### ISSUE TITLE
创建Kubernetes证书时错误

### ISSUE THREAD

**Issue by rootsongjc** [opsnull/follow-me-install-kubernetes-cluster#1]
按照第一篇文档**创建 kubernetes 各组件 TLS 加密通信的证书和秘钥**中介绍，执行下面的命令，json文件与文档中相同，只不过是更改为我自己的IP地址。
```
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kubernetes-csr.json | cfssljson -bare kubernetes
```
**报错信息**
```
Failed to load config file: {"code":5200,"message":"failed to unmarshal configuration: invalid character '\"' after array element"}Failed to parse input: unexpected end of JSON input
```
以第二种方式执行
```
echo '{"CN":"kubernetes","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes -hostname="127.0.0.1,172.20.0.112,172.20.0.113,172.20.0.114,172.20.0.115,254.0.1,kubernetes,kubernetes.default" - | cfssljson -bare kubernetes
```
依然报上述错误。

**环境信息**
```
$cfssl version
Version: 1.2.0
Revision: dev
Runtime: go1.7.5
```
我使用go get方式安装的。

**Comment by rootsongjc** [comment]
个人配置错误，`ca-config.json`文件中少了个逗号。

**Comment by LLj-github-operations-develop** [comment]
{"code":5100,"message":"Invalid policy: no key usage available"}
Failed to parse input: unexpected end of JSON input

solve:
     #用来生成 CA 文件的 JSON 配置文件，例如 ca-config.json
cat << EOF > ca-config.json 
{
  "signing": {
    "default": {
      "expiry": "8760h"
    },
    "profiles": {
      "etcd": {  ###########这块的etcd属性
        "usages": [
          "signing",
          "key encipherment",
          "server auth",
          "client auth"
        ],
        "expiry": "8760h"
      }
    }
  }
}
EOF

#为服务器生成密钥和证书，生成的秘钥和证书分别默认保存在文件 server-key.pem 和 server.pem中
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=etcd server-csr.json | cfssljson -bare server
-profile=etcd server-csr.json 上面的ca-config.json中etcd属性应用到了这块
