### ISSUE TITLE
我想在master机器也当做node来使用，approve kubelet后获取node发现没有添加当前节点进来

### ISSUE THREAD

**Issue by xuguangwu** [opsnull/follow-me-install-kubernetes-cluster#103]
由于机器不足，就准备在一台机器上做个单master单minion的，我尝试了添加另一台主机到集群中，是成功的，但是由于那台机器与master内网是不通的，所以只能先尝试单台机器上部署，于是遇到了这个问题，求助

**Comment by opsnull** [comment]
看看 kubelet 的日志。

**Comment by opsnull** [comment]
@xuguangwu 问题解决了么？
