### ISSUE TITLE
安装 heapster ， influxdb起不来

### ISSUE THREAD

**Issue by langtu329** [opsnull/follow-me-install-kubernetes-cluster#105]
您好，麻烦看一下这个错误是什么问题
![image](https://user-images.githubusercontent.com/9998362/28262914-7b2f3f14-6b17-11e7-8097-469116df603a.png)

**influxdb日志**
Status:		Running
IP:		192.30.28.6
Controllers:	ReplicaSet/monitoring-influxdb-16771525
Containers:
  influxdb:
    Container ID:	docker://99057a764ceef47b6dc565e2c8505c3019b189109eb6e057c3fbace9637ded56
    Image:		registry.cn-hangzhou.aliyuncs.com/google-containers/heapster-influxdb-amd64:v1.1.1
    Image ID:		docker-pullable://registry.cn-hangzhou.aliyuncs.com/google-containers/heapster-influxdb-amd64@sha256:15d48e8a864d73e763f6eb7a010e93902cf625967062bdf25a055098a6aac634
    Port:		
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Mon, 01 Jan 0001 00:00:00 +0000
      Finished:		Mon, 17 Jul 2017 17:29:32 +0800
    Ready:		False
    Restart Count:	15
    Environment:	<none>
    Mounts:
      /data from influxdb-storage (rw)
      /etc/ from influxdb-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mr5h8 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  influxdb-storage:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  influxdb-config:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	influxdb-config
    Optional:	false
  default-token-mr5h8:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-mr5h8
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>

Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "influxdb" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=influxdb pod=monitoring-influxdb-16771525-ms5vx_kube-system(1e32e8b7-6ace-11e7-aa81-00163e00135b)"

**Comment by opsnull** [comment]
贴的日志看不出来错误信息。
看看 kubelet、kubectl describe pod xxx 的日志。

**Comment by langtu329** [comment]
麻烦看一下，自己也不太确定
kubelet日志
**Couldn't find network status for kube-system/monitoring-influxdb-16771525-q4174 through plugin: invalid network status for**
Jul 18 09:37:12 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:12.168029    4619 kubelet.go:1842] SyncLoop (PLEG): "monitoring-influxdb-16771525-q4174_kube-system(9cae4625-6b59-11e7-aa81-00163e00135b)", event: &pleg.PodLifecycleEvent{ID:"9cae4625-6b59-11e7-aa81-00163e00135b", Type:"ContainerDied", Data:"88dbe1e9cd13a9281c9b5165776b0938194ef2c729a5c775a354e43faef7b861"}
Jul 18 09:37:12 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:12.199756    4619 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/9cae4625-6b59-11e7-aa81-00163e00135b-default-token-mr5h8" (spec.Name: "default-token-mr5h8") pod "9cae4625-6b59-11e7-aa81-00163e00135b" (UID: "9cae4625-6b59-11e7-aa81-00163e00135b").
Jul 18 09:37:12 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:12.200822    4619 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/9cae4625-6b59-11e7-aa81-00163e00135b-influxdb-config" (spec.Name: "influxdb-config") pod "9cae4625-6b59-11e7-aa81-00163e00135b" (UID: "9cae4625-6b59-11e7-aa81-00163e00135b").
Jul 18 09:37:12 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:12.468973    4619 kuberuntime_manager.go:458] Container {Name:influxdb Image:registry.cn-hangzhou.aliyuncs.com/google-containers/heapster-influxdb-amd64:v1.1.1 Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:influxdb-storage ReadOnly:false MountPath:/data SubPath:} {Name:influxdb-config ReadOnly:false MountPath:/etc/ SubPath:} {Name:default-token-mr5h8 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jul 18 09:37:12 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:12.469190    4619 kuberuntime_manager.go:742] checking backoff for container "influxdb" in pod "monitoring-influxdb-16771525-q4174_kube-system(9cae4625-6b59-11e7-aa81-00163e00135b)"
Jul 18 09:37:12 iZbp12b35n77zayo2snxmlZ kubelet[4619]: W0718 09:37:12.699323    4619 container.go:352] Failed to create summary reader for "/kubepods/besteffort/pod9cae4625-6b59-11e7-aa81-00163e00135b/e98c435c51f7c24b49fda6a1ec16860afe321e6a8a20b079446f4f54d0486a1c": none of the resources are being tracked.
Jul 18 09:37:12 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:12.699494    4619 helpers.go:101] Unable to get network stats from pid 29884: **couldn't read network stats: failure opening /proc/29884/net/dev: open /proc/29884/net/dev: no such file or directory**
Jul 18 09:37:13 iZbp12b35n77zayo2snxmlZ kubelet[4619]: W0718 09:37:13.183513    4619 docker_sandbox.go:263] Couldn't find network status for kube-system/monitoring-influxdb-16771525-q4174 through plugin: invalid network status for
Jul 18 09:37:13 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:13.190562    4619 kubelet.go:1842] SyncLoop (PLEG): "monitoring-influxdb-16771525-q4174_kube-system(9cae4625-6b59-11e7-aa81-00163e00135b)", event: &pleg.PodLifecycleEvent{ID:"9cae4625-6b59-11e7-aa81-00163e00135b", Type:"ContainerDied", Data:"e98c435c51f7c24b49fda6a1ec16860afe321e6a8a20b079446f4f54d0486a1c"}
Jul 18 09:37:13 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:13.203719    4619 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/9cae4625-6b59-11e7-aa81-00163e00135b-default-token-mr5h8" (spec.Name: "default-token-mr5h8") pod "9cae4625-6b59-11e7-aa81-00163e00135b" (UID: "9cae4625-6b59-11e7-aa81-00163e00135b").
Jul 18 09:37:13 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:13.204538    4619 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/9cae4625-6b59-11e7-aa81-00163e00135b-influxdb-config" (spec.Name: "influxdb-config") pod "9cae4625-6b59-11e7-aa81-00163e00135b" (UID: "9cae4625-6b59-11e7-aa81-00163e00135b").
Jul 18 09:37:13 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 09:37:13.492353    4619 kuberuntime_manager.go:458] Container {Name:influxdb Image:registry.cn-hangzhou.aliyuncs.com/google-containers/heapster-influxdb-amd64:v1.1.1 Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:influxdb-storage ReadOnly:false MountPath:/data SubPath:} {Name:influxdb-config ReadOnly:false MountPath:/etc/ SubPath:} {Name:default-token-mr5h8 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.

**Comment by langtu329** [comment]
@opsnull

**Comment by langtu329** [comment]
@opsnull  麻烦帮我看看哪里错误了
**influxdb日志**
Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/configmap/bf05ecbe-6b9c-11e7-aa81-00163e00135b-influxdb-config" (spec.Name: "influxdb-config") pod "bf05ecbe-6b9c-11e7-aa81-00163e00135b" (UID: "bf05ecbe-6b9c-11e7-aa81-00163e00135b") with: remove /var/lib/kubelet/pods/bf05ecbe-6b9c-11e7-aa81-00163e00135b/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy


**kubelet日志**
Jul 18 17:47:52 iZbp12b35n77zayo2snxmlZ kubelet[4619]: E0718 17:47:52.316103    4619 atomic_writer.go:456] pod kube-system/monitoring-influxdb-16771525-r52xn volume influxdb-config: error pruning old user-visible path resolv.conf: remove /var/lib/kubelet/pods/bf05ecbe-6b9c-11e7-aa81-00163e00135b/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy
Jul 18 17:47:52 iZbp12b35n77zayo2snxmlZ kubelet[4619]: E0718 17:47:52.316143    4619 atomic_writer.go:203] pod kube-system/monitoring-influxdb-16771525-r52xn volume influxdb-config: error removing old visible symlinks: remove /var/lib/kubelet/pods/bf05ecbe-6b9c-11e7-aa81-00163e00135b/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy
Jul 18 17:47:52 iZbp12b35n77zayo2snxmlZ kubelet[4619]: E0718 17:47:52.316156    4619 configmap.go:218] Error writing payload to dir: remove /var/lib/kubelet/pods/bf05ecbe-6b9c-11e7-aa81-00163e00135b/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy
Jul 18 17:47:52 iZbp12b35n77zayo2snxmlZ kubelet[4619]: E0718 17:47:52.316249    4619 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/configmap/bf05ecbe-6b9c-11e7-aa81-00163e00135b-influxdb-config\" (\"bf05ecbe-6b9c-11e7-aa81-00163e00135b\")" failed. No retries permitted until 2017-07-18 17:49:52.316219828 +0800 CST (durationBeforeRetry 2m0s). Error: MountVolume.SetUp failed for volume "kubernetes.io/configmap/bf05ecbe-6b9c-11e7-aa81-00163e00135b-influxdb-config" (spec.Name: "influxdb-config") pod "bf05ecbe-6b9c-11e7-aa81-00163e00135b" (UID: "bf05ecbe-6b9c-11e7-aa81-00163e00135b") with: remove /var/lib/kubelet/pods/bf05ecbe-6b9c-11e7-aa81-00163e00135b/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy
Jul 18 17:48:03 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 17:48:03.657497    4619 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/bf05ecbe-6b9c-11e7-aa81-00163e00135b-default-token-mr5h8" (spec.Name: "default-token-mr5h8") pod "bf05ecbe-6b9c-11e7-aa81-00163e00135b" (UID: "bf05ecbe-6b9c-11e7-aa81-00163e00135b").
Jul 18 17:48:04 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 17:48:04.659535    4619 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/bed313b1-6b9c-11e7-aa81-00163e00135b-default-token-mr5h8" (spec.Name: "default-token-mr5h8") pod "bed313b1-6b9c-11e7-aa81-00163e00135b" (UID: "bed313b1-6b9c-11e7-aa81-00163e00135b").
Jul 18 17:48:13 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 17:48:13.698489    4619 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/88277e50-6859-11e7-aa81-00163e00135b-default-token-jn4fv" (spec.Name: "default-token-jn4fv") pod "88277e50-6859-11e7-aa81-00163e00135b" (UID: "88277e50-6859-11e7-aa81-00163e00135b").
Jul 18 17:48:29 iZbp12b35n77zayo2snxmlZ kubelet[4619]: I0718 17:48:29.495746    4619 qos_container_manager_linux.go:285] [ContainerManager]: Updated QoS cgroup configuration

**Comment by opsnull** [comment]
@langtu329  问题解决了么？

**Comment by ww110052181** [comment]
@opsnull 最近有什么打算，还有kubernetes搭建完成以后，有哪些开发的事情可以做

**Comment by helplove** [comment]
问题怎么解决的呢  我也出现这个问题  请教一下
