### ISSUE TITLE
安装完dns后，测试不成功

### ISSUE THREAD

**Issue by tanzhixu** [opsnull/follow-me-install-kubernetes-cluster#107]
安装文中的步骤，安装完成，进行测试，但是测试不成功
[root@10.10.7.175 tmp]# kubectl exec  nginx -i -t -- /bin/bash
root@nginx:/# cat /etc/resolv.conf
nameserver 10.254.0.2
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

root@nginx:/# ping my-nginx
ping: unknown host
root@nginx:/#

**Comment by kaasia** [comment]
你是如何安装的dns

**Comment by CloudPeter** [comment]
我也是一样的错误。我按照文档里一步步走下去的，但总是启动不了
NAME                                   READY     STATUS             RESTARTS   AGE
kube-dns-2239791558-v5n4z              1/3       CrashLoopBackOff   435        4d
kubernetes-dashboard-548151799-xjl71   1/1       Running            209        4d

**Comment by tanzhixu** [comment]
找的问题了，是docker的启动配置有问题，$DOCKER_NETWORK_OPTIONS这个参数没有传递进去

**Comment by opsnull** [comment]
$DOCKER_NETWORK_OPTIONS 在文档中有特别的说明，严格 follow 文档，愉快和 k8s 玩耍。:P
