### ISSUE TITLE
06.node  向 etcd 写入集群 Pod 网段信息  的修改意见

### ISSUE THREAD

**Issue by it2911** [opsnull/follow-me-install-kubernetes-cluster#11]
/root/local/bin/etcdctl \
  --endpoints=http://127.0.0.1:2379  \     →　  --endpoints=https://127.0.0.1:2379  \ 
  --ca-file=/etc/kubernetes/ssl/ca.pem \
  --cert-file=/etc/kubernetes/ssl/kubernetes.pem \
  --key-file=/etc/kubernetes/ssl/kubernetes-key.pem \
  set ${FLANNEL_ETCD_PREFIX}/config '{"Network":"172.30.0.0/16", "SubnetLen": 24, "Backend": {"Type": "vxlan"}}'

**Comment by opsnull** [comment]
请看 etcd 的 systemd unit 文件，127.0.0.1:2379 对应的是 http 协议，而非 https 协议，故不能修改；

BTW，请看最新提交的文档，这一部分不使用 127.0.0.1 地址了。
