### ISSUE TITLE
这文档这么多命令，哪些要在哪个机器执行都没写。。。

### ISSUE THREAD

**Issue by xskh2007** [opsnull/follow-me-install-kubernetes-cluster#112]
这文档这么多命令，哪些要在哪个机器执行都没写。。。莫非三个机器都要执行？

**Comment by opsnull** [comment]
README.md 中的说明：

> 本文档主要适合于那些有一定 kubernetes 基础，想通过一步步部署的方式来学习和了解系统配置、运行原理的人。
