### ISSUE TITLE
ubuntu下添加系统服务为啥会失败

### ISSUE THREAD

**Issue by ww110052181** [opsnull/follow-me-install-kubernetes-cluster#114]
-- Unit etcd.service has begun starting up.
Aug 09 21:30:51 ubuntu etcd[48108]: etcd Version: 3.2.4
Aug 09 21:30:51 ubuntu etcd[48108]: Git SHA: c31bec0
Aug 09 21:30:51 ubuntu etcd[48108]: Go Version: go1.8.3
Aug 09 21:30:51 ubuntu etcd[48108]: Go OS/Arch: linux/amd64
Aug 09 21:30:51 ubuntu etcd[48108]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Aug 09 21:30:51 ubuntu etcd[48108]: the server is already initialized as member before, starting as etcd member...
Aug 09 21:30:51 ubuntu etcd[48108]: peerTLS: cert = /etc/etcd/ssl/etcd.pem, key = /etc/etcd/ssl/etcd-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/ca.pem, client-cert-auth = false
Aug 09 21:30:51 ubuntu etcd[48108]: listening for peers on https://192.168.137.133:2380
Aug 09 21:30:51 ubuntu etcd[48108]: The scheme of client url http://127.0.0.1:2379 is HTTP while peer key/cert files are presented. Ignored key/cert files.
Aug 09 21:30:51 ubuntu etcd[48108]: listening for client requests on 127.0.0.1:2379
Aug 09 21:30:51 ubuntu etcd[48108]: listening for client requests on 192.168.137.133:2379
Aug 09 21:30:51 ubuntu etcd[48108]: --initial-cluster must include ubuntu=https://192.168.137.133:2380 given --initial-advertise-peer-urls=https://192.168.137.133:2380
Aug 09 21:30:51 ubuntu systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Aug 09 21:30:51 ubuntu systemd[1]: Failed to start Etcd Server.
-- Subject: Unit etcd.service has failed

**Comment by opsnull** [comment]
> Aug 09 21:30:51 ubuntu etcd[48108]: --initial-cluster must include ubuntu=https://192.168.137.133:2380 given --initial-advertise-peer-urls=https://192.168.137.133:2380

你配置错了。
