### ISSUE TITLE
06 node docker安装部分的小瑕疵

### ISSUE THREAD

**Issue by it2911** [opsnull/follow-me-install-kubernetes-cluster#12]
$ wget https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz
$ tar -xvf docker-17.04.0-ce.tgz
$ cp docker/docker* /root/local/bin
$ cp completion/bash/docker /etc/bash_completion.d/  -> cp docker/completion/bash/docker /etc/bash_completion.d/

**Comment by opsnull** [comment]
多谢指出，已修复。
