### ISSUE TITLE
纠错：registry 支持 s3 访问 ceph rgw

### ISSUE THREAD

**Issue by JinsYin** [opsnull/follow-me-install-kubernetes-cluster#121]
原文：https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/12-%E9%83%A8%E7%BD%B2Docker-Registry.md#创建-demo-账号的子账号-swift

registry 配置：https://docs.docker.com/registry/configuration/#list-of-configuration-options

另外，rados 兼容 s3 和 Swift

**Comment by opsnull** [comment]
原文说的不严谨，准确地说是：registry 只支持 AWZ 的标准 S3 协议，ceph 对 AWZ S3 的支持有些兼容性问题，特别是  AWS v4 signatures，目前还有 bug( https://github.com/ceph/ceph/pull/17040，http://tracker.ceph.com/issues/17076，https://github.com/ceph/ceph/pull/15965)，我实际测试的过程中是失败的。

**Comment by JinsYin** [comment]
另外，我有一个小的建议：registry 改用环境变量来配置，见https://docs.docker.com/registry/configuration/#override-specific-configuration-options 。因为如果使用 swarm、k8s 来部署的话需要确保所有节点都具有配置文件 `/etc/docker/registry/config.yml` ，如果过程还要进行修改的话就更麻烦了。
