### ISSUE TITLE
请问如何关闭api-server 8080端口的对外访问？

### ISSUE THREAD

**Issue by mohaijiang** [opsnull/follow-me-install-kubernetes-cluster#126]
希望就算是内网也不允许访问8080端口，仅master本机可以访问

自己找到了
          --insecure-bind-address ip                                The IP address on which to serve the --insecure-port (set to 0.0.0.0 for all interfaces). (default 127.0.0.1)

还是建议一下默认关闭这个端口

**Comment by 4220182** [comment]
kube-apiserver 打开8080确实是一个安全隐患。

如果关闭了8080，文档中kube-controller-manager、kube-scheduler 就连不上kube-apiserver,
我尝试使用kube-apiserver 的https端口，这里涉及到RBAC权限问题，不知道如何设置。
有人能够共享一下如果配置kube-controller-manager、kube-scheduler 连接cube-apiserver的https端口？

**Comment by mohaijiang** [comment]
@4220182 需要将 kube-apiserver.service kube-controller-manager.service kube-scheduler.service 同步修改
kube-controller-manager.service和kube-scheduler.service `--master=http://127.0.0.1:8080 `
kube-apiserver.service  --insecure-bind-address 参数去除或修改成`--insecure-bind-address=127.0.0.1`
