### ISSUE TITLE
05-部署Flannel网络 错误问题

### ISSUE THREAD

**Issue by 3792274** [opsnull/follow-me-install-kubernetes-cluster#129]
向 etcd 写入集群 Pod 网段信息
注意：本步骤只需在第一次部署 Flannel 网络时执行，后续在其它节点上部署 Flannel 时无需再写入该信息！
```
$ /root/local/bin/etcdctl \
  --endpoints=${ETCD_ENDPOINTS} \
  --ca-file=/etc/kubernetes/ssl/ca.pem \
  --cert-file=/etc/flanneld/ssl/flanneld.pem \
  --key-file=/etc/flanneld/ssl/flanneld-key.pem \
  set ${FLANNEL_ETCD_PREFIX}/config '{"Network":"'${CLUSTER_CIDR}'", "SubnetLen": 24, "Backend": {"Type": "vxlan"}}'
```
--------------------------
以下是我执行过程，不知道哪里的问题：
**: invalid character "\r" in host name**

----------------------

 
![image](https://user-images.githubusercontent.com/19231863/30043531-7fe1529c-922a-11e7-9f78-6eb434711c1d.png)

**Comment by wlmvp** [comment]
我也遇到同样的问题 好像是etcdctl不认识${ETCD_ENDPOINTS}  替换为ip地址之后写入 但是后面部署好像有问题 提示：
Sep 09 07:09:49 localhost.localdomain flanneld[5233]: E0909 07:09:49.298372    5233 network.go:102] failed to retrieve network config: 100: Key not found (/kubernetes/network) [17

**Comment by thsheep** [comment]
sh 到进来的会有\r 不用使用  单独写环境变量即可

**Comment by 3792274** [comment]
谢谢，解决！
