### ISSUE TITLE
EFK中image url已经失效

### ISSUE THREAD

**Issue by ibuler** [opsnull/follow-me-install-kubernetes-cluster#131]
1. es-controller    https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/manifests/EFK/es-controller.yaml#L25

2. fluentd https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/manifests/EFK/fluentd-es-ds.yaml#L27

3. kibana https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/manifests/EFK/kibana-controller.yaml#L22

**Comment by taoleilinux** [comment]
请问下，您按照作者的方法搭建，kubelet组件安装好后，有没有始终报错 [Failed to start ContainerManager failed to initialise top level QOS containers: root container /kubepods doesn't exist]，我是单机部署，所以没有用到flanneld，请问您知道原因吗

**Comment by hekan321** [comment]
同问~~

**Comment by taoleilinux** [comment]
@hekan321 你如果问的是我这个错，可以查看https://github.com/opsnull/follow-me-install-kubernetes-cluster/issues/133

**Comment by hekan321** [comment]
@taoleilinux 不是 我是问 EFK镜像失效的问题

**Comment by opsnull** [comment]
这个是 k8s 的 bug，已修复：https://github.com/kubernetes/kubernetes/pull/44940。

**Comment by opsnull** [comment]
最新的文档已更新 image 链接。
