### ISSUE TITLE
加入节点，kubelet报错

### ISSUE THREAD

**Issue by taoleilinux** [opsnull/follow-me-install-kubernetes-cluster#133]
[root@3-227 ~]# systemctl status kubelet -l
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: **active (running)** since 一 2017-09-11 18:02:27 CST; 26s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 23173 ExecStartPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP (code=exited, status=0/SUCCESS)
  Process: 23172 ExecStartPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 23167 ExecStartPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 23165 ExecStartPost=/sbin/iptables -A INPUT -s 172.17.0.0/16 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
 Main PID: 23164 (kubelet)
   Memory: 25.5M
   CGroup: /system.slice/kubelet.service
           ├─23164 /root/local/bin/kubelet --address=192.168.3.227 --hostname-override=192.168.3.227 --pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --require-kubeconfig --cert-dir=/etc/kubernetes/ssl --cluster-dns=10.254.0.100 --cluster-domain=cluster.local. --hairpin-mode promiscuous-bridge --allow-privileged=true --serialize-image-pulls=false --logtostderr=true --v=2
           └─23227 journalctl -k -f

9月 11 18:02:27 3-227 kubelet[23164]: I0911 18:02:27.860157   23164 kubelet_node_status.go:379] Recording NodeHasSufficientDisk event message for node 192.168.3.227
9月 11 18:02:27 3-227 kubelet[23164]: I0911 18:02:27.860710   23164 kubelet_node_status.go:379] Recording NodeHasSufficientMemory event message for node 192.168.3.227
9月 11 18:02:27 3-227 kubelet[23164]: I0911 18:02:27.861114   23164 kubelet_node_status.go:379] Recording NodeHasNoDiskPressure event message for node 192.168.3.227
9月 11 18:02:27 3-227 kubelet[23164]: I0911 18:02:27.861529   23164 kubelet_node_status.go:379] Recording NodeNotReady event message for node 192.168.3.227
9月 11 18:02:27 3-227 kubelet[23164]: I0911 18:02:27.861906   23164 kubelet_node_status.go:682] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2017-09-11 18:02:27.861518794 +0800 CST LastTransitionTime:2017-09-11 18:02:27.861518794 +0800 CST Reason:KubeletNotReady Message:Failed to start ContainerManager failed to initialise top level QOS containers: root container /kubepods doesn't exist,container runtime is down}
9月 11 18:02:32 3-227 kubelet[23164]: I0911 18:02:32.727246   23164 kubelet.go:1752] skipping pod synchronization - [Failed to start ContainerManager failed to initialise top level QOS containers: root container /kubepods doesn't exist]

出现上面的错误，[Failed to start ContainerManager failed to initialise top level QOS containers: root container /kubepods doesn't exist]，检查了很多遍，应该不是我配置错误。

我的环境是centos 4.13.0-1.el7.elrepo.x86_64，其余配置和作者一样，唯一区别是我是单机，没有用flanneld，是自己在单机上测试的。

我也搜了很多，有人说加参数 --cgroups-per-qos=false   --enforce-node-allocatable="" ，但是我加了没用，想请问作者这是什么原因？

**Comment by taoleilinux** [comment]
作者你好，我今天早上，把之前看你教程安装的集群都清空了，重新部署了一遍，但还是报上面这个错，日志报错也就是上面这信息，麻烦你帮忙看看。

**Comment by taoleilinux** [comment]
今天试了三台机安装，发现没问题了，看来这个部署必须的是三台的环境。希望大家看注意。

**Comment by taoleilinux** [comment]
今天又检查了一下，不是必须三台机才行，而是内核的问题。我今天在一台虚拟机上又安装了一遍，用的centos7最初的内核版本3.10，结果成功了。之前失败的原因是内核都是最新的4.12 。

**Comment by lovejoy** [comment]
这里的问题是这个版本的内核的cgroup里面多了个rdma功能，所以你需要创建/sys/fs/cgroup/rdma/kubepods这个目录，这样kubelet能跑起来，但是pods跑不起来。。。 我还在找原因

**Comment by taoleilinux** [comment]
嗯嗯，谢谢了，我现在就是用的最初的内核。如果实在找不到原因，你可以先不要用这么新的内核，后面新版的k8s应该没有这问题。

**Comment by lovejoy** [comment]
3.10 内核有问题会kernel panic

**Comment by taoleilinux** [comment]
你怎么碰到的，我没有遇到啊

**Comment by lovejoy** [comment]
给pod设置cpu使用的上限，压力大的时候就会发生

**Comment by lovejoy** [comment]
更新下，上面那个说新内核有问题的是别的问题，创建那个目录后就能正常跑pod

**Comment by taoleilinux** [comment]
你现在可以成功跑起来pod了吗？没问题了？
