### ISSUE TITLE
registry-mirrors仓库加速设置不生效

### ISSUE THREAD

**Issue by seecsea** [opsnull/follow-me-install-kubernetes-cluster#134]
$ cat /etc/docker/daemon.json
{
  "registry-mirrors": ["https://docker.mirrors.ustc.edu.cn", "hub-mirror.c.163.com"],
  "max-concurrent-downloads": 10
}
按照这个设置重启docker后，docker info最后看不到仓库加速的设置
按照如下格式设置完整的URL就OK了
{
  "registry-mirrors": ["https://docker.mirrors.ustc.edu.cn", "http://hub-mirror.c.163.com"],
  "max-concurrent-downloads": 10
}

**Comment by opsnull** [comment]
多谢反馈！下一次文档更新时包含进来。

**Comment by lmxin123** [comment]
我的win10 设置了一直不生效，我的docker版本是 19.03.8
