### ISSUE TITLE
证书生成问题

### ISSUE THREAD

**Issue by heyinhenu** [opsnull/follow-me-install-kubernetes-cluster#136]
$ cfssl print-defaults config > config.json
$ cfssl print-defaults csr > csr.json
下面的这个cat ca-config.json这个文件从哪里来的,是不是上面的cfssl print-defaults config > ca-config.json  少写了ca-，类似下面的cat ca-csr.json  这个文件也是不是漏掉了ca-

**Comment by opsnull** [comment]
按照 `cat ca-config.json` 的输出，自己创建 ca-config.json 文件。
 print-defaults 命令的目的是让你知道配置文件的格式和可以配置的内容，具体可以参考 cfssl github 项目的文档。
