### ISSUE TITLE
部署flannel，Docker0和flannel0不在同一段内

### ISSUE THREAD

**Issue by heyinhenu** [opsnull/follow-me-install-kubernetes-cluster#138]
mk-docker-opts.sh 脚本将分配给 flanneld 的 Pod 子网网段信息写入到 /run/flannel/docker 文件中，后续 docker 启动时使用这个文件中参数值设置 docker0 网桥

----------result--------------------------------

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.253.72.0  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::7849:62ff:fe2b:e3ae  prefixlen 64  scopeid 0x20<link>
        ether 7a:49:62:2b:e3:ae  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 10 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:b0:7d:7a:58  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

结果Docker0和flannel0不在同一段内,/run/flannel/docker的文件内容如下：
DOCKER_OPT_BIP="--bip=10.253.72.1/24"
DOCKER_OPT_IPMASQ="--ip-masq=true"
DOCKER_OPT_MTU="--mtu=1450"
DOCKER_NETWORK_OPTIONS=" --bip=10.253.72.1/24 --ip-masq=true --mtu=1450"

请脚下大家有碰到吗？  万分感谢！

/run/flannel/subnet.env 这个文件中内容：

FLANNEL_NETWORK=10.253.0.0/16
FLANNEL_SUBNET=10.253.72.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false

但是docker的ip确是：inet 172.17.0.1 netmask 255.255.0.0 broadcast 0.0.0.0

**Comment by heyinhenu** [comment]
/run/flannel/subnet.env 这个文件中内容：

FLANNEL_NETWORK=10.253.0.0/16
FLANNEL_SUBNET=10.253.72.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false


但是docker的ip确是：inet 172.17.0.1 netmask 255.255.0.0 broadcast 0.0.0.0

**Comment by taoleilinux** [comment]
你应该是之前docker有缓存没删除，把docker重装吧，还有记得把/var/lib/docker和/var/run/docker/var/run/docker/这两目录删了。

**Comment by heyinhenu** [comment]
@taoleilinux  不行，已经试过了，不是docker缓存的问题，安装的时候就没有docker 刚才删除了docker的全部文件，重新安装后，仍是如此。

**Comment by taoleilinux** [comment]
你的docker和flanneld安装步骤都是按照作者的方法来的？

**Comment by heyinhenu** [comment]
@taoleilinux  是的 都是按照这个来的   弄到了05Flannel 这一步了

**Comment by opsnull** [comment]
docker 在 "07-部署Node节点.md" 文档中部署，特别注意的是 docker.service unit 文件中的：
```
Environment="PATH=/root/local/bin:/bin:/sbin:/usr/bin:/usr/sbin"
EnvironmentFile=-/run/flannel/docker
ExecStart=/root/local/bin/dockerd --log-level=error $DOCKER_NETWORK_OPTIONS
```
这里systemd在启动 dockerd 进程前，先导入flannel生成的网络相关环境变量 DOCKER_NETWORK_OPTIONS ，然后dockerd 命令行上使用它。

你需要：
1. 清理旧的 docker 配置文件；
2. 确保 docker systemd unit 的配置如上即可；

**Comment by heyinhenu** [comment]
@opsnull  谢谢问题已经解决。

**Comment by jasonys820** [comment]
@xierui921326 如果你的 docker 已经设置 enable，那就ps一下看看你的 .service 配置文件里加的内容有没有生效，没生效应该是修改配置文件的位置不对。。

**Comment by JoeyX-u** [comment]
@xierui921326  docker配置文件里面 注意$DOCKER_NETWORK_OPTIONS 这个变量，看看有没有添加
