### ISSUE TITLE
在各节点上部署完 Flannel 后，分配的网关地址ping不通

### ISSUE THREAD

**Issue by peter20170715** [opsnull/follow-me-install-kubernetes-cluster#141]
在3个节点上分别部署了flannel，查看已分配的pod子网段列表：
$ /root/local/bin/etcdctl \
  --endpoints=${ETCD_ENDPOINTS} \
  --ca-file=/etc/kubernetes/ssl/ca.pem \
  --cert-file=/etc/flanneld/ssl/flanneld.pem \
  --key-file=/etc/flanneld/ssl/flanneld-key.pem \
  ls ${FLANNEL_ETCD_PREFIX}/subnets
/kubernetes/network/subnets/172.30.69.0-24
/kubernetes/network/subnets/172.30.101.0-24
/kubernetes/network/subnets/172.30.38.0-24
在各节点上分配 ping 这三个网段的网关地址，都ping不通，请问如何解决？
另外我在装完node后，验证集群功能时，执行：
$ kubectl get svc |grep nginx-ds
nginx-ds     10.254.69.112   <nodes>       80:8744/TCP         11m
$ curl 10.254.69.112  
结果出不来，是不是跟之前的网段不通有关？

**Comment by opsnull** [comment]
curl 失败肯定与 pod 网络不通有关。

看起来你的 flanneld 已经正常启动和配置了，pod 网络不通很可能是 iptables 的原因，建议检查下 iptables 规则，看是否有 drop 或 refuse 的情况。

**Comment by peter20170715** [comment]
谢谢您的回复，我对iptable不是很熟，如果您有什么方法或建议，希望您能告知，我也排查一下。再次感谢。

**Comment by peter20170715** [comment]
master上的iptable规则是：
[root@k8s-1 ~]# iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
[root@k8s-1 ~]# iptables -L 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
[root@k8s-1 ~]# 
------------------------------------------------
node上的规则是：
[root@k8s-2 ~]# iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     tcp  --  10.0.0.0/8           0.0.0.0/0            tcp dpt:4194
ACCEPT     tcp  --  172.16.0.0/12        0.0.0.0/0            tcp dpt:4194
ACCEPT     tcp  --  192.168.0.0/16       0.0.0.0/0            tcp dpt:4194
DROP       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:4194

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-SERVICES (1 references)
target     prot opt source               destination         
----------------------------------------------
从规则上看，有什么问题吗？iptable这个功能必须要用吗？可不可以关闭它？

**Comment by peter20170715** [comment]
问题找到，docker启动时，没有绑定ip，问题已经解决。

**Comment by yunlzheng** [comment]
@peter20170715 请问一下没绑定ip是什么情况？
我这边也出现了一样的问题。flannel正常运行起来并且都分配了子网，但是node上ping网关都不通，部署起来的pod跨主机访问也不通。

现在在所有节点上把iptables全部开放了
```
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT  
sudo iptables -P FORWARD ACCEPT
```

**Comment by peter20170715** [comment]
我觉得上他的手册写的不够严谨，后来我用其他的方式搭建了。




发自网易邮箱大师


在2017年11月29日 17:09，ylzheng<notifications@github.com> 写道：

@peter20170715 请问一下没绑定ip是什么情况？
我这边也出现了一样的问题。flannel正常运行起来并且都分配了子网，但是node上ping网关都不通，部署起来的pod跨主机访问也不通。

现在在所有节点上把iptables全部开放了

sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT  
sudo iptables -P FORWARD ACCEPT

**Comment by Wheeling** [comment]
我也拜读到“部署 Flannel 网络”这一章，一步一步下来，flanneld三台机器都启动成功了，三个网段都分配了。但是网关Ping不通。三台机器的iptables全是disable的。求解。

**Comment by baifuwa** [comment]
之前我安装没有遇到这个问题，这次也遇到了，查了好久，才找到，添加iptable 规则确实能解决
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT

**Comment by jiangxiaoqiang** [comment]
我也遇到同样的问题，经过实际验证，用@baifuwa的方式能够解决

**Comment by unbelievableMyself** [comment]
遇到了同样的问题，运行
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT 

运行上述命令后，还是没有解决，怎么办呢

**Comment by baifuwa** [comment]
你分别在对应的节点上执行一下如下命令试一下
iptables -t nat -I POSTROUTING -s 172.30.69.0/24 -j MASQUERADE 
iptables -t nat -I POSTROUTING -s 172.30.101.0/24 -j MASQUERADE 
iptables -t nat -I POSTROUTING -s 172.30.38.0/24 -j MASQUERADE

**Comment by JokerDevops** [comment]
这个问题最后怎么解决的？我一用 flannel 就有问题，我用的 host-gw 模式，路由信息都正常。

宿主机 ping  另一台机器上的  pod 然后在另一台机器上抓包看到有返回包。但是就是不通
```
# 第一台宿主机 ping pod
[173 ops]# ping 172.20.3.10


# pod 所在的宿主机抓包
[ops]# tcpdump icmp
23:49:38.666359 IP 172.18.154.173 > 172.20.3.10: ICMP echo request, id 51638, seq 1, length 64
23:49:38.666512 IP 172.20.3.10 > 172.18.154.173: ICMP echo reply, id 51638, seq 1, length 64
```

**Comment by JokerDevops** [comment]
补充一下，我的 iptables 防火墙策略默认都是允许的
