### ISSUE TITLE
请问按照作者搭建的这套k8s环境，可以做生产环境吗

### ISSUE THREAD

**Issue by taoleilinux** [opsnull/follow-me-install-kubernetes-cluster#143]
按照作者的方法搭建好了，在测试环境上用起来也还可以，想请问下大家这套环境可以做生产环境吗？还有就是对rbac的理解还不是特别清晰，是所有跑在集群里的服务都要进行认证还是只是要访问api的服务需要认证呢？

**Comment by opsnull** [comment]
本文档只是部署一个能 work 的系统，离生产环境还有差距，你可以看看 openShift 提供的生产环境能力。

RBAC 只是对访问 API 的服务做授权。

**Comment by taoleilinux** [comment]
那请问下，作为生产环境还有什么没达到的吗？我现在只是跑些公司的小型业务，没什么访问量。

**Comment by taoleilinux** [comment]
@opsnull 那请问下，作为生产环境还有什么没达到的吗？我现在只是跑些公司的小型业务，没什么访问量。
