### ISSUE TITLE
通过kube-apiserver访问dashboard报错

### ISSUE THREAD

**Issue by NUABO** [opsnull/follow-me-install-kubernetes-cluster#145]
[root@doc1 ~]# kubectl cluster-info
Kubernetes master is running at https://192.168.1.182:6443
KubeDNS is running at https://192.168.1.182:6443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://192.168.1.182:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
在浏览器访问URL http://192.168.1.182:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/ 后报错：
Error: 'dial tcp 172.17.0.3:9090: getsockopt: no route to host'
Trying to reach: 'http://172.17.0.3:9090/'
请问如何解决，使用 http://NodeIP:nodePort 地址或通过kubectl proxy也无法访问，不知道哪里出错了

**Comment by jmgao1983** [comment]
'http://172.17.0.3:9090/'是pod的内部地址，请检查两件事情：
1.看下你每个节点 iptables的filter表FORWARD有没有允许
2.该pod是否正常运行，kubectl exec -it xxxx bash 查看下

**Comment by jmgao1983** [comment]
'http://172.17.0.3:9090/'是pod的内部地址，请检查两件事情：
1.看下你每个节点 iptables的filter表FORWARD有没有允许
2.该pod是否正常运行，kubectl exec -it xxxx bash 查看下

**Comment by ofly** [comment]
使用 http://NodeIP:nodePort 地址可以访问，但是使用APIServer和proxy就无法访问，提示：
Error: 'dial tcp 172.10.34.3:9090: getsockopt: connection timed out'
Trying to reach: 'http://172.10.34.3:9090/'
请问怎么排查这个问题

**Comment by opsnull** [comment]
@ofly 是的，如果通过 apiserver 访问服务，需要 apiserver 也部署 flannel，这样 apiserver 就可以访问
 service ip 对应的 pod ip ，即 apiserver 和 pod 网络互通了。

**Comment by motecshine** [comment]
访问dashboard 有同样的问题 我的master 节点没有充当node ，在master通过api-server 访问dashboard 会出现这个错误
 
` Error: 'dial tcp 172.17.0.3:9090: getsockopt: no route to host'
Trying to reach: 'http://172.17.0.3:9090/' `

**Comment by JasonYLong** [comment]
这里需要检查一下 dashboard 容器跑再哪个节点上
kubectl --namespace kube-system get pods -o wide
NAME                                    READY     STATUS             RESTARTS   AGE       IP            NODE
kubernetes-dashboard-65f7b4f486-v7szz   1/1       Running            1          23h       172.30.4.3    kube-node2
然后用对应节点的 ip 访问即可。
https://172.27.129.111:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default
