### ISSUE TITLE
关于升级

### ISSUE THREAD

**Issue by Tizeen** [opsnull/follow-me-install-kubernetes-cluster#146]
你好，集群部署成功之后，如果有新版本，我该怎么进行升级

是直接替换服务的二进制文件重启服务？还是有其他需要注意的地方

谢谢。

**Comment by jmgao1983** [comment]
基本上是的，等你这套环境熟悉后，升级肯定不是问题

**Comment by Tizeen** [comment]
@jmgao1983 好的，谢谢。
我目前是按教程搭了一套环境，最近想升级到1.7，怕版本变化导致升级失败，所以来问一下。
有时间我试试
