### ISSUE TITLE
导入admin.p12仍然无法访问安全端口？

### ISSUE THREAD

**Issue by Chinaxiang** [opsnull/follow-me-install-kubernetes-cluster#149]
按照文档安装了k8s, 可以使用非安全端口和kube-proxy访问：
http://192.168.163.132:8080
http://192.168.163.132:8086
使用
openssl pkcs12 -export -in admin.pem -out admin.p12 -inkey admin-key.pem
生成了证书，导入到chrome中，重新打开浏览器访问：
https://192.168.163.132:6443/
无法访问，提示：

```
您的连接不是私密连接

攻击者可能会试图从192.168.163.132窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_INVALID
重新加载隐藏详情
192.168.163.132 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 192.168.163.132 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 192.168.163.132，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 192.168.163.132，因为此网站发送的凭据是乱码，Google Chrome 无法处理。网络错误和攻击行为通常是暂时的，因此，此网页稍后可能就会恢复正常。了解详情。
```

[新窗口打开图片](http://ww4.sinaimg.cn/large/a15b4afely1fkne9rh3baj20jc0fewfr)

**Comment by Chinaxiang** [comment]
是不是只能通过非安全方式打开呢？导入证书也打不开呀。
chrome和ie都试了。

**Comment by opsnull** [comment]
看你的截图是证书乱码， chrome 认为该证书无效，拒绝连接。

你可以按照生成 etcd 证书的方法，为你的电脑生成证书(注意 hosts 字段中的 IP 地址为你的电脑 IP），然后导入到系统中。

**Comment by hoperuin** [comment]
先导入ca根证书，再导入admin证书，然后用https://mater ip:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/访问
