### ISSUE TITLE
etcdctl v3如何访问K8S存储的数据呢

### ISSUE THREAD

**Issue by Sam-Chou** [opsnull/follow-me-install-kubernetes-cluster#154]
作者您好，K8S集群的数据存储在etcd中，如果不指定--etcd-prefix参数，数据将会存储在/registry路径下。在etcd v2中可以使用 etcdctl ls /registry -recursive来查看K8S集群的数据，我按照您的教程搭建好了K8S集群，在etcd v3版本中如何使用etcdctl客户端去查看K8S存储的数据呢？

**Comment by opsnull** [comment]
```
  ETCDCTL_API=3 /root/local/bin/etcdctl \
  --endpoints=https://{YOUR_IP}:2379  \
  --cacert=/etc/kubernetes/ssl/ca.pem \
  --cert=/etc/etcd/ssl/etcd.pem \
  --key=/etc/etcd/ssl/etcd-key.pem \
  get /registry --prefix
```

**Comment by KeithTt** [comment]
好棒 终于知道怎么查看k8s的数据了 不过能不能像之前的`ls`一样列出里面的所有目录呢？@opsnull
