### ISSUE TITLE
请问下，我想在用一台腾讯云，一台阿里云，一台华为云，做这个实验，可以行不

### ISSUE THREAD

**Issue by feixia5712** [opsnull/follow-me-install-kubernetes-cluster#156]
感觉这样做的话，网络划分方便有点乱了
还有再请教下，ubuntu14.04上支持不，看你的说明写了ubuntu16以上，
docker的最新版本可以不，您的实验室17.04

**Comment by feixia5712** [comment]
请问下，全部操作都是在普通用户下吗？我看了你全部$  那应该就是全部普通用户了？

**Comment by opsnull** [comment]
不建议这样做。没有机器资源的话，可以用 vagrant 虚拟出几台机器做实验，参考文档 vagrant/Vagrantfile 。

建议在普通用户下操作，需要 root 权限的操作加了 sudo 前缀。
