### ISSUE TITLE
按照你的教程暗转好kubectl，但是配置了config之后还是提示拒绝，请问下怎么处理，给点思路

### ISSUE THREAD

**Issue by feixia5712** [opsnull/follow-me-install-kubernetes-cluster#158]
_root@ubuntu:~# tar -xzvf kubernetes-client-linux-amd64.tar.gz
kubernetes/
kubernetes/client/
kubernetes/client/bin/
kubernetes/client/bin/kubefed
kubernetes/client/bin/kubectl
root@ubuntu:~# cp kubernetes/client/bin/kube* /root/local/bin/
root@ubuntu:~# cp kubernetes/client/bin/kube* /root/local/bin/
root@ubuntu:~# chmod a+x /root/local/bin/kube*
root@ubuntu:~# ls
kubernetes  kubernetes-client-linux-amd64.tar.gz  local  ssl
root@ubuntu:~#  
root@ubuntu:~# vim admin-csr.json
root@ubuntu:~# vim admin-csr.json
root@ubuntu:~# export MASTER_IP=192.168.100.137
root@ubuntu:~# export KUBE_APISERVER="https://${MASTER_IP}:6443"
root@ubuntu:~# echo $KUBE_APISERVER
https://192.168.100.137:6443
root@ubuntu:~# ls
admin-csr.json  kubernetes  kubernetes-client-linux-amd64.tar.gz  local  ssl
root@ubuntu:~# ls
admin-csr.json  kubernetes  kubernetes-client-linux-amd64.tar.gz  local  ssl
root@ubuntu:~# 
root@ubuntu:~# cfssl gencert -ca=/etc/kubernetes/ssl/ca.pem \
>   -ca-key=/etc/kubernetes/ssl/ca-key.pem \
>   -config=/etc/kubernetes/ssl/ca-config.json \
>   -profile=kubernetes admin-csr.json | cfssljson -bare admin
2017/10/25 11:52:16 [INFO] generate received request
2017/10/25 11:52:16 [INFO] received CSR
2017/10/25 11:52:16 [INFO] generating key: rsa-2048
2017/10/25 11:52:16 [INFO] encoded CSR
2017/10/25 11:52:16 [INFO] signed certificate with serial number 443190835206105245858826310719866098711095852542
2017/10/25 11:52:16 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
root@ubuntu:~# ls admin*
admin.csr  admin-csr.json  admin-key.pem  admin.pem
root@ubuntu:~# mv admin*.pem /etc/kubernetes/ssl/
root@ubuntu:~# mv admin*.pem /etc/kubernetes/ssl/
root@ubuntu:~#  rm admin.csr admin-csr.json
root@ubuntu:~# ls
kubernetes  kubernetes-client-linux-amd64.tar.gz  local  ssl
root@ubuntu:~# kubectl config set-cluster kubernetes \
>   --certificate-authority=/etc/kubernetes/ssl/ca.pem \
>   --embed-certs=true \
>  ^C-server=${KUBE_APISERVER}
root@ubuntu:~# kubectl config set-cluster kubernetes \
> --certificate-authority=/etc/kubernetes/ssl/ca.pem \
> --embed-certs=true \
> --server=${KUBE_APISERVER}
Cluster "kubernetes" set.
root@ubuntu:~# 
root@ubuntu:~# 
root@ubuntu:~# 
root@ubuntu:~# 
root@ubuntu:~# 
root@ubuntu:~# ls
kubernetes  kubernetes-client-linux-amd64.tar.gz  local  ssl
root@ubuntu:~# kubectl config set-credentials admin \
>   --client-certificate=/etc/kubernetes/ssl/admin.pem \
>   --embed-certs=true \
>   --client-key=/etc/kubernetes/ssl/admin-key.pem
User "admin" set.
root@ubuntu:~# kubectl config set-context kubernetes \
>   --cluster=kubernetes \
>   --user=admin
Context "kubernetes" set.
root@ubuntu:~#  kubectl config use-context kubernetes
Switched to context "kubernetes".
root@ubuntu:~# ls -l ~/.kube/config
-rw------- 1 root root 6263 10月 25 13:42 /root/.kube/config
root@ubuntu:~# 
root@ubuntu:~# kubectl get pods
The connection to the server 192.168.100.137:6443 was refused - did you specify the right host or port?

**Comment by feixia5712** [comment]
上面是我的过程，按照你的教程来做的，贴出来不知道为啥划线了，帮忙看看

**Comment by feixia5712** [comment]
已经解决了，是防火墙的问题

**Comment by jiangxinshang** [comment]
我也遇到了这个问题，关闭防火墙和selinux仍然无效

**Comment by feixia5712** [comment]
关闭防火墙没什么用，你执行放行语句试试iptable -P FORWORD   ACCEPT
