### ISSUE TITLE
配置和启动 kube-controller-manager引入参数缺少$符号

### ISSUE THREAD

**Issue by ybgaoa** [opsnull/follow-me-install-kubernetes-cluster#16]
$ cat > kube-controller-manager.service <<EOF
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/root/local/binkube-controller-manager \\
  --address=127.0.0.1 \\
  **--master=http://{MASTER_IP}:8080 \\**
  --allocate-node-cidrs=true \\
  --service-cluster-ip-range=${SERVICE_CIDR} \\
  --cluster-cidr=${CLUSTER_CIDR} \\
  --cluster-name=kubernetes \\
  --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem \\
  --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem \\
  --service-account-private-key-file=/etc/kubernetes/ssl/ca-key.pem \\
  --root-ca-file=/etc/kubernetes/ssl/ca.pem \\
  --leader-elect=true \\
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

加粗地方引入参数时候，缺少$符号

**Comment by opsnull** [comment]
多谢反馈，已修复！
