### ISSUE TITLE
MASTER_IP和NODE_IP为什么是同一个IP地址？

### ISSUE THREAD

**Issue by TerrificMao** [opsnull/follow-me-install-kubernetes-cluster#160]
为什么第7部分 - 部署 Node 节点，其中的MASTER_IP和NODE_IP是同一个IP地址呢？

另外，我已经完成了6部分，即部署成功Master节点（172.16.3.27），再另一台机器（172.16.3.226）打算部署Node节点，执行到最后一步systemctl status kubelet时报错。
[root@ip-172-16-3-226 bin]# systemctl start kubelet（成功）
[root@ip-172-16-3-226 bin]# systemctl status kubelet（失败）
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2017-10-25 16:20:18 UTC; 1s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 29168 ExecStartPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP (code=exited, status=0/SUCCESS)
  Process: 29166 ExecStartPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 29163 ExecStartPost=/sbin/iptables -A INPUT -s 172.16.0.0/12 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 29160 ExecStartPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT (code=exited, status=0/SUCCESS)
  Process: 29159 ExecStart=/root/local/bin/kubelet --address=172.16.3.226 --hostname-override=172.16.3.226 --pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --require-kubeconfig --cert-dir=/etc/kubernetes/ssl --cluster-dns=10.254.0.2 --cluster-domain=cluster.local. --hairpin-mode promiscuous-bridge --allow-privileged=true --serialize-image-pulls=false --logtostderr=true --v=2 (code=exited, status=1/FAILURE)
 Main PID: 29159 (code=exited, status=1/FAILURE)

Oct 25 16:20:18 ip-172-16-3-226.ec2.internal systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Oct 25 16:20:18 ip-172-16-3-226.ec2.internal systemd[1]: Unit kubelet.service entered failed state.
Oct 25 16:20:18 ip-172-16-3-226.ec2.internal systemd[1]: kubelet.service failed.

**Comment by opsnull** [comment]
> 为什么第7部分 - 部署 Node 节点，其中的MASTER_IP和NODE_IP是同一个IP地址呢？

因为只有三台机器，master 和 一台 node 复用。

kubelet 启动失败了，看下它的日志有没有异常：
`$ journalctl -u kube-controller-manager -o export|grep MESSAGE`

**Comment by feixia5712** [comment]
最好别用同一个，真的容易出问题，不好排查
