### ISSUE TITLE
请教，Service网段路由不可达，Pod网段路由可达，这样的设计原因是？外部访问服务一般用哪种方式？

### ISSUE THREAD

**Issue by bl-mds** [opsnull/follow-me-install-kubernetes-cluster#169]

**Comment by opsnull** [comment]
Service IP 只存在于节点的 iptables 中，不是配置在网络接口上的，所以路由不可达，但可以 telnet IP Port 测试。具体可以看看 k8s 官网 network 一节的原理说明。

外部一般是通过 LB、Ingester 等访问服务，LB、Ingester 再通过 Service IP 访问后端 Pod 服务；
