### ISSUE TITLE
配置和启动 kube-scheduler

### ISSUE THREAD

**Issue by ybgaoa** [opsnull/follow-me-install-kubernetes-cluster#17]
$ cat > kube-scheduler.service <<EOF
[Unit]
Description=Kubernetes Scheduler
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/root/local/bin/kube-scheduler \\
  --address=127.0.0.1 \\
  **--master=http://{MASTER_IP}:8080 \\**
  --leader-elect=true \\
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

缺少$符号

**Comment by opsnull** [comment]
多谢反馈，已修复！
