### ISSUE TITLE
influxdb-deployment.yaml 文件中存储卷写法有错

### ISSUE THREAD

**Issue by JaeGerW2016** [opsnull/follow-me-install-kubernetes-cluster#170]
```        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - mountPath: /etc/
          name: influxdb-config
```

报错:error: error validating "influxdb-deployment.yaml": error validating data: [field spec.template.spec.containers[0].volumeMounts[1].mountPath for v1.VolumeMount is required, found invalid field moutPath for v1.VolumeMount]; if you choose to ignore these errors, turn validation off with --validate=false

修改为:
```  
      - name: influxdb-storage
          mountPath: /data
      - name: influxdb-config
          mountPath: /etc/
```

**Comment by opsnull** [comment]
没有错，你写的有问题。

**Comment by JaeGerW2016** [comment]
我这边直接用你的yaml部署是有报错的，我查了相关的deployment关于mountPath的写法，感觉你的是有问题的，应该是name写在前面而且`-`是得加在name之前的
