### ISSUE TITLE
etcd 配置不够安全！

### ISSUE THREAD

**Issue by JinsYin** [opsnull/follow-me-install-kubernetes-cluster#171]
@opsnull 
[创建 etcd 的 systemd unit 文件](https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/03-%E9%83%A8%E7%BD%B2%E9%AB%98%E5%8F%AF%E7%94%A8Etcd%E9%9B%86%E7%BE%A4.md#创建-etcd-的-systemd-unit-文件) 部分建议增加两个参数：`--client-cert-auth=true`、`--peer-client-cert-auth=true`，否则客户端不需要证书也能访问 etcd。

**Comment by opsnull** [comment]
多谢反馈！最近将发布的 1.8 版本文档会加上这两个参数。
