### ISSUE TITLE
用kubernetes1.8部署node 时出现权限验证的问题

### ISSUE THREAD

**Issue by steinliber** [opsnull/follow-me-install-kubernetes-cluster#172]
使用教程部署kubernetes1.8 node 时出现 kubelet 验证无法通过的问题,如下图s所示，node没有添加成功
![image](https://user-images.githubusercontent.com/13215800/32939459-27ac7116-cb45-11e7-8c85-a4f86f3c39cc.png)
查看kublet 的错误日志如下
![image](https://user-images.githubusercontent.com/13215800/32939489-47114144-cb45-11e7-8c47-a1ed5bd82166.png)
查看 kube-pai 的错误日志如下
![image](https://user-images.githubusercontent.com/13215800/32939522-5f9ae49a-cb45-11e7-9085-e2210c50fe98.png)
看kubenetes的更新文档好像是说 system:nodes 已经默认没有权限了，这样的话要怎么做

**Comment by opsnull** [comment]
@steinliber 
#142
