### ISSUE TITLE
部署完etcd集群 ，启动服务出现错误

### ISSUE THREAD

**Issue by jiangxinshang** [opsnull/follow-me-install-kubernetes-cluster#176]
`11月 22 14:48:32 manager etcd[7090]: rejected connection from "10.20.22.2:55116" (remote error: tls: bad certificate)`
`11月 22 14:48:32 manager etcd[7090]: rejected connection from "10.20.22.3:53708" (remote error: tls: bad certificate)`
`11月 22 14:48:32 manager etcd[7090]: rejected connection from "10.20.22.3:53710" (remote error: tls: bad certificate)`
`11月 22 14:48:32 manager etcd[7090]: health check for peer 5ab0ee54e79aa1a9 could not connect: x509: certificate is valid for 127.0.0.1, not 10.20.22.2`
`11月 22 14:48:32 manager etcd[7090]: rejected connection from "10.20.22.2:55120" (remote error: tls: bad certificate)`
`11月 22 14:48:32 manager etcd[7090]: health check for peer f6a28e81a2d95a1e could not connect: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`
`11月 22 14:48:32 manager etcd[7090]: rejected connection from "10.20.22.2:55124" (remote error: tls: bad certificate)`
11月 22 14:48:33 manager systemd[1]: etcd.service start operation timed out. Terminating.``

**Comment by opsnull** [comment]
证书有问题，请严格按照文档中的步骤和配置生成证书。注意证书 hosts 字段的 IP 列表为当前运行 etcd 的机器 IP。

**Comment by jiangxinshang** [comment]
jason文件中的内容，当前机器的IP是使用${NODE_IP},还是使用10.20.22.2，这两种方式有区别吗？

**Comment by opsnull** [comment]
1. ${NODE_IP} 是在文档开头定义的环境变量，在创建 json 文件时会自动被替换为实际的 IP(使用 Bash 的 here document 语法)；
2. 是的。秘钥和证书是各机器专用的，需要单独生成后，再起 etcd 服务。

**Comment by xgfone** [comment]
@opsnull 我在文档中似乎没有找到 `重复以上步骤` 这几个字，另外，在 `04.部署etcd集群` 章节中，生成的 etcd 秘钥和证书被分发到各个节点，这是不是说，所有机器上的 etcd 秘钥和证书都是一样的？

如果说 `秘钥和证书是各机器专用的，需要单独生成`，那文档中没有看到相关的说明或步骤？

另外，既然 etcd 的秘钥和证书是各节点专用的，那其它服务，如 apiserver、kubelet，是不是也是各节点专用的？

这个 issue 是 2017 年提的，不知道现在是如何？

这几点没能理解清楚，一直报 etcd 证书错误。求指正。

**Comment by abhty822** [comment]
同问 楼上的问题 希望有人能回答

**Comment by JohnnyHL** [comment]
ETCD集群启动具体是什么问题？截图看一下呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"leiyz"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月22日(星期天) 下午3:19
收件人:&nbsp;"opsnull/follow-me-install-kubernetes-cluster"<follow-me-install-kubernetes-cluster@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [opsnull/follow-me-install-kubernetes-cluster] 部署完etcd集群 ，启动服务出现错误 (#176)




同问 楼上的问题 希望有人能回答
