### ISSUE TITLE
master docker flanneld

### ISSUE THREAD

**Issue by vsxen** [opsnull/follow-me-install-kubernetes-cluster#178]
master上面没有docker，但是在`安装和配置 flannels`这步中

flannel的service文件有`/root/local/bin/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker`?这是？

还有flannel的证书是分发还是各个节点自己生成？

```
/root/local/bin/flanneld \
  -etcd-cafile=/etc/kubernetes/ssl/ca.pem \
  -etcd-certfile=/etc/flanneld/ssl/flanneld.pem \
  -etcd-keyfile=/etc/flanneld/ssl/flanneld-key.pem \
  -etcd-endpoints=https://10.64.3.7:2379,https://10.64.3.8:2379,https://10.66.3.86:2379 \
  -etcd-prefix=/kubernetes/network
```
这里的etcd keyfile是不是错了？

**Comment by opsnull** [comment]
> master上面没有docker，但是在安装和配置 flannels这步中
> 
> flannel的service文件有/root/local/bin/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker?这是？

没有 docker 也可以部署 flanneld，目的是将 master 与 pod node 通过 pod 网段互通。

> 还有flannel的证书是分发还是各个节点自己生成？
各个节点自己生成。文档中明确说明了。

> 这里的etcd keyfile是不是错了？
No。

**Comment by vsxen** [comment]
Thank you
找到了一张关于flannel的图
在master上 是通过flannel网卡和node通信的
```
flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN
    link/ether 12:24:40:48:1a:bf brd ff:ff:ff:ff:ff:ff
    inet 172.30.32.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::1024:40ff:fe48:1abf/64 scope link
       valid_lft forever preferred_lft forever
```
![a7dcaa3ed376490a9b44ba51222233af_th](https://user-images.githubusercontent.com/8838032/33257766-50bc4d42-d392-11e7-9912-2d6af452a676.jpg)

PS 如果遇到这个错误
> Failed  to find any valid interface to use: failed to get default interface: Unable to find default route

需要指定网卡（need to use `--iface=eth0`）
