### ISSUE TITLE
部署master节点，启动kube-apiserver服务出错

### ISSUE THREAD

**Issue by jiangxinshang** [opsnull/follow-me-install-kubernetes-cluster#179]
提示内容：
`root@manager system]# systemctl status kube-apiserver.service
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since 一 2017-11-27 10:32:30 CST; 3s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 2939 ExecStart=/root/local/bin/kube-apiserver # --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota --admission-control=ServiceAccount --advertise-address=10.20.42.17 --bind-address=10.20.42.17 --insecure-bind-address=10.20.42.17 --authorization-mode=RBAC --runtime-config=rbac.authorization.k8s.io/v1alpha1 --kubelet-https=true --experimental-bootstrap-token-auth --token-auth-file=/etc/kubernetes/token.csv --service-cluster-ip-range=10.254.0.0/16 --service-node-port-range=8400-9000 --tls-cert-file=/etc/kubernetes/ssl/kubernetes.pem --tls-private-key-file=/etc/kubernetes/ssl/kubernetes-key.pem --client-ca-file=/etc/kubernetes/ssl/ca.pem --service-account-key-file=/etc/kubernetes/ssl/ca-key.pem --etcd-cafile=/etc/kubernetes/ssl/ca.pem --etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem --etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem --etcd-servers=https://10.20.42.17:2379,https://10.20.42.22:2379,https://10.20.42.172:2379 --enable-swagger-ui=true --allow-privileged=true --apiserver-count=3 --audit-log-maxage=30 --audit-log-maxbackup=3 --audit-log-maxsize=100 --audit-log-path=/var/lib/audit.log --event-ttl=1h --v=2 (code=exited, status=2)
 Main PID: 2939 (code=exited, status=2)

11月 27 10:32:30 manager kube-apiserver[2939]: --tls-ca-file string                                      If set, this certificate authority will used for secure ac...cert-file.
11月 27 10:32:30 manager kube-apiserver[2939]: --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if...
11月 27 10:32:30 manager kube-apiserver[2939]: --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
11月 27 10:32:30 manager kube-apiserver[2939]: --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, opt...he names o
11月 27 10:32:30 manager kube-apiserver[2939]: --token-auth-file string                                  If set, the file that will be used to secure the secure po...ntication.
11月 27 10:32:30 manager kube-apiserver[2939]: -v, --v Level                                                 log level for V logs
11月 27 10:32:30 manager kube-apiserver[2939]: --version version[=true]                                  Print version information and quit
11月 27 10:32:30 manager kube-apiserver[2939]: --vmodule moduleSpec                                      comma-separated list of pattern=N settings for file-filtered logging
11月 27 10:32:30 manager kube-apiserver[2939]: --watch-cache                                             Enable watch caching in the apiserver (default true)
11月 27 10:32:30 manager kube-apiserver[2939]: --watch-cache-sizes stringSlice                           List of watch cache sizes for every resource (pods, nodes,...s enabled.
Hint: Some lines were ellipsized, use -l to show in full.
`

服务启动不了，导致6443端口不开，会导致无法执行以下命令
`[root@manager system]#  kubectl get pods
The connection to the server 10.20.42.17:6443 was refused - did you specify the right host or port?`

**Comment by opsnull** [comment]
> (code=exited, status=2)
> Main PID: 2939 (code=exited, status=2)

手动执行 systemd unit 文件中的命令行，看看具体报错原因。

**Comment by jiangxinshang** [comment]
使用ExecStart中的cmd命令，去掉参数--experimental-bootstrap-token-auth 就可以执行了，不明白为什么会这样

**Comment by opsnull** [comment]
版本兼容性问题，文档针对的是 1.6.2 版本，最新的 1.8 版本，该参数为 --enable-bootstrap-token-auth。

**Comment by cmadah** [comment]
我有同样问题，手动执行后，报错无法识别
I0314 11:17:31.915504   28630 services.go:35] Network range for service cluster IPs is unspecified. Defaulting to 10.0.0.0/24.
[--etcd-servers must be specified, no --service-cluster-ip-range specified]

手动添加--etcd-servers和--service-cluster-ip-range这两个参数也无法识别。

**Comment by lijunyong** [comment]
@cmadah 同样的问题，你好好检测一下systemd是否有换行乱码

**Comment by bobo325** [comment]
同样的问题，手动敲了一遍，还是同样的问题

**Comment by smxyms** [comment]
> 我同样有，手动执行后，报错无法识别 I0314 11:17:31.915504 28630 services.go:35] 未指定服务集群 IP 的网络范围。默认为 10.0.0.0/24。 [必须指定--etcd-servers，不指定--service-cluster-ip-range]
> 
> 手动添加--etcd-servers和--service-cluster-ip-range这两个参数也无法识别。
--etcd-servers这个怎么解决了？
