### ISSUE TITLE
老大有没有计划写个k8s1.8版本的，1.6怎么直接升级到1.8啊，请指点下，现在k8s的1.8版本貌似官方定位为稳定版本了

### ISSUE THREAD

**Issue by feixia5712** [opsnull/follow-me-install-kubernetes-cluster#182]
老大有没有计划写个k8s1.8版本的，1.6怎么直接升级到1.8啊，请指点下，现在k8s的1.8版本貌似官方定位为稳定版本了

**Comment by opsnull** [comment]
已经在写了，估计本周末可以 merge。

**Comment by feixia5712** [comment]
期待大神新作

**Comment by eehuangyanwen** [comment]
@opsnull 有没有高可用的方案？毕竟这块还是比较关注的

**Comment by gjmzj** [comment]
@eehuangyanwen 
推荐下本人的项目https://github.com/gjmzj/kubeasz 已经集成了高可用方案和calico网络方案，其他部分与opsnull大神的类似，同样的二进制安装，交流学习

**Comment by gjmzj** [comment]
@opsnull 欢迎您来交流，希望大神给提意见建议 https://github.com/gjmzj/kubeasz
另外，我项目里面也专门链接了您的项目地址

**Comment by feixia5712** [comment]
@gjmzj有写k8s1.6与1.8的却别大吗？你没用flannel？

**Comment by gjmzj** [comment]
@feixia5712 k8s1.6与1.8区别不大，少许调整一些参数，网络选了calico，用flannel的话，使用opsnull这个教程即可

**Comment by imbadog** [comment]
@opsnull  作者1.8版的具体什么时候推呀... 等了一周了.  这周能么

**Comment by aaa7946132** [comment]
@opsnull  这周能推吗

**Comment by opsnull** [comment]
已经发布了 v1.10.4 版本。
