### ISSUE TITLE
kube-apiserver 证书中的 hosts 受限问题

### ISSUE THREAD

**Issue by JinsYin** [opsnull/follow-me-install-kubernetes-cluster#185]
我简单的把证书分为三类：
  * server 证书：server auth；
  * client 证书：client auth；
  * peer 证书：server auth + client auth。

经过我的实践和理解：client 证书可以不用指定 `hosts` 字段，server 证书和 peer 证书必须要指定 `hosts` 字段，否则客户端访问时会提示错误：
```
Unable to connect to the server: x509: cannot validate certificate for 192.168.1.x because it doesn't contain any IP SANs
```

但是当我在做 HA master （我使用 Keepalived 新增了一个 VIP，并且使用 HAProxy 代理 https 的 kube-apiserver）时，就会存在一个问题：由于 VIP 并不在 kube-apiserver 的 `hosts` 中，导致所有客户端都没有办法通过 VIP 来访问 kube-apiserver （提示 VIP 不在 SANS 中）。

解决办法是我事先将 VIP 加入到 kube-apiserver 的 hosts 中，但是对于 VIP 不固定，或者需要更改，亦或者还要增加 VIP 时（比如原先设定了一个 VIP 用于内网访问，现在要增加一个 VIP 供外网访问），就无效了，除非一个个停掉 kube-apiserver 并且重新签发 kube-apiserver 证书。

我想请问一下，针对这种情况有没有更好的解决办法？

**Comment by opsnull** [comment]
对，除了 IP 外，还可以使用域名的方式。

**Comment by JinsYin** [comment]
@gjmzj @opsnull Thx.

**Comment by slayercao** [comment]
我遇到和你相似的问题，也是kubectl访问apiserver的时候报错：
Unable to connect to the server: x509: certificate is valid for 10.0.0.1, 127.0.0.1, 100.101.238.140, 100.101.239.25, 100.101.239.2, not 10.90.187.250
将VIP 10.90.187.250添加到server的证书中之后，替换证书并重启所有apiserver进程、甚至master节点，仍然会出现相同的报错信息，都是提示证书对VIP无效，不晓得该怎么搞了。
我用的keepalived+haproxy。
