### ISSUE TITLE
运行kubelet之后，master上approve了csr，但是get nodes 还是No resources found.

### ISSUE THREAD

**Issue by maotongxue** [opsnull/follow-me-install-kubernetes-cluster#192]
node上也没有生成kubelet.kubeconfig，生成了kubelet-client.key，kubelet.crt，kubelet.key，dan也没生成kubelet-client.crt。kubelet正常运行，日志上报：
Dec 28 14:21:56 node1 kubelet[3208]: I1228 14:21:56.637191    3208 feature_gate.go:156] feature gates: map[]
Dec 28 14:21:56 node1 kubelet[3208]: I1228 14:21:56.637701    3208 controller.go:114] kubelet config controller: starting controller
Dec 28 14:21:56 node1 kubelet[3208]: I1228 14:21:56.637889    3208 controller.go:118] kubelet config controller: validating combination of defau
Dec 28 14:21:56 node1 kubelet[3208]: I1228 14:21:56.642250    3208 mount_linux.go:168] Detected OS with systemd
Dec 28 14:21:56 node1 kubelet[3208]: I1228 14:21:56.642472    3208 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Dec 28 14:21:56 node1 kubelet[3208]: I1228 14:21:56.642685    3208 client.go:95] Start docker client with request timeout=2m0s
Dec 28 14:21:56 node1 kubelet[3208]: W1228 14:21:56.645757    3208 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
Dec 28 14:21:56 node1 kubelet[3208]: I1228 14:21:56.654323    3208 feature_gate.go:156] feature gates: map[]
Dec 28 14:21:56 node1 kubelet[3208]: W1228 14:21:56.654861    3208 server.go:289] --cloud-provider=auto-detect is deprecated. The desired cloud 
Dec 28 14:21:56 node1 kubelet[3208]: I1228 14:21:56.655308    3208 bootstrap.go:57] Using bootstrap kubeconfig to generate TLS client cert, key 

请问是什么原因造成的？docker运行正常，那个镜像也pull了。

**Comment by hoperuin** [comment]
1、关闭swap分区
2、"mode": "Webhook" 注意w大写
3、"hairpinMode": "promiscuous-veth"报错，修改为"promiscuous-bridge"
检查下这几个看看。

**Comment by maotongxue** [comment]
之后发现问题了，忘记更新了，现在说一下，还是我的问题，太粗心，自己把配置文件都保存在onenode上，但是第二次装的时候直接复制过来，出现了上面的问题，原来复制过来的配置文件里出现了隐藏字符，主要是空格，复制粘贴后，好像是编码不对了，通过cat -A file.conf，看到的，在此也提醒各位注意此类问题
