### ISSUE TITLE
error with opening dashboard

### ISSUE THREAD

**Issue by lluxury** [opsnull/follow-me-install-kubernetes-cluster#197]
Error: 'dial tcp 172.17.0.6:9090: getsockopt: no route to host'
Trying to reach: 'http://172.17.0.6:9090/'

both method return same error

**Comment by lluxury** [comment]
in dashboard folder 
run kubectl delete -f .
kubectl create -f  .
view http://10.64.3.7:8086/ui
new error:
Error: 'dial tcp 172.17.0.6:9090: getsockopt: connection refused'
Trying to reach: 'http://172.17.0.6:9090/'

**Comment by opsnull** [comment]
很久没有更新了，如果还有问题再打开。
