### ISSUE TITLE
etcd 集群配置报错

### ISSUE THREAD

**Issue by kaleLiu** [opsnull/follow-me-install-kubernetes-cluster#199]
<img width="1436" alt="2018-02-07 4 38 33" src="https://user-images.githubusercontent.com/13827926/35906462-92142dac-0c25-11e8-8ad5-1fdf099b9c8f.png">

**Comment by opsnull** [comment]
TLS 证书的问题，注意：
1. 其中的 IP 为所在 etcd 节点的忽略 IP；
2. 不能过期；

**Comment by opsnull** [comment]
@kaleLiu 还有问题么？
