### ISSUE TITLE
您好！咨询下master HA模式下证书的问题

### ISSUE THREAD

**Issue by minminmsn** [opsnull/follow-me-install-kubernetes-cluster#2]
kube-dns等组件需要kube-controll-manager启动时指定证书，如果3个kube-controll-manager，每个的证书怎样指定啊？谢谢。

**Comment by minminmsn** [comment]
补充下，就是说3个kube-controller-manager 
      --cluster-signing-cert-file         --cluster-signing-key-file  都设置为一样的吗？

**Comment by opsnull** [comment]
是的，3个 kube-controller-manager 需要使用相同的证书。

**Comment by minminmsn** [comment]
您好!我kube-apiserver和kube-controller-manager都设置了证书，如下：

[root@k8s-master ca]# cat /etc/kubernetes/controller-manager
KUBE_CONTROLLER_MANAGER_ARGS="--cluster-signing-cert-file=/etc/kubernetes/ca/ca.pem --cluster-signing-key-file=/etc/kubernetes/ca/ca-key.pem  --service-account-private-key-file=/etc/kubernetes/ca/ca-key.pem --root-ca-file=/etc/kubernetes/ca/ca.pem --leader-elect=true "

[root@k8s-master ca]# cat /etc/kubernetes/apiserver
KUBE_API_ARGS="--tls-cert-file=/etc/kubernetes/ca/kubernetes.pem --tls-private-key-file=/etc/kubernetes/ca/kubernetes-key.pem --client-ca-file=/etc/kubernetes/ca/ca.pem --service-account-key-file=/etc/kubernetes/ca/ca-key.pem"


但是我创建时kube-dns任然报错
[root@k8s-master kube-dns]# kubectl logs kube-dns-368911643-5b4rs -c kubedns -n kube-system |less
 1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Ser
vice: the server has asked for the client to provide credentials (get services)

不知道原因在哪儿，麻烦指导下，谢谢！

**Comment by opsnull** [comment]
你这是缺少 RBAC 授权的 ServiceAccount 。请参考最新的文档。

**Comment by minminmsn** [comment]
额，我说下我的环境我的环境是k8s1.5.4版本，这些组件之前都建好了就是没有设置认证，之前kube-dns这边kube-apiserver参数为空，kube-controller-manager里面是这样设置的kube-dns是可以正常运行的，#KUBE_CONTROLLER_MANAGER_ARGS="--service-account-private-key-file=/var/run/kubernetes/apiserver.key --root-ca-file=/var/run/kubernetes/apiserver.crt --leader-elect=true"     要是我这个在1.5.4版本上修改，不知道从哪儿着手啊？

**Comment by opsnull** [comment]
1.5.4 开启了 RBAC 了么？你的报错原因是权限不足。

**Comment by minminmsn** [comment]
不清楚怎样查开启了RBAC吗？权限不足好郁闷啊。
