### ISSUE TITLE
无法成功部署dns测试

### ISSUE THREAD

**Issue by it2911** [opsnull/follow-me-install-kubernetes-cluster#20]
我完全按照您的说明文档进行部署，但是到测试dns的时候，出现问题。
root@nginx:/# ping my-nginx
ping: unknown host
root@nginx:/# ping kubernetes
^C
root@nginx:/# ping kube-dns.kube-system.svc.cluster.local
ping: unknown host

请问我如何排查这个问题？

**Comment by opsnull** [comment]
1. 看 dns pod 是否处于 Running 状态，重启次数是否一直在增加。
kubectl get pods  -n kube-system |grep dns

2. 看 dns pod 的日志情况，
kubectl describe pod kube-dns-699984412-lz29f -n kube-system

**Comment by it2911** [comment]
>看 dns pod 是否处于 Running 状态，重启次数是否一直在增加。
>kubectl get pods -n kube-system |grep dns
1.dns应该是在启动状态，而且没有看到重启的情况。

>看 dns pod 的日志情况
我用您的命令，发现确实有些奇怪的问题，就是liveness和readiness里面的ip地址有问题。
Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3

另外一点就是我没有做environment.sh，是这个问题导致了我的dns服务不可用么？

3.我用kubectl -n kube-system logs kube-dns-3392212829-93v3t -c kubedns 查看
应用确实都加入到dns里面了
![_20170417151047](https://cloud.githubusercontent.com/assets/2803470/25082057/cc7bd06e-2380-11e7-9fcd-613b300edb2f.png)

**Comment by opsnull** [comment]
>> 另外一点就是我没有做environment.sh，是这个问题导致了我的dns服务不可用么？
不会的。

从日志看，kubedns 启动和功能正常：
1. 你的 kubelet 指定了 dns 相关的两个参数了么？ 
2. kubelet 指定的 dns service ip 和 kubectl get svc -n kube-system 一致么？
3. 贴下 你 nginx pod 的 /etc/resolv.conf 文件看看。

**Comment by it2911** [comment]
我突然发现了一个问题，
SERVICE_CIDR="10.254.0.0/16" 这个是跟您本地环境相关的对吧，我在启动kube-apiservice的时候，也写的是这个，我本地的ip地址段是192.168.0.22，192.168.0.24，192.168.0.25，那么我应该改成 192.168.0.0/24 才对，您看是这个样子么。

**Comment by it2911** [comment]
>你的 kubelet 指定了 dns 相关的两个参数了么？

指定行代码
 --cluster_dns=10.254.0.2 \
  --cluster_domain=cluster.local. \

>kubelet 指定的 dns service ip 和 kubectl get svc -n kube-system 一致么？

kubectl get svc -n kube-system的输出结果
 NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
kube-dns               10.254.0.2       <none>        53/UDP,53/TCP   4h
kubernetes-dashboard   10.254.232.155   <nodes>       80:8775/TCP     4h

>贴下 你 nginx pod 的 /etc/resolv.conf 文件看看。

root@nginx:/# cat /etc/resolv.conf
nameserver 10.254.0.2
search default.svc.cluster.local. svc.cluster.local. cluster.local. airport
options ndots:5

**Comment by opsnull** [comment]
看起来都OK。

**Comment by it2911** [comment]
我现在比较怀疑是我的flannel的问题
如果是在同一个物理节点上，那么ping ip地址是可以成功的，但是如果跨物理节点。ping起来是错误的。


![image](https://cloud.githubusercontent.com/assets/2803470/25084161/a934d242-238d-11e7-8583-a1a09481c494.png)

**Comment by it2911** [comment]
跨物理节点如果出现问题，请问会不会跟SERVICE_CIDR的相关部署也有关系？

kube-apiserver/kube-proxy/kube-contorller-manger

**Comment by it2911** [comment]
# 服务网段 (Service CIDR），部署前必须路由不可达
SERVICE_CIDR="10.254.0.0/16"

请问不可达的标准是什么？

**Comment by it2911** [comment]
对了，我没有开启防火墙。

**Comment by ipchy** [comment]
@it2911 我也遇到和你一样的问题，但是我安装的方式和第一次安装一样的，我就搞不懂了，我是第一次安装完成了，然后想温习一下，然后重新来过，结果走到dns也是无法解析，不过我第一次安装的时候文档是以前的，当时也做了笔记，现在按照之前的方法安装还是新方法，都是走到dns出错，无法解析

**Comment by it2911** [comment]
你开启防火墙了么？

**Comment by ipchy** [comment]
@it2911 防火墙和SElinux是第一步就关掉的啊，这个会有问题么

**Comment by ipchy** [comment]
@it2911 我刚刚又通过kubeadm安装了一遍也是走到dns这一步骤，发现解析不了，结果我现在一个测试环境都没了

**Comment by it2911** [comment]
我终于弄好了，你要打开iptables，记得重启docker就好了

**Comment by ipchy** [comment]
@it2911 你是什么版本，我这里怎么没有iptables呢

**Comment by ipchy** [comment]
@it2911 centos默认的不是firewalld吗，我把这个关掉了，是不是说我还需要安装一个net-tools然后开启iptables？

**Comment by it2911** [comment]
是的，你需要安装iptables和iptables-service，然后按照作者的步骤修改iptable协议，我微信:it2911

**Comment by jianglin1008** [comment]
你们都没发现domain后面有个小数点么
