### ISSUE TITLE
部署flanneld 时的iface是/etc/network/interfaces里代表10.64.3.7的网口名么？

### ISSUE THREAD

**Issue by lcgogo** [opsnull/follow-me-install-kubernetes-cluster#204]
flanneld 使用系统缺省路由所在的接口和其它节点通信，对于有多个网络接口的机器（如，内网和公网），可以用 --iface 选项值指定通信接口(上面的 systemd unit 文件没指定这个选项)，如本着 Vagrant + Virtualbox，就要指定--iface=enp0s8

这里-iface=enp0s8我理解的是/etc/network/interfaces里代表10.64.3.7的网口名。
（PS：--iface应该是-iface才对。）
但是我的vagrant默认设置的是eth1，是不是要换成-iface=eth1?但是我换了并且iptable都accept，ping网关还是ping不通。

```
root@kube-node1:/tmp# cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto enp0s3
iface enp0s3 inet dhcp
pre-up sleep 2
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 10.64.3.7
      netmask 255.255.255.0
#VAGRANT-END

root@kube-node1:/tmp# /root/local/bin/etcdctl   --endpoints=${ETCD_ENDPOINTS}   --ca-file=/etc/kubernetes/ssl/ca.pem   --cert-file=/etc/flanneld/ssl/flanneld.pem   --key-file=/etc/flanneld/ssl/flanneld-key.pem   get ${FLANNEL_ETCD_PREFIX}/subnets/172.30.17.0-24
2018-02-28 08:17:53.988461 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
{"PublicIP":"10.64.3.7","BackendType":"vxlan","BackendData":{"VtepMAC":"9e:b0:26:b3:4e:06"}}

root@kube-node3:/tmp# /root/local/bin/etcdctl   --endpoints=${ETCD_ENDPOINTS}   --ca-file=/etc/kubernetes/ssl/ca.pem   --cert-file=/etc/flanneld/ssl/flanneld.pem   --key-file=/etc/flanneld/ssl/flanneld-key.pem   ls ${FLANNEL_ETCD_PREFIX}/subnets
2018-02-28 07:21:12.176279 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
/kubernetes/network/subnets/172.30.99.0-24
/kubernetes/network/subnets/172.30.17.0-24
/kubernetes/network/subnets/172.30.18.0-24

root@kube-node3:/tmp# ping 172.30.17.1
PING 172.30.17.1 (172.30.17.1) 56(84) bytes of data.
^C
--- 172.30.17.1 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1001ms
```

**Comment by opsnull** [comment]
可以用 ip route show 命令确认下缺省路由是否位于 eth1 接口上。如果是的话，就不需要设置 -iface=eth1，否则需要设置。

ping  flanneld 网关不通的原因很多：
1. 确认 kube-node1、kube-node3 之间是否互通( ping 对端的 10.64.3.X IP ）？
2. 用 ip route show 确认 flanneld 是否创建了到 172.30.xx.0 的路由规则？
3. 参看 各 node 的 iptables 规则是否有 drop 的情况。

**Comment by lcgogo** [comment]
1. 可以ping通
root@kube-node1:/vagrant# ping 10.64.3.8
PING 10.64.3.8 (10.64.3.8) 56(84) bytes of data.
64 bytes from 10.64.3.8: icmp_seq=1 ttl=64 time=1.03 ms
64 bytes from 10.64.3.8: icmp_seq=2 ttl=64 time=0.477 ms
^C
--- 10.64.3.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.477/0.758/1.039/0.281 ms

2. 有一个规则，但是不是172.30.xx.0的，是172.30.0.0的
root@kube-node1:/vagrant# ip route show
default via 10.0.2.2 dev eth0
10.0.2.0/24 dev eth0  proto kernel  scope link  src 10.0.2.15
10.64.3.0/24 dev eth1  proto kernel  scope link  src 10.64.3.7
**172.30.0.0/16 dev flannel.1**

3. iptables如下，在安装docker之前的，vagrant里应该是空的。
root@kube-node1:/vagrant# iptables -L -n -v
Chain INPUT (policy ACCEPT 83624 packets, 7425K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 88729 packets, 7599K bytes)
 pkts bytes target     prot opt in     out     source               destination
root@kube-node1:/vagrant# /root/local/bin/etcdctl \
>   --endpoints=${ETCD_ENDPOINTS} \
>   --ca-file=/etc/kubernetes/ssl/ca.pem \
>   --cert-file=/etc/flanneld/ssl/flanneld.pem \
>   --key-file=/etc/flanneld/ssl/flanneld-key.pem \
>   get ${FLANNEL_ETCD_PREFIX}/subnets/172.30.63.0-24
2018-03-19 06:38:23.517830 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
{"PublicIP":"10.64.3.7","BackendType":"vxlan","BackendData":{"VtepMAC":"ea:8c:69:4c:53:4b"}}
root@kube-node1:/vagrant# ifconfig flannel.1
flannel.1 Link encap:Ethernet  HWaddr ea:8c:69:4c:53:4b
          inet addr:172.30.63.0  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::e88c:69ff:fe4c:534b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:14 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

4. 但是ping网关还是不通。
root@kube-node1:/vagrant# ping 172.30.63.1
PING 172.30.63.1 (172.30.63.1) 56(84) bytes of data.
From 172.30.63.0 icmp_seq=1 Destination Host Unreachable
From 172.30.63.0 icmp_seq=2 Destination Host Unreachable
From 172.30.63.0 icmp_seq=3 Destination Host Unreachable
From 172.30.63.0 icmp_seq=4 Destination Host Unreachable
From 172.30.63.0 icmp_seq=5 Destination Host Unreachable
From 172.30.63.0 icmp_seq=6 Destination Host Unreachable
^C
--- 172.30.63.1 ping statistics ---
9 packets transmitted, 0 received, +6 errors, 100% packet loss, time 8020ms
pipe 7
root@kube-node1:/vagrant#

5. 求教了。

**Comment by lcgogo** [comment]
我大概知道是什么原因了，因为flannel 0.7.0之后为了防止网络风暴的隐患，把flannel网卡的掩码设成32位了。所以只有这一个172.30.81.0 IP暴露出来。
[root@kube-node2 vagrant]# ip addr show flannel.1
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN
    link/ether 82:a3:d4:3d:eb:f0 brd ff:ff:ff:ff:ff:ff
    inet **172.30.81.0/32** scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::80a3:d4ff:fe3d:ebf0/64 scope link
       valid_lft forever preferred_lft forever
所以flannel搭好后，互相ping的检测应该只互相ping这个端口就行。

[root@kube-node1 dashboard]# /root/local/bin/etcdctl   --endpoints=${ETCD_ENDPOINTS}   --ca-file=/etc/kubernetes/ssl/ca.pem   --cert-file=/etc/flanneld/ssl/flanneld.pem   --key-file=/etc/flanneld/ssl/flanneld-key.pem   ls ${FLANNEL_ETCD_PREFIX}/subnets
2018-04-19 01:37:28.202604 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
/kubernetes/network/subnets/**172.30.81.0-24**
/kubernetes/network/subnets/**172.30.51.0-24**
[root@kube-node1 dashboard]# ping 172.30.81.0
PING 172.30.81.0 (172.30.81.0) 56(84) bytes of data.
64 bytes from 172.30.81.0: icmp_seq=1 ttl=64 time=0.694 ms
64 bytes from 172.30.81.0: icmp_seq=2 ttl=64 time=0.763 ms
^C
--- 172.30.81.0 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.694/0.728/0.763/0.043 ms
[root@kube-node1 dashboard]# ping 172.30.51.0
PING 172.30.51.0 (172.30.51.0) 56(84) bytes of data.
64 bytes from 172.30.51.0: icmp_seq=1 ttl=64 time=0.081 ms
64 bytes from 172.30.51.0: icmp_seq=2 ttl=64 time=0.070 ms
64 bytes from 172.30.51.0: icmp_seq=3 ttl=64 time=0.082 ms
^C
--- 172.30.51.0 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.070/0.077/0.082/0.011 ms
[root@kube-node1 dashboard]#
