### ISSUE TITLE
创建的pod状态是ContainerCreating

### ISSUE THREAD

**Issue by wanghuan578** [opsnull/follow-me-install-kubernetes-cluster#208]
创建的pod状态是ContainerCreating，kubectl describe 命令查看，提示unable to pull sandbox image \"registry.access.redhat.com/rhel7/pod-infrastr，请问楼主，这个是什么问题造成的？

**Comment by opsnull** [comment]
看起来是你的网络问题，你可以用 docker pull registry.access.redhat.com/rhel7/pod-infrastr 命令手动 pull 试试。
