### ISSUE TITLE
Dashboard无法显示heapster监控信息，

### ISSUE THREAD

**Issue by liusl12** [opsnull/follow-me-install-kubernetes-cluster#209]
heapster一直报这个错误，该怎么办呢？
/heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb:8086
I0315 06:28:17.581211       1 heapster.go:72] Heapster version v1.3.0-beta.1
I0315 06:28:17.581579       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default" and version v1
I0315 06:28:17.581609       1 configs.go:62] Using kubelet port 10255
E0315 06:28:27.587321       1 kubelet.go:336] Failed to load nodes: Get https://kubernetes.default/api/v1/nodes: dial tcp: lookup kubernetes.default on 10.254.0.2:53: read udp 172.17.0.6:38161->10.254.0.2:53: read: connection refused
E0315 06:28:47.592711       1 influxdb.go:238] issues while creating an InfluxDB sink: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb on 10.254.0.2:53: read udp 172.17.0.6:45906->10.254.0.2:53: read: connection refused, will retry on use
I0315 06:28:47.592738       1 influxdb.go:252] created influxdb sink with options: host:monitoring-influxdb:8086 user:root db:k8s
I0315 06:28:47.592763       1 heapster.go:193] Starting with InfluxDB Sink
I0315 06:28:47.592770       1 heapster.go:193] Starting with Metric Sink
E0315 06:28:47.592819       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: Get https://kubernetes.default/api/v1/nodes?resourceVersion=0: dial tcp: lookup kubernetes.default on 10.254.0.2:53: read udp 172.17.0.6:33032->10.254.0.2:53: read: connection refused
I0315 06:28:47.606650       1 heapster.go:105] Starting heapster on port 8082

**Comment by liusl12** [comment]
对了  上面的报错 是dns和heapster的pod不在同一个主机上；如果他们两个的pod在同一个主机会报另外一个错误


 /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb:8086
I0315 06:30:40.940834       1 heapster.go:72] Heapster version v1.3.0-beta.1
I0315 06:30:40.941104       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default" and version v1
I0315 06:30:40.941127       1 configs.go:62] Using kubelet port 10255
E0315 06:30:40.976703       1 kubelet.go:336] Failed to load nodes: the server does not allow access to the requested resource (get nodes)
E0315 06:30:40.979505       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:41.981873       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:42.984033       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:43.986883       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:44.989833       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:45.992269       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:46.994368       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:47.997381       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:48.999557       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
E0315 06:30:50.001994       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:342: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)

**Comment by iiitux** [comment]
rbac问题？是否有执行kubectl create -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml

**Comment by opsnull** [comment]
RBAC 的问题，参考上面的回答。
