### ISSUE TITLE
关于Heapster被拒绝访问的问题

### ISSUE THREAD

**Issue by it2911** [opsnull/follow-me-install-kubernetes-cluster#21]
您好，我在部署完成Heapster后，出现以下画面中的被拒绝访问的问题。
我的Heapster的文件，完全是您的yaml文件的copy来进行复制的，请问是不是有什么地方需要修改？

![image](https://cloud.githubusercontent.com/assets/2803470/25088766/5b8ea8c4-23ab-11e7-9ebc-4eff7f9d6701.png)

**Comment by opsnull** [comment]
权限不足，没有使用heapster-rbac.yaml？

**Comment by it2911** [comment]
最终也不知道是什么原因，但是我重新部署一边就好了，谢谢。
