### ISSUE TITLE
Please enter Username:

### ISSUE THREAD

**Issue by wangshuaizs** [opsnull/follow-me-install-kubernetes-cluster#210]
你好：
    按照您的教程，当配置完master节点，用“kubectl get componentstatuses”查看组件状态时，提示：
Please enter Username: admin
Please enter Password: *****
                            Error from server (Forbidden): User "system:anonymous" cannot list componentstatuses at the cluster scope. (get componentstatuses)
由于之前没有不记得创建过密码，我就用admin试了试，结果不能通过。请问这是为什么?前面生成了各种密钥，现在访问是不是不需要密码？

**Comment by opsnull** [comment]
kubeconfig 中没有 user 信息，所以报错。

**Comment by heyinhenu** [comment]
问题解决了吗？ 我也碰到了这个问题 目前卡在这里
