### ISSUE TITLE
咨询下这个手册有官方参考文档么？

### ISSUE THREAD

**Issue by iiitux** [opsnull/follow-me-install-kubernetes-cluster#211]
您好：
    我打算参照你的手册，进行1.9.4版本的二进制方式安装。但是除了你的手册，kubernetes.io官方网站一直未能找到新版本的二进制安装官方手册，都是kubeadm方式安装或者基于容器方式部署。官方是否有二进制方式安装的手册呢？看了Creating a Custom Cluster from Scratch内容，也是以容器方式部署，缺少些SSL之类细节内容。

**Comment by opsnull** [comment]
本文档是参考官方文档和我的实践总结而成。官方目前没有全面、系统的二进制安装手册。
