### ISSUE TITLE
etcd 启动报错

### ISSUE THREAD

**Issue by 435242634** [opsnull/follow-me-install-kubernetes-cluster#212]
[root@localhost ssl]# sudo mv etcd.service /etc/systemd/system/
[root@localhost ssl]# sudo systemctl daemon-reload
[root@localhost ssl]# sudo systemctl enable etcd
[root@localhost ssl]# sudo systemctl start etcd
Job for etcd.service failed because the control process exited with error code. See "systemctl status etcd.service" and "journalctl -xe" for details.
[root@localhost ssl]# journalctl -xe
-- Subject: Unit etcd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has failed.
-- 
-- The result is failed.
3月 29 22:37:15 localhost.localdomain systemd[1]: Unit etcd.service entered failed state.
3月 29 22:37:15 localhost.localdomain systemd[1]: etcd.service failed.
3月 29 22:37:21 localhost.localdomain systemd[1]: etcd.service holdoff time over, scheduling restart.
3月 29 22:37:21 localhost.localdomain systemd[1]: Starting Etcd Server...
-- Subject: Unit etcd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has begun starting up.
3月 29 22:37:21 localhost.localdomain etcd[4439]: expected IP in URL for binding (https://:2380)
3月 29 22:37:21 localhost.localdomain etcd[4439]: expected IP in URL for binding (https://:2379)
3月 29 22:37:21 localhost.localdomain etcd[4439]: etcd Version: 3.1.6
3月 29 22:37:21 localhost.localdomain etcd[4439]: Git SHA: e5b7ee2
3月 29 22:37:21 localhost.localdomain etcd[4439]: Go Version: go1.7.5
3月 29 22:37:21 localhost.localdomain etcd[4439]: Go OS/Arch: linux/amd64
3月 29 22:37:21 localhost.localdomain etcd[4439]: setting maximum number of CPUs to 1, total number of available CPUs is 1
3月 29 22:37:21 localhost.localdomain etcd[4439]: the server is already initialized as member before, starting as etcd member...
3月 29 22:37:21 localhost.localdomain etcd[4439]: expected IP in URL for binding (https://:2380)
3月 29 22:37:21 localhost.localdomain etcd[4439]: expected IP in URL for binding (https://:2379)
3月 29 22:37:21 localhost.localdomain etcd[4439]: peerTLS: cert = /etc/etcd/ssl/etcd.pem, key = /etc/etcd/ssl/etcd-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/ca.pem, cli
3月 29 22:37:21 localhost.localdomain etcd[4439]: listening for peers on https://:2380
3月 29 22:37:21 localhost.localdomain etcd[4439]: listening for client requests on 127.0.0.1:2379
3月 29 22:37:21 localhost.localdomain etcd[4439]: stopping listening for client requests on :2379
3月 29 22:37:21 localhost.localdomain etcd[4439]: listen tcp :2379: bind: address already in use
3月 29 22:37:21 localhost.localdomain systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
3月 29 22:37:21 localhost.localdomain systemd[1]: Failed to start Etcd Server.
-- Subject: Unit etcd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has failed.
-- 
-- The result is failed.
3月 29 22:37:21 localhost.localdomain systemd[1]: Unit etcd.service entered failed state.
3月 29 22:37:21 localhost.localdomain systemd[1]: etcd.service failed.

**Comment by jianjyan** [comment]
-- Subject: Unit etcd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has begun starting up.
Apr 11 01:52:18 host114 etcd[1871]: expected IP in URL for binding (https://:2380)
Apr 11 01:52:18 host114 etcd[1871]: expected IP in URL for binding (https://:2379)
Apr 11 01:52:18 host114 etcd[1871]: etcd Version: 3.1.6
Apr 11 01:52:18 host114 etcd[1871]: Git SHA: e5b7ee2
Apr 11 01:52:18 host114 etcd[1871]: Go Version: go1.7.5
Apr 11 01:52:18 host114 etcd[1871]: Go OS/Arch: linux/amd64
Apr 11 01:52:18 host114 etcd[1871]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Apr 11 01:52:18 host114 etcd[1871]: expected IP in URL for binding (https://:2380)
Apr 11 01:52:18 host114 etcd[1871]: expected IP in URL for binding (https://:2379)
Apr 11 01:52:18 host114 etcd[1871]: peerTLS: cert = /etc/etcd/ssl/etcd.pem, key = /etc/etcd/ssl/etcd-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/ca.pem, client-cert-auth = false
Apr 11 01:52:18 host114 etcd[1871]: listening for peers on https://:2380
Apr 11 01:52:18 host114 etcd[1871]: The scheme of client url http://127.0.0.1:2379 is HTTP while peer key/cert files are presented. Ignored key/cert files.
Apr 11 01:52:18 host114 etcd[1871]: listening for client requests on 127.0.0.1:2379
Apr 11 01:52:18 host114 etcd[1871]: stopping listening for client requests on :2379
Apr 11 01:52:18 host114 etcd[1871]: listen tcp :2379: bind: address already in use
Apr 11 01:52:18 host114 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Apr 11 01:52:18 host114 systemd[1]: Failed to start Etcd Server.
-- Subject: Unit etcd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has failed.
-- 
-- The result is failed.
Apr 11 01:52:18 host114 systemd[1]: Unit etcd.service entered failed state.
Apr 11 01:52:18 host114 systemd[1]: etcd.service failed.
[root@host114 kubernetes]# ss -ant | grep 2379
[root@host114 kubernetes]# 



我也遇到同样的问题，并且我grep了2379，并没有运行

**Comment by lcgogo** [comment]
在第一个节点上跑etcd会报错，在第二个节点上跑起来后就都好了。这个在本文里说的不详细，只说了第一个节点会卡住。但我实践是这样的。

**Comment by jianjyan** [comment]
我解决了 是因为生成密匙文件的时候，需要将所以节点的IP放入hosts属性， 或者将所有节点映射进一个域名，否则启动不了； 本教程里没有交代这点

**Comment by zlfzy** [comment]
同样的报错

```
[root@k8s system]# journalctl -xe
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has failed.
-- 
-- The result is failed.
May 30 16:52:06 k8s systemd[1]: Unit etcd.service entered failed state.
May 30 16:52:06 k8s systemd[1]: etcd.service failed.
May 30 16:52:11 k8s systemd[1]: etcd.service holdoff time over, scheduling restart.
May 30 16:52:11 k8s systemd[1]: Starting Etcd Server...
-- Subject: Unit etcd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has begun starting up.
May 30 16:52:11 k8s etcd[4197]: expected IP in URL for binding (https://:2380)
May 30 16:52:11 k8s etcd[4197]: expected IP in URL for binding (https://:2379)
May 30 16:52:11 k8s etcd[4197]: etcd Version: 3.1.6
May 30 16:52:11 k8s etcd[4197]: Git SHA: e5b7ee2
May 30 16:52:11 k8s etcd[4197]: Go Version: go1.7.5
May 30 16:52:11 k8s etcd[4197]: Go OS/Arch: linux/amd64
May 30 16:52:11 k8s etcd[4197]: setting maximum number of CPUs to 1, total number of available CPUs is 1
May 30 16:52:11 k8s etcd[4197]: the server is already initialized as member before, starting as etcd member...
May 30 16:52:11 k8s etcd[4197]: expected IP in URL for binding (https://:2380)
May 30 16:52:11 k8s etcd[4197]: expected IP in URL for binding (https://:2379)
May 30 16:52:11 k8s etcd[4197]: peerTLS: cert = /etc/etcd/ssl/etcd.pem, key = /etc/etcd/ssl/etcd-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/c
May 30 16:52:11 k8s etcd[4197]: listening for peers on https://:2380
May 30 16:52:11 k8s etcd[4197]: The scheme of client url http://127.0.0.1:2379 is HTTP while peer key/cert files are presented. Ignored key/cert fi
May 30 16:52:11 k8s etcd[4197]: listening for client requests on 127.0.0.1:2379
May 30 16:52:11 k8s etcd[4197]: stopping listening for client requests on :2379
May 30 16:52:11 k8s etcd[4197]: listen tcp :2379: bind: address already in use
May 30 16:52:11 k8s systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
May 30 16:52:11 k8s systemd[1]: Failed to start Etcd Server.
-- Subject: Unit etcd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has failed.
-- 
-- The result is failed.
May 30 16:52:11 k8s systemd[1]: Unit etcd.service entered failed state.
May 30 16:52:11 k8s systemd[1]: etcd.service failed.
```


我感觉是读不到环境变量，我已经在/etc/profile里面添加了如下内容，还是读不到

```
export NODE_NAME=etcd-host0
export NODE_IP=172.19.0.15
export NODE_IPS="172.19.0.15 172.19.0.14 172.19.0.12"
export ETCD_NODES=etcd-host0=https://172.19.0.15:2380,etcd-host1=https://172.19.0.14:2380,etcd-host2=https://172.19.0.12:2380
```

**Comment by opsnull** [comment]
> 3月 29 22:37:21 localhost.localdomain etcd[4439]: expected IP in URL for binding (https://:2380)
> 3月 29 22:37:21 localhost.localdomain etcd[4439]: expected IP in URL for binding (https://:2379)

的确是没有定义环境变量。参考 environment.sh 和 文档开始位置定义的环境变量。
