### ISSUE TITLE
flanneld安装后各节点无法ping通

### ISSUE THREAD

**Issue by lyc20140320** [opsnull/follow-me-install-kubernetes-cluster#214]
我原先搭建好了flanneld，后面我把etcd中的flanneld记录给删了，重新生成了下，我再各节点重启flanneld后发现flannel.1网卡的ip(还是第一次生成的ip)和etcd中不一样，导致各节点ping不通，请问这种情况怎么解决

[root@k8s-master ~]# etcdctl --endpoints=https://10.0.6.4:2379,https://10.0.6.5:2379,https://10.0.6.6:2379 \
> --ca-file=/etc/kubernetes/ssl/ca.pem \
> --cert-file=/etc/kubernetes/ssl/kubernetes.pem \
> --key-file=/etc/kubernetes/ssl/kubernetes-key.pem get /kube-centos/network/config
{"Network":"172.30.0.0/16","SubnetLen":24,"Backend":{"Type":"vxlan"}}
[root@k8s-master ~]# etcdctl --endpoints=https://10.0.6.4:2379,https://10.0.6.5:2379,https://10.0.6.6:2379 --ca-file=/etc/kubernetes/ssl/ca.pem --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem ls /kube-centos/network/subnets
/kube-centos/network/subnets/172.30.46.0-24
/kube-centos/network/subnets/172.30.60.0-24
/kube-centos/network/subnets/172.30.24.0-24
[root@k8s-master ~]# etcdctl --endpoints=https://10.0.6.4:2379,https://10.0.6.5:2379,https://10.0.6.6:2379 \
> --ca-file=/etc/kubernetes/ssl/ca.pem \
> --cert-file=/etc/kubernetes/ssl/kubernetes.pem \
> --key-file=/etc/kubernetes/ssl/kubernetes-key.pem get /kube-centos/network/subnets/172.30.24.0-24
{"PublicIP":"10.0.6.7","BackendType":"vxlan","BackendData":{"VtepMAC":"56:da:a5:5e:7f:01"}}
[root@k8s-master ~]# etcdctl --endpoints=https://10.0.6.4:2379,https://10.0.6.5:2379,https://10.0.6.6:2379 --ca-file=/etc/kubernetes/ssl/ca.pem --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem get /kube-centos/network/subnets/172.30.46.0-24
{"PublicIP":"10.0.6.5","BackendType":"vxlan","BackendData":{"VtepMAC":"ee:85:c5:f4:f9:0e"}}
[root@k8s-master ~]# etcdctl --endpoints=https://10.0.6.4:2379,https://10.0.6.5:2379,https://10.0.6.6:2379 --ca-file=/etc/kubernetes/ssl/ca.pem --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem get /kube-centos/network/subnets/172.30.60.0-24
{"PublicIP":"10.0.6.6","BackendType":"vxlan","BackendData":{"VtepMAC":"8a:6b:4c:8a:bd:20"}}

各节点
[root@k8s-worker01 ~]# ifconfig flannel.1
flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.30.26.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether ee:85:c5:f4:f9:0e  txqueuelen 0  (Ethernet)
        RX packets 4  bytes 336 (336.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 13 overruns 0  carrier 0  collisions 0

[root@k8s-worker02 ~]# ifconfig flannel.1
flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.30.36.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether 8a:6b:4c:8a:bd:20  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 336 (336.0 B)
        TX errors 0  dropped 1 overruns 0  carrier 0  collisions 0

[root@k8s-worker03 ~]# ifconfig flannel.1
flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.30.52.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether 56:da:a5:5e:7f:01  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by lcgogo** [comment]
inet 172.30.26.0 netmask 255.255.255.255 broadcast 0.0.0.0
你和我一样，flannel.1的掩码是/32，所以只能ping通 172.30.26.0。我也是今天才发现这个的，原因还不清楚。

**Comment by opsnull** [comment]
1. stop kubelet
2. stop flanneld
3. stop docker
4. rm /run/flannel/*
5. etcdctl --endpoints=xxxx rm /coreos.com/network --recursive
6. etcdctl --endpoints=xxxx set /coreos.com/network/config  '{"Network":"10.254.0.0/16", "SubnetLen": 24, "Backend": {"Type": "vxlan"}}'
7. start flanneld
8. start docker
9. start kubelet
