### ISSUE TITLE
部署kubectl配置的04章是不是有笔误？

### ISSUE THREAD

**Issue by lcgogo** [opsnull/follow-me-install-kubernetes-cluster#215]
需要将下载的 kubectl 二进制程序和生成的 ~/.kube/config 配置文件拷贝到**所有使用 kubectl 命令的机器**。

我觉得第二个kubectl应该是kubelet。因为本章最后是分发到运行kubelet的机器上

分发 kubeconfig 文件

将 ~/.kube/config 文件拷贝到运行 kubelet 命令的机器的 ~/.kube/ 目录下。

**Comment by opsnull** [comment]
不是笔误。可以在任意机器上部署和执行 kubectl 命令。
