### ISSUE TITLE
安装flannel集群起不来

### ISSUE THREAD

**Issue by XDongo** [opsnull/follow-me-install-kubernetes-cluster#217]
照着文档一步一步走 flannel起不来,报如下错误：

main.go:132] Installing signal handlers
4月 25 18:07:49 localhost.localdomain flanneld[32050]: I0425 18:07:49.369803   32050 manager.go:136] Determining IP address of default interface
4月 25 18:07:49 localhost.localdomain flanneld[32050]: I0425 18:07:49.370377   32050 manager.go:149] Using interface with name ens32 and address 192.168.1.141
4月 25 18:07:49 localhost.localdomain flanneld[32050]: I0425 18:07:49.370397   32050 manager.go:166] Defaulting external address to interface address (192.168.1.141)
4月 25 18:07:49 localhost.localdomain flanneld[32050]: I0425 18:07:49.410215   32050 local_manager.go:179] Picking subnet in range 172.30.2.0 ... 172.30.1.0
4月 25 18:07:49 localhost.localdomain flanneld[32050]: E0425 18:07:49.410245   32050 network.go:102] failed to register network: failed to acquire lease: out of subnets
4月 25 18:07:50 localhost.localdomain flanneld[32050]: I0425 18:07:50.436010   32050 local_manager.go:179] Picking subnet in range 172.30.2.0 ... 172.30.1.0
4月 25 18:07:50 localhost.localdomain flanneld[32050]: E0425 18:07:50.436078   32050 network.go:102] failed to register network: failed to acquire lease: out of subnets
4月 25 18:07:51 localhost.localdomain flanneld[32050]: I0425 18:07:51.461728   32050 local_manager.go:179] Picking subnet in range 172.30.2.0 ... 172.30.1.0
4月 25 18:07:51 localhost.localdomain flanneld[32050]: E0425 18:07:51.461802   32050 network.go:102] failed to register network: failed to acquire lease: out of subnets

environment.sh是这么写的
SERVICE_CIDR="192.254.1.0/24"
CLUSTER_CIDR="172.30.1.0/24"

**Comment by opsnull** [comment]
> SERVICE_CIDR="192.254.1.0/24"
> CLUSTER_CIDR="172.30.1.0/24"

应该是 /16 段的地址；
