### ISSUE TITLE
Pod 网段，必须是 /16 段地址，为什么？

### ISSUE THREAD

**Issue by kulong0105** [opsnull/follow-me-install-kubernetes-cluster#227]
在 https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/01.%E7%B3%BB%E7%BB%9F%E5%88%9D%E5%A7%8B%E5%8C%96%E5%92%8C%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F.md 中，有如下描述:
```
Pod 网段，必须是 /16 段地址，部署前路由不可达，**部署后**路由可达(flanneld保证)
CLUSTER_CIDR="172.30.0.0/16"
```

什么原因使的只能使用/16段地址？ 是由于flannel的限制吗？
因为，我在使用calico作为网络插件时，没有这个限制。

一些其他小问题：
- 在https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/01.%E7%B3%BB%E7%BB%9F%E5%88%9D%E5%A7%8B%E5%8C%96%E5%92%8C%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F.md 中，描述了需要`设置 kube-node1 可以无密码登录所有节点的 k8s 和 root 账户`,  既然也需要设置root账号无密码登陆，那么整个操作是否可以全部直接基于root账户来操作，而不使用k8s用户？如果可以的话，整个文档描述会更加简洁些？

- `https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/04.%E9%83%A8%E7%BD%B2etcd%E9%9B%86%E7%BE%A4.md` 在启动etcd集群中，有如下描述：
```source /opt/k8s/bin/environment.sh
for node_ip in ${NODE_IPS[@]}
  do
    echo ">>> ${node_ip}"
    ssh root@${node_ip} "systemctl daemon-reload && systemctl enable etcd && systemctl start etcd"
  done
etcd 进程首次启动时会等待其它节点的 etcd 加入集群，命令 systemctl start etcd 会卡住一段时间，为正常现象
```
就像描述中，start命令会卡住，由于使用了for循环，所以这里会一直卡住， 考虑把那条ssh命令放到台后执行，像下面这样 ?

```source /opt/k8s/bin/environment.sh
for node_ip in ${NODE_IPS[@]}
  do
    echo ">>> ${node_ip}"
    ssh root@${node_ip} "systemctl daemon-reload && systemctl enable etcd && systemctl start etcd" &
  done
```

BTW： 我基于kubeadm完成了自动化部署高可用的K8S集群，如果有感兴趣的同学，可以下载下来试一试  https://github.com/kulong0105/kubeadm-ha

**Comment by opsnull** [comment]
> 什么原因使的只能使用/16段地址？是由于flannel的限制吗？

这个是因为后续向 etcd 写入 flanneld Network 配置时，SubnetLen 参数是 24，这里的网络前缀必须小于 24。当然，你也可以指定其它前缀长度。

> 那么整个操作是否可以全部直接基于root账户来操作，而不使用k8s用户？如果可以的话，整个文档描述会更加简洁些？

最小权限原则，部分组件如 etcd、kube-apiserver、kube-controller-manager、kube-scheduler 是以 k8s 账户运行的。

> 所以这里会一直卡住， 考虑把那条ssh命令放到台后执行，像下面这样 ?
可以放在后台运行，但是就看不到执行结果了。

**Comment by kulong0105** [comment]
谢谢你的回答。 闭关这个issue
