### ISSUE TITLE
加入ingress的配置

### ISSUE THREAD

**Issue by sysit** [opsnull/follow-me-install-kubernetes-cluster#23]
没有cloud provider的情况下，对外暴露服务总不能全部用nodeport吧。
用ingress非常有必要

**Comment by opsnull** [comment]
后续会开源新的项目文档: 《post-install-kubernetes-cluster》，包含 Ingress 相关内容，请期待。

**Comment by it2911** [comment]
超级期待！可以close了吧。

**Comment by rootsongjc** [comment]
@it2911 treafik这样中不知道对不对 https://github.com/rootsongjc/follow-me-install-kubernetes-cluster/blob/master/11-traefik-ingress.md
