### ISSUE TITLE
kubelet 运行报 Unable to update cni config: No networks found in /etc/cni/net.d

### ISSUE THREAD

**Issue by zxtyjx** [opsnull/follow-me-install-kubernetes-cluster#232]
根据网上的搜索结果现实，是由于没有cni这个目录导致的，但是教程中又没有cni插件的配置，请问这个应该怎么解决呢？
Jun 22 00:03:17 k8s-master-server kubelet[13584]: I0622 00:03:17.716649   13584 flags.go:27] FLAG: --volume-stats-agg-period="1m0s"
Jun 22 00:03:17 k8s-master-server kubelet[13584]: I0622 00:03:17.716677   13584 feature_gate.go:226] feature gates: &{{} map[]}
Jun 22 00:03:17 k8s-master-server kubelet[13584]: I0622 00:03:17.717844   13584 feature_gate.go:226] feature gates: &{{} map[RotateKubeletClientCertificate:true RotateKubeletServerCertificate:true]}
Jun 22 00:03:17 k8s-master-server kubelet[13584]: I0622 00:03:17.754246   13584 mount_linux.go:211] Detected OS with systemd
Jun 22 00:03:17 k8s-master-server kubelet[13584]: W0622 00:03:17.754367   13584 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Jun 22 00:03:17 k8s-master-server kubelet[13584]: I0622 00:03:17.757845   13584 server.go:376] Version: v1.10.4
Jun 22 00:03:17 k8s-master-server kubelet[13584]: I0622 00:03:17.757886   13584 feature_gate.go:226] feature gates: &{{} map[RotateKubeletClientCertificate:true RotateKubeletServerCertificate:true]}
Jun 22 00:03:17 k8s-master-server kubelet[13584]: F0622 00:03:17.757921   13584 server.go:233] failed to run Kubelet: invalid configuration: option "promiscuous-veth" specified for HairpinMode (--hairpin-mode). Valid options are "none", "hairpin-veth" or "promiscuous-bridge"
Jun 22 00:03:17 k8s-master-server systemd[1]: Unit kubelet.service entered failed state.
Jun 22 00:03:17 k8s-master-server systemd[1]: kubelet.service failed.

另外：06-1.api-server.md 这个文件中少了一个$符号导致分发有问题
ssh root@{MASTER_IP} "systemctl daemon-reload && systemctl enable kube-apiserver && systemctl start kube-apiserver"
---》
ssh root@${MASTER_IP} "systemctl daemon-reload && systemctl enable kube-apiserver && systemctl start kube-apiserver"

**Comment by Marcyle** [comment]
我也遇到了同样的问题，不知道你是怎么解决的呢？
