### ISSUE TITLE
x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."

### ISSUE THREAD

**Issue by zxtyjx** [opsnull/follow-me-install-kubernetes-cluster#233]
现在按照教程部署coredns运行后查看日志显示 x509无法解析dns地址错误如下：
x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."

**Comment by it2911** [comment]
这个感觉是证书错误

**Comment by zxtyjx** [comment]
对我也是这么分析的，但是根据教程我重新部署了两边都是这个结果就很郁闷了，另外在教程中07-2.部署 kubelet 组件这一节中，有个地方很纳闷，教程开始的部分是生成kubelet-bootstrap.kubeconfig并且分发到各个服务器上然后部署kubelet服务，但是在后面一段中又说如果没有这个文件kubelet服务器启动的时候会自动生成，这个地方没看明白可以帮忙解释一下吗？

**Comment by hoperuin** [comment]
我的也是这个错误，求解。

**Comment by opsnull** [comment]
@zxtyjx 你搞混淆了。kubelet 启动时检查是否有 kubelet.kubeconfig 文件，如果没有则使用 kubelet-bootstrap.kubeconfig 文件向 apiserver 发送 CSR 请求，然后自动生成 kubelet.kubeconfig 文件。

**Comment by opsnull** [comment]
@zxtyjx 完整贴下相关日志，看起来像  coredns 配置的不对。

**Comment by hoperuin** [comment]
这个问题应该是配置问题，由于启用了x509证书认证，所以coredns也应该有相应的客户端证书配置。但从文档中看不到有这个提示。我把coredns换成kube-dns并且配置了客户端证书，成功了。猜测coredns估计也是这个原因。

**Comment by zxtyjx** [comment]
@opsnull 由于那个配置我重新走了一遍教程，现在kubelet还没有起成功，回头等完成了我再贴下coredns的日志吧，我也是感觉因为创建coredns时没有设置证书的地方，所以才会有这个问题。

**Comment by ioiioo** [comment]
@opsnull 我也遇到了 跟issues #151 相同的问题:
我这儿的错误日志如下:
```
[k8s@kube-node1 ~]$ kubectl get all -n kube-system
NAME                                        READY     STATUS             RESTARTS   AGE
pod/coredns-77c989547b-ch5bv                0/1       CrashLoopBackOff   125        18h
pod/coredns-77c989547b-p5ccx                0/1       CrashLoopBackOff   202        21h
```

查看CrashLoopBackOff 状态的pod日志如下:
```
....
E0625 07:45:21.933070       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:319: Failed to list *v1.Namespace: Get https://10.254.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
E0625 07:45:21.938464       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:312: Failed to list *v1.Service: Get https://10.254.0.1:443/api/v1/services?limit=500&resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
```

**Comment by opsnull** [comment]
> tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."

这个 dnsName 本身是 OK 的，问题可能出在 CA 证书有问题，不能用于校验 kube-apiserver 的证书。
有可能：
1. CA 证书创建的有问题；参考：02.创建CA证书和秘钥.md
2. apiserver 和 controller-manager 参数配置的有问题：kube-apiserver ：--service-account-key-file=/etc/kubernetes/cert/ca-key.pem; kube-controller-manager: --root-ca-file=/etc/kubernetes/cert/ca.pem  --service-account-private-key-file=/etc/kubernetes/cert/ca-key.pem;

可以使用如下命令检查  ca.pem 是否包含 CA:TRUE 内容：
```
$ openssl x509  -noout -text -in /etc/kubernetes/cert/ca.pem |grep CA:
                CA:TRUE, pathlen:2
```

**Comment by hoperuin** [comment]
看golang的Issues中有个类似的，说在go1.9.5中解决了，k8s用的是1.9.3编译的，不知道是不是这个原因。但是同样的版本，kube-dns的ssl验证就能成功。

**Comment by hoperuin** [comment]
@zxtyjx @it2911 @opsnull 问题解决了。
配置如下：
# diff coredns.yaml coredns.yaml.base
61,65c61,64
<         kubernetes cluster.local. in-addr.arpa ip6.arpa {
<            endpoint https://192.168.92.136:6443
<            tls /etc/coredns/admin.pem /etc/coredns/admin-key.pem /etc/coredns/ca.pem
<            pods insecure
<            fallthrough in-addr.arpa ip6.arpa
---
>         kubernetes __PILLAR__DNS__DOMAIN__ in-addr.arpa ip6.arpa {
>             pods insecure
>             upstream
>             fallthrough in-addr.arpa ip6.arpa
71,146d69
<   admin-key.pem: |
<     -----BEGIN RSA PRIVATE KEY-----
<     MIIEogIBAAKCAQEAye5L1M0B0McQ7kYzQHtGv4CR8PlQeVwhTeNLUKFOUc8sfuWp
<     71KESfvfjr1fAC1bbf0UEUGlO8KV7wBIcF1/6hvtk+rjguI1q0k+w1ex0wslnUlo
<     xs0JBrLlda8keqnSMq5xmy0rqN8lRvs8K/IIcajda7pxqrjkdcvoZGO1K1CuC7Ou
<     BUpKFM4WtbEMD+7l/Kg2LG+wUx8jY8qNFCIguD/3ly3qM/khljXiefSc1QHcAcoz
<     8MWcKGzkIGMe60KbQOvcLHy+3+bD8EUtID/F2kJGvNX6xvD3QqGtc8k7CauF3rox
<     8feWZuT3wMdVDPR0xuVamMdD3H7yjiP7mF4n+wIDAQABAoIBADhKOk9W2qO1ak3R
<     ueXGt6EYmRZAmaNLAGmy68LNRITfqLqzEN0K9p+dG+OxfHMTMcKGYvqwfvwasSsP
<     vCG+nrLHGEI8nzFUF7vozhssLgDzwYeH+DI648I/SmG08glTn6nLIRYt0Fbh5YVU
<     8aAadyof9aFbNuZtZhpEPkMF3HH3K8+wPrYSFyAXzmCY1Q+cpsjVQOHIpGH3nprw
<     Pj07Wdg+481UzubcEHz+jb9pxGjo4Anrt2b8CsVx94Qpk1xfDGh2pAoEy4aZsLIA
<     ehkV20st1CkwLGXODSbx9WojnUn8jYf2nQNdcPP5aU279dZ3+XdKQap/Wpql8Bp6
<     iZyjwtECgYEA3ZVnw8ci6lxUMAaZmhThRLGvrmuP7eGUYF0/NZvPp/QltaaiFwyV
<     aIr6nyV6i+dUI0ETr79gSIIM+XsoQhtgEneQSGpLQkgruPcibfk29GMVJF/oQ5vY
<     ksI7B2ZOy0SsHe2lqn+MzB6QfiKvGMNvYep9DR3pJhTj32fnk6tYJeMCgYEA6Ut1
<     Zr3+1QTuV0kE8//SVhfkwyAKra6Yh0RijEN8UBtEFcvS9u7nhb3+B9iYrC5NOu9E
<     VeKC8HJHWkieNL5AROMnlSaOLH1s8gG1iyEJoCsAPxbKL1CA0Q8QVrX0MBnVXD9w
<     EzmaVMeBT+nUiBcpEQWGX/AyVPZNiAnSsSsYUQkCgYAIiYIW8+wvdWE0/HwciKNp
<     PyNSqAhClQdfcxhFW3xzrx9o0UO7eZukDH69dPc0vrPqK86zXb866+/OCOWzLlTU
<     QVEIyTefFSLCHJtx+0EXx12AKkXLnQyKEvutPE7a3Al5mbdhS0rEboUIpxNx882t
<     yxgIUleyROnGqL0uXlKmGwKBgGa3YZZ9+tBhnmrx7Gtd7IcZeBBtcCYuZFvSQS2O
<     nRJMHvsVxeoRIADjuRBNTlMpA7n6FPVXiN1DA6V9qaKBTZzHAuuJkTmHc8tN81ex
<     kSJjLHWanCSe5kilwETdUglHpog6KidcylWfjZDY3EmbIOqsqxBcmlyMIXDPGmQF
<     HGy5AoGAfBHTrYlAiLCj8nvmWf2usW//MR2/EnpOYZXnKjTbddzpCMq9xPs13C0Z
<     2KEpXHFiYivNlWCqh1mpRCoZ7Eddyjd1igKa05bq5H5mL/RySjl9/dylGD5E5u/w
<     VMK++5F98NJEK2jErFiphIUTr2EVLv66gbd+aFcjdxwZx4+7YG8= 
<     -----END RSA PRIVATE KEY-----
<   admin.pem: |
<     -----BEGIN CERTIFICATE-----
<     MIID4zCCAsugAwIBAgIUBpcPynUHQZB3CCVdl50TZ8bFd2MwDQYJKoZIhvcNAQEL
<     BQAwaDELMAkGA1UEBhMCQ04xEDAOBgNVBAgTB0JlaUppbmcxEDAOBgNVBAcTB0Jl
<     aUppbmcxDDAKBgNVBAoTA2s4czESMBAGA1UECxMJNFBhcmFkaWdtMRMwEQYDVQQD
<     EwprdWJlcm5ldGVzMB4XDTE4MDYyMDA3MDAwMFoXDTI4MDYxNzA3MDAwMFowbjEL
<     MAkGA1UEBhMCQ04xEDAOBgNVBAgTB0JlaUppbmcxEDAOBgNVBAcTB0JlaUppbmcx
<     FzAVBgNVBAoTDnN5c3RlbTptYXN0ZXJzMRIwEAYDVQQLEwk0UGFyYWRpZ20xDjAM
<     BgNVBAMTBWFkbWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAye5L
<     1M0B0McQ7kYzQHtGv4CR8PlQeVwhTeNLUKFOUc8sfuWp71KESfvfjr1fAC1bbf0U
<     EUGlO8KV7wBIcF1/6hvtk+rjguI1q0k+w1ex0wslnUloxs0JBrLlda8keqnSMq5x
<     my0rqN8lRvs8K/IIcajda7pxqrjkdcvoZGO1K1CuC7OuBUpKFM4WtbEMD+7l/Kg2
<     LG+wUx8jY8qNFCIguD/3ly3qM/khljXiefSc1QHcAcoz8MWcKGzkIGMe60KbQOvc
<     LHy+3+bD8EUtID/F2kJGvNX6xvD3QqGtc8k7CauF3rox8feWZuT3wMdVDPR0xuVa
<     mMdD3H7yjiP7mF4n+wIDAQABo38wfTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
<     FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFFYP
<     P8xgA77+pYDhJFfBbPHz7hZ0MB8GA1UdIwQYMBaAFDsFnJr0Cbbg7FZ52gTM/HtH
<     afwJMA0GCSqGSIb3DQEBCwUAA4IBAQCTUHO5QxSoss9EOq2OrqU3htxtqqvfLoWG
<     bq7iTvqf83zl0ktt1R35TTpXGlFcm9DoMN20bi4nz5NnP/TmPROK/EM8rzWD6uIa
<     auhBMkXGoyBKkpIb3fgwog2YC1j5lf3hGVmAJb7czigRx+TfzHO+HrbF+jIgBwL2
<     0k03r43hlHZnpeed2ZRtmk4NQ4ZGN5faifClj4tvGyhZb/crnSX9K3qriTs9FPc+
<     D9cseLNAfSpfQ2lrsNzK7eoQj6suuqaW1+cXFpbvSjvJ2CXjZvH/DuAaw8pDLIsn
<     Z4elLStfiC9tR2WT7hFInpPoY5qqLizWM6Ne9C3bv+nNAGlqwIDk
<     -----END CERTIFICATE-----
<   ca.pem: |
<     -----BEGIN CERTIFICATE-----
<     MIIDxDCCAqygAwIBAgIUOO2f8/u0TJLcyfRvwfNohXQMJjwwDQYJKoZIhvcNAQEL
<     BQAwaDELMAkGA1UEBhMCQ04xEDAOBgNVBAgTB0JlaUppbmcxEDAOBgNVBAcTB0Jl
<     aUppbmcxDDAKBgNVBAoTA2s4czESMBAGA1UECxMJNFBhcmFkaWdtMRMwEQYDVQQD
<     EwprdWJlcm5ldGVzMB4XDTE4MDYyMDA2NTYwMFoXDTIzMDYxOTA2NTYwMFowaDEL
<     MAkGA1UEBhMCQ04xEDAOBgNVBAgTB0JlaUppbmcxEDAOBgNVBAcTB0JlaUppbmcx
<     DDAKBgNVBAoTA2s4czESMBAGA1UECxMJNFBhcmFkaWdtMRMwEQYDVQQDEwprdWJl
<     cm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApmZDDR4GOK2H
<     gFetiTtATKXgWZUzy9X0z9j+0mr7ZQx/ZnMsGk60Ha36r+5zJHWVpRjS3cPYjt2b
<     bDTfjmLkdYnrq72R6CC9xl5/MjRuryrgiGgztNSGj45l3KKqoIGDERSlvUlYwtAC
<     A9WH8kB+Y6CV9jU8i+xj8M4+8NGeWMj5tWVsDaonSNLEOdLg9K5R14n3qBe+V6Um
<     eHQRB6FZKNLz3BadO7E/PNNSYfNvljuiP91qn8qvQPfJqESxKbJ7uYuYAo2+Xn7B
<     1yHG/OMo2NqQVXs8EI+XhUk3po0FCpYOK70q3AiJnjZU7FcNACh8tsZFzTfZ7IIw
<     Fh2/J4absQIDAQABo2YwZDAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB
<     /wIBAjAdBgNVHQ4EFgQUOwWcmvQJtuDsVnnaBMz8e0dp/AkwHwYDVR0jBBgwFoAU
<     OwWcmvQJtuDsVnnaBMz8e0dp/AkwDQYJKoZIhvcNAQELBQADggEBAC6bPkZalcc/
<     y7nhxIE977ToHl9uePCFhRV210LGlJqxowBPoPROghs8OkL9vMMfd6uELcC0qaAW
<     zDCrNjIdS1GleMNJAhfvct5Um73ydNJHVbOo5AX8qW1o2MaWbUC4Tpqak0Tmu6mr
<     etVqymzxDs38FkkTdqORXgUaPI+4AyQTTy//FZAryW4s1zMBfr4vTQ8xXPrk43tk
<     xYmY0BNP+eOKQWt3eOm5q7OIlVvrcCfdHaVwdq8XOi31fuUEHT2pkpO3Wvcs+F5b
<     7cWKu69//tF3wC14Bvxg6G23ytNVwqppuVuDVOGj4axFAfTdZIrSW/3yoNKtUic1
<     hZ2+E8II9zA=
<     -----END CERTIFICATE-----
180c103
<         image: coredns/coredns:1.1.4
---
>         image: coredns/coredns:1.0.6
216,221d138
<             - key: admin-key.pem
<               path: admin-key.pem
<             - key: admin.pem
<               path: admin.pem
<             - key: ca.pem
<               path: ca.pem
236c153
<   clusterIP: 10.254.0.2
---
>   clusterIP: __PILLAR__DNS__SERVER__
其中证书内容分别为ca.pem,admin-key.pem和admin.pem的证书内容。coredns镜像换1.1.4的最新镜像。
# 测试
root@nginx:/# ping my-nginx
PING my-nginx.default.svc.cluster.local (10.254.34.186): 48 data bytes
56 bytes from 10.254.34.186: icmp_seq=0 ttl=64 time=6.959 ms
56 bytes from 10.254.34.186: icmp_seq=1 ttl=64 time=0.076 ms
56 bytes from 10.254.34.186: icmp_seq=2 ttl=64 time=0.126 ms
^C--- my-nginx.default.svc.cluster.local ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.076/2.387/6.959/3.233 ms
root@nginx:/# ping kubernetes
PING kubernetes.default.svc.cluster.local (10.254.0.1): 48 data bytes
56 bytes from 10.254.0.1: icmp_seq=0 ttl=64 time=0.081 ms
56 bytes from 10.254.0.1: icmp_seq=1 ttl=64 time=0.103 ms
56 bytes from 10.254.0.1: icmp_seq=2 ttl=64 time=0.097 ms
^C--- kubernetes.default.svc.cluster.local ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.081/0.094/0.103/0.000 ms
root@nginx:/# ping coredns.kube-system.svc.cluster.local
PING coredns.kube-system.svc.cluster.local (10.254.0.2): 48 data bytes
56 bytes from 10.254.0.2: icmp_seq=0 ttl=64 time=0.098 ms
56 bytes from 10.254.0.2: icmp_seq=1 ttl=64 time=0.184 ms
56 bytes from 10.254.0.2: icmp_seq=2 ttl=64 time=0.097 ms
56 bytes from 10.254.0.2: icmp_seq=3 ttl=64 time=0.152 ms
^C--- coredns.kube-system.svc.cluster.local ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.097/0.133/0.184/0.037 ms

**Comment by cosiner** [comment]
升级一下coredns版本, 我试过正常了

**Comment by opsnull** [comment]
@hoperuin 并不需要为 coredns 配置证书，它默认使用 ServiceAccount 中的 Token 和 CA 来访问 apiserver。这个错误估计与没有正确配置ServiceAccount有关，需要检查下 kube-apiserver 和 kube-controller-manager 中相关配置。

**Comment by opsnull** [comment]
@cosiner 你配置了证书么？

**Comment by opsnull** [comment]
@all 找到原因呢，go 1.10 编译的二进制文件不支持解析证书中最后一位是 .  的域名了。。。把 kubernetes.default.svc.cluster.local. 最后的 . 去掉即可。

**Comment by zxtyjx** [comment]
@opsnull 我也是更新了coredns的版本后直接通过了，不用配置证书！
