### ISSUE TITLE
kubectl exec  nginx -i -t -- /bin/bas

### ISSUE THREAD

**Issue by turboic** [opsnull/follow-me-install-kubernetes-cluster#237]
unable to upgrade connection: Forbidden (user=kubernetes, verb=create, resource=nodes, subresource=proxy)

**Comment by opsnull** [comment]
kubernetes 证书权限的问题，请参考 06-1.部署 kube-apiserver 组件.md 中的 “授予 kubernetes 证书访问 kubelet API 的权限” 一节。
