### ISSUE TITLE
metrics-server:Back-off restarting failed container

### ISSUE THREAD

**Issue by hoperuin** [opsnull/follow-me-install-kubernetes-cluster#238]
I0624 10:29:05.897660       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:https://kubernetes.default?kubeletHttps=true&amp;kubeletPort=10250
I0624 10:29:05.907719       1 heapster.go:72] Metrics Server version v0.2.1
I0624 10:29:05.908045       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default" and version 
I0624 10:29:05.908066       1 configs.go:62] Using kubelet port 10250
I0624 10:29:05.909213       1 heapster.go:128] Starting with Metric Sink
I0624 10:29:12.498852       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0624 10:29:30.700536       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file

**Comment by opsnull** [comment]
请严格follow 09-4.部署 metrics-server 插件 文档，其中有向 kube-apiserver 和 kube-controller-manager 添加参数的部分。

**Comment by hoperuin** [comment]
这个添加了，kube-apiserver里面是缺少参数的，controller-manager我看了下service脚本里面是有的。

**Comment by opsnull** [comment]
> kube-apiserver里面是缺少参数的

都添加完了，还有问题么？

**Comment by hoperuin** [comment]
就是添加完参数，重启之后报的这个错。

**Comment by hoperuin** [comment]
重新测试了下，没问题了，还是配置有问题。

**Comment by AsanZhang** [comment]
部署 metrics-server 插件前必须部署 heapster 插件吗？我也是报这个错，并且严格follow 09-4.部署 metrics-server 插件 文档，向 kube-apiserver 和 kube-controller-manager 添加参数的：
` --requestheader-client-ca-file=/etc/kubernetes/cert/ca.pem \
  --requestheader-allowed-names="aggregator" \
  --requestheader-extra-headers-prefix="X-Remote-Extra-" \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --proxy-client-cert-file=/etc/kubernetes/cert/metrics-server.pem \
  --proxy-client-key-file=/etc/kubernetes/cert/metrics-server-key.pem \
  --runtime-config=api/all=true
`
我看容器日志报错：
`F0717 22:51:33.075646       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file`
