### ISSUE TITLE
 Liveness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by ghqaz3633** [opsnull/follow-me-install-kubernetes-cluster#240]
如题，按照教程：部署 coredns 插件 报如下错误，并一直重启

Events:
  Type     Reason                 Age                 From                 Message
  ----     ------                 ----                ----                 -------
  Normal   Scheduled              39m                 default-scheduler    Successfully assigned coredns-77c989547b-9ndff to kube-node1
  Normal   SuccessfulMountVolume  39m                 kubelet, kube-node1  MountVolume.SetUp succeeded for volume "config-volume"
  Normal   SuccessfulMountVolume  39m                 kubelet, kube-node1  MountVolume.SetUp succeeded for volume "coredns-token-hhs96"
  Normal   Pulled                 36m (x3 over 39m)   kubelet, kube-node1  Container image "coredns/coredns:1.0.6" already present on machine
  Normal   Created                36m (x3 over 39m)   kubelet, kube-node1  Created container
  Normal   Started                36m (x3 over 39m)   kubelet, kube-node1  Started container
  Normal   Killing                36m (x2 over 38m)   kubelet, kube-node1  Killing container with id docker://coredns:Container failed liveness probe.. Container will be killed and recreated.
  Warning  BackOff                14m (x42 over 28m)  kubelet, kube-node1  Back-off restarting failed container
  Warning  Unhealthy              9m (x42 over 38m)   kubelet, kube-node1  Liveness probe failed: HTTP probe failed with statuscode: 503
  Normal   SuccessfulMountVolume  7m                  kubelet, kube-node1  MountVolume.SetUp succeeded for volume "coredns-token-hhs96"
  Normal   SuccessfulMountVolume  7m                  kubelet, kube-node1  MountVolume.SetUp succeeded for volume "config-volume"
  Normal   SandboxChanged         7m                  kubelet, kube-node1  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                 4m (x3 over 7m)     kubelet, kube-node1  Container image "coredns/coredns:1.0.6" already present on machine
  Normal   Created                4m (x3 over 7m)     kubelet, kube-node1  Created container
  Normal   Started                4m (x3 over 7m)     kubelet, kube-node1  Started container
  Normal   Killing                4m (x2 over 5m)     kubelet, kube-node1  Killing container with id docker://coredns:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy              1m (x14 over 6m)    kubelet, kube-node1  Liveness probe failed: HTTP probe failed with statuscode: 503

**Comment by hoperuin** [comment]
docker logs -f -n kube-system pods/coredns-77c989547b-9ndff

**Comment by ghqaz3633** [comment]
这个忘记看了，没想到也是这个错： [issues/233](https://github.com/opsnull/follow-me-install-kubernetes-cluster/issues/233)
E0626 09:49:34.137597       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:319: Failed to list *v1.Namespace: Get https://10.254.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
E0626 09:49:34.153254       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:312: Failed to list *v1.Service: Get https://10.254.0.1:443/api/v1/services?limit=500&resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
@hoperuin

**Comment by hoperuin** [comment]
@ghqaz3633 问题已解决，请查看 #233
