### ISSUE TITLE
$CLUSTER_DNS_DOMAIN环境变量

### ISSUE THREAD

**Issue by PXzzzpython** [opsnull/follow-me-install-kubernetes-cluster#241]
请问作者大大专门设置这个环境变量，我可以理解为service的域名解析格式service_name.namespace_name.svc.cluster.local从svc之后是可以自己设定的吗

**Comment by opsnull** [comment]
> service_name.namespace_name.svc.cluster.local从svc之后是可以自己设定的吗

是的。

**Comment by PXzzzpython** [comment]
谢谢
