### ISSUE TITLE
Error:  100: Key not found (/kubernetes/network/subnets/172.30.81.0-24) [15]

### ISSUE THREAD

**Issue by heyinhenu** [opsnull/follow-me-install-kubernetes-cluster#243]
source /opt/k8s/bin/environment.sh
etcdctl \
  --endpoints=${ETCD_ENDPOINTS} \
  --ca-file=/etc/kubernetes/cert/ca.pem \
  --cert-file=/etc/flanneld/cert/flanneld.pem \
  --key-file=/etc/flanneld/cert/flanneld-key.pem \
  get ${FLANNEL_ETCD_PREFIX}/subnets/172.30.81.0-24

对应的输出：Error:  100: Key not found (/kubernetes/network/subnets/172.30.81.0-24) [15]

在各节点上 ping 所有 flannel 接口 IP，这个ping不通 ，其余的和教程结果完全一样，求教。

**Comment by heyinhenu** [comment]
问题已经解决，谢谢大家

**Comment by haiya512** [comment]
> 问题已经解决，谢谢大家

怎么解决的？
