### ISSUE TITLE
coredns 的问题

### ISSUE THREAD

**Issue by songhe2136** [opsnull/follow-me-install-kubernetes-cluster#248]
我 exec 到  pod 查看  dns文件，已经获取到了coredns 的地址。pod 能通外网，但是不能解析外网的dns记录。
运行 coredns  的 pod 容器，运行一段时间就 自动崩溃了。
coredns 日志报错如下：

E0629 04:39:37.533648       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:312: Failed to list *v1.Service: Get https://10.254.0.1:443/api/v1/services?limit=500&resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
E0629 04:39:37.537800       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:319: Failed to list *v1.Namespace: Get https://10.254.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."

**Comment by opsnull** [comment]
参考 #233

**Comment by songhe2136** [comment]
谢谢，参考 issue 233，我的问题解决了。但是现在出现了 coredns 出现了新的问题： coredns 日志如下
A: unreachable backend: read udp 172.30.47.5:41129->10.10.3.61:53: i/o timeout
A: unreachable backend: read udp 172.30.47.5:41129->10.10.3.61:53: i/o timeout
A: unreachable backend: read udp 172.30.47.5:41129->10.10.3.61:53: i/o timeout
10.10.3.61 是我的上游 内网 dns。
检查了配置，组件日志也没啥问题。不知道怎么回事，张老师。

**Comment by songhe2136** [comment]
我配置上游dns 为公共dns 也不行：
A: unreachable backend: read udp 172.30.47.5:46541->114.114.114.114:53: i/o timeout
A: unreachable backend: read udp 172.30.47.5:46541->114.114.114.114:53: i/o timeout
A: unreachable backend: read udp 172.30.47.5:46541->114.114.114.114:53: i/o timeout

**Comment by zchunhai** [comment]
@songhe2136  我也遇到同样的问题，请问最后找到解决方法了吗？

**Comment by songhe2136** [comment]
解决了

**Comment by a307582707** [comment]
求分享

**Comment by songhe2136** [comment]
> 求分享

810485328  加我 qq
