### ISSUE TITLE
容器之间访问的问题，帮忙看下谢谢！

### ISSUE THREAD

**Issue by zxtyjx** [opsnull/follow-me-install-kubernetes-cluster#253]
我有三台服务器分别是：
192.168.13.186
192.168.13.146
192.168.13.147

根据教程成功创建了k8s集群，并且也安装了dns、dashboard、ingress-nginx插件，但是现在碰到一个问题，我在创建pod的时候，如果容器是在192.168.13.186或者192.168.13.147上，就可以ping同我三台服务器的ip地址，但是如果容器是在192.168.13.146上就只能ping通146，186和147都无法ping通。

请问这个问题应该是哪里出现了问题呢？

补充：
不管在哪台服务器上的容器之间访问没有问题，都可以ping通。

**Comment by liyongzhezz** [comment]
看下防火墙，有没有放开
