### ISSUE TITLE
kubelet启动报错，好像有人遇到过同样的问题，求教

### ISSUE THREAD

**Issue by Marcyle** [opsnull/follow-me-install-kubernetes-cluster#256]
Jul  3 14:07:33 kubenode01 kubelet: I0703 14:07:33.881265   22675 feature_gate.go:226] feature gates: &{{} map[]}
Jul  3 14:07:33 kubenode01 kubelet: I0703 14:07:33.885888   22675 feature_gate.go:226] feature gates: &{{} map[RotateKubeletClientCertificate:true RotateKubeletServerCertificate:true]}
Jul  3 14:07:33 kubenode01 kubelet: I0703 14:07:33.899065   22675 mount_linux.go:211] Detected OS with systemd
Jul  3 14:07:33 kubenode01 kubelet: W0703 14:07:33.899173   22675 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Jul  3 14:07:33 kubenode01 kubelet: I0703 14:07:33.921925   22675 server.go:376] Version: v1.10.4
Jul  3 14:07:33 kubenode01 kubelet: I0703 14:07:33.921961   22675 feature_gate.go:226] feature gates: &{{} map[RotateKubeletClientCertificate:true RotateKubeletServerCertificate:true]}
Jul  3 14:07:33 kubenode01 kubelet: F0703 14:07:33.921993   22675 server.go:233] failed to run Kubelet: invalid configuration: option "promiscuous-veth" specified for HairpinMode (--hairpin-mode). Valid options are "none", "hairpin-veth" or "promiscuous-bridge"

**Comment by hoperuin** [comment]
不要用gitbook，直接看github master分支。配置问题，promiscuous-veth需要修改为promiscuous-bridge

**Comment by Marcyle** [comment]
多谢，已解决！
自己在kubelet.service中添加了--hairpin-mode=promiscuous-bridge
