### ISSUE TITLE
动态扩展 master 节点的证书问题

### ISSUE THREAD

**Issue by wzt3309** [opsnull/follow-me-install-kubernetes-cluster#262]
@opsnull 您好，我有一个疑问，就是在部署 master 节点创建证书的时候，使用了 `host` 字段去指定 ip，当新添加 master 节点的时候，是不是要重新生成证书（有新 ip 要加入进来）

ps. worker 节点我知道，TLS Bootstrap 生成证书，不会有这个问题

**Comment by songhe2136** [comment]
1.如果是集群已经创建好的话，master 扩展，就要重新生成证书了。你坐 master 高可用的话，其实更换正时还算方便。
2.如果是还未创建的集群，那么你可以在创建证书的时候 预留 ip，届时可以直接进行master扩展。
