### ISSUE TITLE
按 07-2.kubelet 章节部署最后并没有发现有 cadvisor 这个服务的端口

### ISSUE THREAD

**Issue by nibocn** [opsnull/follow-me-install-kubernetes-cluster#267]
Kubernetes Version: v1.11.0

你好，按文章描述操作到 07-2.kubelet 章节，最后部署完成后并没有发现文中所说的 cadvisor 服务相关端口，请问这个是单独部署的吗？

```
$ sudo netstat -lnpt | grep kubelet
tcp        0      0 127.0.0.1:45274         0.0.0.0:*               LISTEN      20102/kubelet
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      20102/kubelet
tcp        0      0 172.27.129.105:10250    0.0.0.0:*               LISTEN      20102/kubelet
````

**Comment by mawennan** [comment]
Kubernetes Version: v1.11.0
你好，我也是卡到这个步骤了，每次重启“127.0.0.1:45274”端口都是会变的。

之后的 "curl -s --cacert /etc/kubernetes/cert/ca.pem --cert /etc/kubernetes/cert/kube-controller-manager.pem --key /etc/kubernetes/cert/kube-controller-manager-key.pem https://172.27.129.111:10250/metrics" 也失败了，报错如下：

* NSS error -8172 (SEC_ERROR_UNTRUSTED_ISSUER)
* Peer's certificate issuer has been marked as not trusted by the user.

**Comment by opsnull** [comment]
Sorry，本文档暂不只支持 v1.11.
