### ISSUE TITLE
无法进入pod内部

### ISSUE THREAD

**Issue by gitplyx** [opsnull/follow-me-install-kubernetes-cluster#268]
root@kube-node1:~# kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
my-nginx-86555897f9-ddjcg   1/1       Running   0          12m
my-nginx-86555897f9-xglkd   1/1       Running   0          12m
nginx                       1/1       Running   0          8m
nginx-ds-7g6fp              1/1       Running   0          1h
nginx-ds-9cjjv              1/1       Running   0          1h
nginx-ds-jrzqs              1/1       Running   0          1h
root@kube-node1:~# kubectl exec -it nginx bash
error: unable to upgrade connection: Forbidden (user=kubernetes, verb=create, resource=nodes, subresource=proxy)

无法进入pod内部

**Comment by liyongzhezz** [comment]
执行kubectl create clusterrolebinding kube-apiserver:kubelet-apis --clusterrole=system:kubelet-api-admin --user kubernetes即可

**Comment by 957446525** [comment]
执行了下面的命令，还是报错，大佬是什么原因呢
[root@zhangjun-k8s01 work]# kubectl create clusterrolebinding kube-apiserver:kubelet-apis --clusterrole=system:kubelet-api-admin --user kubernetes
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "kube-apiserver:kubelet-apis" already exists
[root@zhangjun-k8s01 work]# kubectl exec dnsutils-ds-nzj9m nslookup kubernetes
error: unable to upgrade connection: Forbidden (user=kubernetes, verb=create, resource=nodes, subresource=proxy)
