### ISSUE TITLE
kube-schedulerb日志中出现"Failed to list *v1.ReplicationController: Unauthorized"

### ISSUE THREAD

**Issue by hnzouzc** [opsnull/follow-me-install-kubernetes-cluster#270]
按照06-3.scheduler集群部署kube-schedule(三个节点),日志中出现大量未授权信息。

➜  kubernetes kubectl get endpoints kube-scheduler --namespace=kube-system  -o yaml
Error from server (NotFound): endpoints "kube-scheduler" not found

vi kube-scheduler.ERROR
 E0708 17:31:42.177705   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.ReplicationController: Unauthorized
E0708 17:31:42.178737   18834 reflector.go:205] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:594: Failed to list *v1.Pod: Unauthorized
E0708 17:31:42.179813   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.ReplicaSet: Unauthorized
E0708 17:31:42.180849   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Service: Unauthorized
E0708 17:31:42.181813   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.PersistentVolume: Unauthorized
E0708 17:31:42.183273   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.PodDisruptionBudget: Unauthorized
E0708 17:31:43.174286   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.PersistentVolumeClaim: Unauthorized
E0708 17:31:43.174398   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Node: Unauthorized
E0708 17:31:43.176307   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.StorageClass: Unauthorized
E0708 17:31:43.177021   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.StatefulSet: Unauthorized
E0708 17:31:43.178443   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.ReplicationController: Unauthorized
E0708 17:31:43.179718   18834 reflector.go:205] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:594: Failed to list *v1.Pod: Unauthorized
E0708 17:31:43.180700   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.ReplicaSet: Unauthorized
E0708 17:31:43.181688   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Service: Unauthorized
E0708 17:31:43.182843   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.PersistentVolume: Unauthorized
E0708 17:31:43.183927   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.PodDisruptionBudget: Unauthorized
E0708 17:31:44.176165   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.PersistentVolumeClaim: Unauthorized
E0708 17:31:44.179657   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.ReplicationController: Unauthorized
E0708 17:31:44.179704   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Node: Unauthorized
E0708 17:31:44.179755   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.StatefulSet: Unauthorized
E0708 17:31:44.179801   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.StorageClass: Unauthorized
E0708 17:31:44.180725   18834 reflector.go:205] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:594: Failed to list *v1.Pod: Unauthorized
E0708 17:31:44.181779   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.ReplicaSet: Unauthorized
E0708 17:31:44.182877   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Service: Unauthorized
E0708 17:31:44.184204   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.PersistentVolume: Unauthorized
E0708 17:31:44.185092   18834 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list 

➜  kubernetes systemctl status kube-scheduler|grep Active
   Active: active (running) since Sun 2018-07-08 17:28:45 CST; 22min ago

➜  kubernetes sudo netstat -lnpt|grep kube-sche
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      18834/kube-schedule

➜  kubernetes curl -s http://127.0.0.1:10251/metrics |head
# HELP apiserver_audit_event_total Counter of audit events generated and sent to the audit backend.
# TYPE apiserver_audit_event_total counter
apiserver_audit_event_total 0
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000120793
go_gc_duration_seconds{quantile="0.25"} 0.000192816
go_gc_duration_seconds{quantile="0.5"} 0.000313262
go_gc_duration_seconds{quantile="0.75"} 0.000638267
go_gc_duration_seconds{quantile="1"} 0.005454495

/etc/systemd/system/kube-scheduler.service
[Unit]
Description=Kubernetes Scheduler
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/opt/k8s/bin/kube-scheduler \
  --address=127.0.0.1 \
  --kubeconfig=/etc/kubernetes/kube-scheduler.kubeconfig \
  --leader-elect=true \
  --alsologtostderr=true \
  --logtostderr=false \
  --log-dir=/var/log/kubernetes \
  --v=2
Restart=on-failure
RestartSec=5
User=k8s

[Install]
WantedBy=multi-user.target

/etc/kubernetes/kube-scheduler.kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4RENDQXF5Z0F3SUJBZ0lVZUZydVBOQmZEQ2FsS01YT1RzcGpOWnliR293d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVTTUJBR0ExVUVDeE1KTkZCaGNtRmthV2R0TVJNd0VRWURWUVFECkV3cHJkV0psY201bGRHVnpNQjRYRFRFNE1EWXlNekUwTWprd01Gb1hEVEl6TURZeU1qRTBNamt3TUZvd2FERUwKTUFrR0ExVUVCaE1DUTA0eEVEQU9CZ05WQkFnVEIwSmxhVXBwYm1jeEVEQU9CZ05WQkFjVEIwSmxhVXBwYm1jeApEREFLQmdOVkJBb1RBMnM0Y3pFU01CQUdBMVVFQ3hNSk5GQmhjbUZrYVdkdE1STXdFUVlEVlFRREV3cHJkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUErT0w2TUhLSHBuVnAKUHdJOU1rYjdaZGd3bWp6MDU4dDNTTmpXSnVhdDJDWllod1J5MmJlY3NIVFlhekx1U0VTL0ZCcW9hbGZsUFplSwpYQzJ3Z1dzTUFkRUR5Z0hvQnprWHhveVVyVVRJaUh6YjYzR09hcWxYNzIzalZRZlVjMHg3czlGU1dJazZaczBqCmU2eElVMCtjN3RmYkU1cVgxNFA1ZTdJMUV2ZnYxODRBQndwckVNSmV6c3hCRHgwTmV0WkpQSllLMUU3RDRnUmEKZG5zWVVzNEltUHBxd3dxVS9VcUxDSzZLQmx5U3RLdzZiMDBZNk10MHZDZFpid2FBMlE2cnk3QVVlMm53bStCawpSQjQreXgwZlh2RzhNOUE5VnArbUZnV0tXMVNmdUcrNURHY0dCZnplRENqU21QSjhqeEJ3ZmJ2L0Z4Qi90djNMCjVsd0hnNUErU1FJREFRQUJvMll3WkRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIKL3dJQkFqQWRCZ05WSFE0RUZnUVVUeGxDWkJMRk1QNDd2N0pSemt5bjZ6dERockF3SHdZRFZSMGpCQmd3Rm9BVQpUeGxDWkJMRk1QNDd2N0pSemt5bjZ6dERockF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUI2NGNjY2Z5T3FvCjVkNXhXT0F0eHBMRFY1V3Y2ZEg2RDZtcXdNZE11d1AycW1JTVREV243MnhnbkRnNHA1L2xib2U3aDlGUThaR2oKQU16aDFpOGdzcXlkdEE5b0RWdDBCMy9qdTlnbk9raWRnTFpKMS95TG44WCt6NlpiMFZ1VUdKc2hEbWl5Y0d4ZwpoQTFVU3BZL016U09keHJSZDNFdVJGV2cxb0ZRbExSQUJ6VVNNZzhtTG8xanpRZ3ZBRGVJMzNLTWZYY3ZMVWdOCm91VStRV3AxRE8xak1QZWw0TzREWEs2NXI0VzMyZ0FpZFFOUjVFRkpFdUVmejFHSzVFNXRQTS9QdkIralJ5UXIKUzFpMWVrRkVQZ2NCYTNBYUFxdkx6V1VLWUt3YmVZQ1FycFNTNHRmUkFRRWFKekZsS01IdWVjTEpPUHpyWXUrcApTZzJ6bmU3c2YwOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.52.64:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:kube-scheduler
  name: system:kube-scheduler
current-context: system:kube-scheduler
kind: Config
preferences: {}
users: []

**Comment by opsnull** [comment]
/etc/kubernetes/kube-scheduler.kubeconfig
文件有误，少了 users 的相关配置。

**Comment by bwl-bwl** [comment]
[root@k8-test3 ~]#  systemctl status kube-scheduler.service -l
● kube-scheduler.service - Kubernetes Scheduler
   Loaded: loaded (/usr/lib/systemd/system/kube-scheduler.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-08-02 18:03:24 CST; 2 days ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 5089 (kube-scheduler)
    Tasks: 20
   Memory: 24.5M
   CGroup: /system.slice/kube-scheduler.service
           └─5089 /opt/kubernetes/bin/kube-scheduler --logtostderr=true --v=4 --master=https://172.16.50.93:6443 --leader-elect=true --secure-port=10259 --bind-address=172.16.50.93 --client-ca-file=/ca.pem --tls-cert-file=/kube-scheduler.pem --tls-private-key-file=/kube-scheduler-key.pem --kubeconfig=/kube-scheduler.kubeconfig --authentication-kubeconfig=/kube-scheduler.kubeconfig --authorization-kubeconfig=/kube-scheduler.kubeconfig

Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: I0805 09:45:37.835009    5089 reflector.go:161] Listing and watching *v1.StatefulSet from k8s.io/client-go/informers/factory.go:133
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: I0805 09:45:37.836210    5089 reflector.go:161] Listing and watching *v1.StorageClass from k8s.io/client-go/informers/factory.go:133
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: E0805 09:45:37.836359    5089 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StatefulSet: Unauthorized
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: E0805 09:45:37.837216    5089 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StorageClass: Unauthorized
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: I0805 09:45:37.837408    5089 reflector.go:161] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:133
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: I0805 09:45:37.838528    5089 reflector.go:161] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/client-go/informers/factory.go:133
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: E0805 09:45:37.838831    5089 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.PersistentVolume: Unauthorized
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: E0805 09:45:37.839631    5089 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PodDisruptionBudget: Unauthorized
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: I0805 09:45:37.839663    5089 reflector.go:161] Listing and watching *v1.ReplicationController from k8s.io/client-go/informers/factory.go:133
Aug 05 09:45:37 k8-test3 kube-scheduler[5089]: E0805 09:45:37.840630    5089 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ReplicationController: Unauthorized
我也遇到了相同问题，照着你的文档部署的，看来文档里面有问题

**Comment by JohnnyHL** [comment]
你的kube-scheduler组件配置怎么还配置这些证书认证、秘钥、权限干什么呢，其实可以不用配置的，“-client-ca-file=/ca.pem --tls-cert-file=/kube-scheduler.pem --tls-private-key-file=/kube-scheduler-key.pem --kubeconfig=/kube-scheduler.kubeconfig --authentication-kubeconfig=/kube-scheduler.kubeconfig --authorization-kubeconfig=/kube-scheduler.kubeconfig”这几个参数可以去掉。

**Comment by bwl-bwl** [comment]
去掉不安全吧。我调通了，你的文档有错误，语法错误
  

 

 ------------------ 原始邮件 ------------------
  发件人: "JohnnyHL"<notifications@github.com>;
 发送时间: 2019年8月26日(星期一) 晚上10:55
 收件人: "opsnull/follow-me-install-kubernetes-cluster"<follow-me-install-kubernetes-cluster@noreply.github.com>;
 抄送: "鲍文澜"<57759842@qq.com>;"Comment"<comment@noreply.github.com>;
 主题: Re: [opsnull/follow-me-install-kubernetes-cluster] kube-schedulerb日志中出现"Failed to list *v1.ReplicationController: Unauthorized" (#270)

 

你的kube-scheduler组件配置怎么还配置这些证书认证、秘钥、权限干什么呢，其实可以不用配置的，“-client-ca-file=/ca.pem --tls-cert-file=/kube-scheduler.pem --tls-private-key-file=/kube-scheduler-key.pem --kubeconfig=/kube-scheduler.kubeconfig --authentication-kubeconfig=/kube-scheduler.kubeconfig --authorization-kubeconfig=/kube-scheduler.kubeconfig”这几个参数可以去掉。

**Comment by shuming1308** [comment]
> 去掉不安全吧。我调通了，你的文档有错误，语法错误
----- 哪个地方有语法错误 ？ 我也遇到相同的问题了

**Comment by shuming1308** [comment]
> /etc/kubernetes/kube-scheduler.kubeconfig
> 文件有误，少了 users 的相关配置。
=====================================
按照你的文档，我也出现上面的问题 【报错信息完全一直】，我的kube-scheduler.kubeconfig 里面包含了users 信息： 可能是是什么原因?
cat /etc/kubernetes/kube-scheduler.kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4akNDQXE2Z0F3SUJBZ0lVUStmR1p0OFNlaFZQeDVCRUI0cUFlSGoyend3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVTTUJBR0ExVUVDeE1KTkZCaGNtRmthV2R0TVJNd0VRWURWUVFECkV3cHJkV0psY201bGRHVnpNQxxxxxxxxxxxx
    server: https://127.0.0.1:8443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:kube-scheduler
  name: system:kube-scheduler
current-context: system:kube-scheduler
kind: Config
preferences: {}
users:
- name: system:kube-scheduler
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVJRENDQXdpZ0F3SUJBZ0lVSFhzQlorN3cwT0JBMks0Ly9aTHg1cXBwdU9zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVTTxxxxxxxxxxxxx
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBd2xlN0dWVk1wcnFmeHUwcndjdjg4dERHNnR5TC8wU1BlVUIzd3pQM3RGdnQ1RkN4CmpFTkNEeWdJcTNWam9NaC9wdjMydk8vcGdVQlJoVVl3Yys5Slh0xxxxxxxxxxxxxx
