### ISSUE TITLE
prometheus的数据如何清理

### ISSUE THREAD

**Issue by liyongzhezz** [opsnull/follow-me-install-kubernetes-cluster#271]
我将prometheus的数据目录挂载到nfs的目录下，数据增长比较快，如何清理例如2天前的数据？

**Comment by opsnull** [comment]
没有直接清理的命令，但你可以调用 DeleteSeries 的 admin api，通过删除一段时间的 Series 来达到清理数据的目的。根本的还是调整 scrape period，metric 数量、大磁盘来解决。

https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-admin-apis
