### ISSUE TITLE
environment.sh中的MASTER_IP是在哪里定义的？

### ISSUE THREAD

**Issue by ghoolooloo** [opsnull/follow-me-install-kubernetes-cluster#281]
您好！
environment.sh中第27行：export KUBE_APISERVER="https://${MASTER_IP}:8443"，但是没找到MASTER_IP是在哪里定义的。只找到：export MASTER_VIP=172.27.129.253，但是三个节点中没有IP是“172.27.129.253”的节点，它是怎么冒出来的呢？

**Comment by hjgCka** [comment]
这个应该是笔误，要使用MASTER_VIP。我看了下之前的pdf文档，里面写的是MASTER_IP。
之前的kube-apiserver只有一个节点没做高可用，所以写死了一个虚拟机的IP。
但是现在做高可用的话，要填一个虚拟IP。
