### ISSUE TITLE
安装EFK时，elasticsearch-logging-0出现Init:ErrImagePull错误

### ISSUE THREAD

**Issue by hjgCka** [opsnull/follow-me-install-kubernetes-cluster#283]
通过命令
kubectl -n kube-system describe pod elasticsearch-logging-0
查看得到信息如下：
Failed to pull image "alpine:3.6"

在不能上网的情况下，这个镜像要事先push到私库中。
或者是导入到docker本地镜像。
修改文件es-statefulset.yaml第108行的镜像地址为私库地址即可。

kibana-deployment.yaml也有如此情况，不能上网时无法pull镜像。
改22行的镜像地址即可。

**Comment by opsnull** [comment]
可以的。
