### ISSUE TITLE
error

### ISSUE THREAD

**Issue by banshaotuan** [opsnull/follow-me-install-kubernetes-cluster#285]
![Uploading 图片.png…]()
提示这个错误
[k8s@node1 k8s]$ kubectl cluster-info
Kubernetes master is running at https://:8443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
[k8s@node1 k8s]$

**Comment by banshaotuan** [comment]
请问这个错误如何解决，

**Comment by opsnull** [comment]
kubectl 使用的 kubeconfig 文件配置有误。
