### ISSUE TITLE
kubeadm

### ISSUE THREAD

**Issue by songhe2136** [opsnull/follow-me-install-kubernetes-cluster#291]
老师：
我打算在 生产环境中用  kubeadm管理集群，主要考虑是部署和以后升级k8s 方便，我看大家都不推荐。原因是什么？

**Comment by opsnull** [comment]
kubeadm 搭建的集群对你来说是黑盒，封装了太多细节，不好自主控制， troubleshooting 时很不方便。

**Comment by opsnull** [comment]
kube-api 指的是 kube-apiserver 吧？你需要参考 A.浏览器访问kube-apiserver安全端口.md 文档导入证书。

**Comment by songhe2136** [comment]
谢谢！
