### ISSUE TITLE
harbor push 500

### ISSUE THREAD

**Issue by zhaop33** [opsnull/follow-me-install-kubernetes-cluster#298]
你好：
    我按照步骤安装harber，证书这些安装好后登陆都没有问题，但是上传镜像的时候会报500，
![image](https://user-images.githubusercontent.com/27794742/43502398-409ed0a2-958d-11e8-969e-f7a1d6bca84f.png)，网上也没有相关说明，我这个哪块可能配置错了？

**Comment by opsnull** [comment]
可以看看  harbor 容器的日志( 容器 /var/log/harbor 目录下)。

**Comment by zhaop33** [comment]
我找到问题了，是没有登陆，没有创建工程，没有打好tag，然后就会这样

**Comment by q1054261752** [comment]
[root@kube-node1 harbor]# docker tag nginx:1.7.9 172.27.129.105/library/nginx:1.7.9

[root@kube-node1 harbor]# docker push 172.27.129.105/library/nginx:1.7.9
