### ISSUE TITLE
Flannel貌似不支持etcd clientv3接口

### ISSUE THREAD

**Issue by finals** [opsnull/follow-me-install-kubernetes-cluster#3]
flannel启动失败，报如下错误
Error: 100: Key not found (/kubernetes) [1]

**Comment by opsnull** [comment]
flanneld 当前还是使用 v2 接口 从 etcd 获取网络配置数据，经过测试的确不支持 etcd v3 接口。

已经更新了文档，使用 v2 API 写入网络配置数据；
