### ISSUE TITLE
token.csv 是什么？根据你写的部署MASTER，然后启动发现一个Forbidden问题

### ISSUE THREAD

**Issue by istrike** [opsnull/follow-me-install-kubernetes-cluster#30]
etcd 访问正常：
 etcdctl --endpoint=https://192.168.8.130:2379 --ca-file=/etc/kubernetes/ssl/ca.pem --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem cluster-health
2017-04-20 14:20:48.202497 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2017-04-20 14:20:48.203776 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
member 261a27fe54f9e457 is healthy: got healthy result from https://192.168.8.199:2379
member 84166fb6649565fe is healthy: got healthy result from https://192.168.8.124:2379
member b6872d54339a0bdb is healthy: got healthy result from https://192.168.8.130:2379
cluster is healthy

 kubectl get nodes
Error from server (Forbidden): User "admin" cannot list nodes at the cluster scope. (get nodes)

**Comment by it2911** [comment]
token是验证编号，是一个自动的16位数字，你应该用作者的export部分先生产16位数字，进行验证。
BTW，尊重人家的辛苦更新，请用您这种敬语。

**Comment by liz1989** [comment]
我也是这样的问题，403权限不足

**Comment by opsnull** [comment]
@istrike 
> Error from server (Forbidden): User "admin" cannot list nodes at the cluster scope. (get nodes)

这是 kubectl 的权限不足，请参考 02-创建TLS证书和秘钥.md 文档创建 admin 证书，参考 04-部署Kubectl命令行工具.md 文档创建 kubectl 命令使用 kubeconfig文件；

**Comment by opsnull** [comment]
@it2911  谢谢，你懂的！！！

**Comment by opsnull** [comment]
@istrike 可以Close这个issue了么？

**Comment by istrike** [comment]
@opsnull 谢谢大师指导。我得再去找机器弄一下，kube这二种认证机制感觉都很麻烦。
