### ISSUE TITLE
证书到期问题

### ISSUE THREAD

**Issue by mohaijiang** [opsnull/follow-me-install-kubernetes-cluster#301]
刚开始生成的证书有效期只有一年，一年后证书过期，导致kubernetes api-server 6443端口服务失效，只能访问8080端口。
之前通过重新生成证书方式，重新配置整个集群的方式，使集群恢复工作，但是导致了相当长的一段时间内集群无法工作。请求有没有不中断集群服务的方式进行证书的升级？

kubernetes 版本是1.6.2，根据 https://github.com/opsnull/follow-me-install-kubernetes-cluster/tree/v1.6.2 安装

**Comment by opsnull** [comment]
1.6.2 不支持证书自动论证，到期后只能手动生成，没有好的版本。

1.8.X 以后，kube-controller-manager 可以自动为 kubelet 生成 client 和 server 证书，而且可以指定过期时间，过期前自动轮转证书，就没有这个问题了。
