### ISSUE TITLE
kubectl exec到容器报错

### ISSUE THREAD

**Issue by bigV0616** [opsnull/follow-me-install-kubernetes-cluster#302]
您好：
     我部署完coredns后测试发现kubectl不能exec到容器：
[root@kube-node3 k8s]# kubectl exec nginx -i -t -- /bin/bash
error: unable to upgrade connection: Forbidden (user=kubernetes, verb=create, resource=nodes, subresource=proxy)  这里不知道是什么问题。
    我按照步骤部署kubelet都正常，但是kube-proxy状态是start非active running状态 ， 也没有发现error信息
[root@kube-node3 k8s]# systemctl status kube-proxy
● kube-proxy.service - Kubelet Proxy Server
   Loaded: loaded (/usr/lib/systemd/system/kube-proxy.service; enabled; vendor preset: disabled)
   **Active: activating (start)** since Thu 2018-08-09 11:49:52 CST; 1min 0s ago
 Main PID: 13512 (kube-proxy)
   CGroup: /system.slice/kube-proxy.service
           ‣ 13512 /usr/bin/kube-proxy --config=/etc/kubernetes/kube-proxy.config.yaml --alsologtostderr=true --logtostderr=false --log-dir=/var/log/kubernetes --v=2

Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.737202   13512 controller_utils.go:1019] Waiting for caches to sync for endpoints config controller
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.737257   13512 config.go:202] Starting service config controller
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.737265   13512 controller_utils.go:1019] Waiting for caches to sync for service config controller
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.837366   13512 controller_utils.go:1026] Caches are synced for service config controller
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.837366   13512 controller_utils.go:1026] Caches are synced for endpoints config controller
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.837504   13512 service.go:310] Adding new service port "default/kubernetes:https" at 10.254.0.1:443/TCP
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.837535   13512 service.go:310] Adding new service port "default/my-nginx:" at 10.254.98.2:80/TCP
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.837548   13512 service.go:310] Adding new service port "kube-system/coredns:dns" at 10.254.0.2:53/UDP
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.837559   13512 service.go:310] Adding new service port "kube-system/coredns:dns-tcp" at 10.254.0.2:53/TCP
Aug 09 11:49:52 kube-node3 kube-proxy[13512]: I0809 11:49:52.837586   13512 proxier.go:637] Stale udp service kube-system/coredns:dns -> 10.254.0.2

请问这2个问题有关联么，  都是哪里的问题呢     
十分感谢

**Comment by bigV0616** [comment]
kubectl exec container 问题解决了，
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-apiserver-to-kubelet
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
      - nodes/stats
      - nodes/log
      - nodes/spec
      - nodes/metrics
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-apiserver
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-apiserver-to-kubelet
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kubernetes

但是kube-proxy不是running状态 ，目前没发现问题 😆

**Comment by xjjj064** [comment]
请问如何解决的呢？没看出来呢
