### ISSUE TITLE
Approve CSR之后状态为Issued，nodes不可见

### ISSUE THREAD

**Issue by xkai08** [opsnull/follow-me-install-kubernetes-cluster#316]
kubelet报错`kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"`
docker是用yum安装的，docker网络配置正常

**Comment by xkai08** [comment]
将kubelet.config.json中"cgroupDriver"设为"systemd"，nodes可见，csr依然带有Issued，查看kublet日志
`E0818 18:02:50.961503   21701 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
`

**Comment by gujiacheng78** [comment]
Docker可以先恢复成cgroupfs，我用的是docker-ce 18.x，默认就是cgroupfs，无须改加任何设置。
之后，可以把kubelet.config.json中的cgroupDriver再改回来。

**Comment by dianwen119** [comment]
Kubernetes 1.11.2
Docker 17.06.2.ce-1.el7.centos
Etcd 3.2.22-1.el7
Flanneld 0.10.0
插件：
Coredns
Dashboard
Heapster (influxdb、grafana)
Metrics-Server

docker 也是 yum 安装的。我也没问题啊。。你们什么情况。。。
