### ISSUE TITLE
Kubelet server 端证书不能自动 approve

### ISSUE THREAD

**Issue by khs1994** [opsnull/follow-me-install-kubernetes-cluster#326]
https://github.com/opsnull/follow-me-install-kubernetes-cluster/commit/1355073ab35a419206bd2709589bec8b5af1a627#diff-dc8265c5bf5f28e4306665e5e4bee454L428

我看作者的 v1.11.2 分支的 kubelet 执行结果没有自动生成 server 端证书。

**Comment by khs1994** [comment]
我的疑问是 server 端证书是否必须手动 approve,还是我的配置错误。

**Comment by msdemt** [comment]
@khs1994 麻烦问下，我的也是1.11.2安装的，在/etc/kubernetes里没有生成kubelet.crt和kubelet.key，请问你的有生成这两个吗？

**Comment by khs1994** [comment]
自动生成不了，get csr 然后手动 approve，具体查看手动 approve 那部分

**Comment by msdemt** [comment]
@khs1994 我的approve了之后，还是没有生成kubelet.crt和kubelet.key
![image](https://user-images.githubusercontent.com/38455670/45094402-ca558300-b14d-11e8-8805-73837336f6fd.png)

**Comment by khs1994** [comment]
没有也不影响

**Comment by dianwen119** [comment]
我就是1.11.2版本的。可以自动approve 啊。就是等的有点久。。

**Comment by khs1994** [comment]
https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/07-2.kubelet.md#%E6%89%8B%E5%8A%A8-approve-server-cert-csr
