### ISSUE TITLE
关于防火墙端口的问题

### ISSUE THREAD

**Issue by imaemo** [opsnull/follow-me-install-kubernetes-cluster#329]
我在aliyun上面开了3个服务器来安装k8s，在配置完HA的时候，ha的状态都是红色的。
我想问一下，我是不是应该在aliyun的安全组设置一个规则让 三台服务器的 6443端口都可以互相访问呢

**Comment by huruizhi** [comment]
配置完ha的时候 ha状态是红色，是因为你的master-api还没有安装。安装完master-api后，应该就正常了。

**Comment by imaemo** [comment]
@huruizhi 是的，后来就正常了。
