### ISSUE TITLE
您好，请问kubelet启动时候的pod-infra-container-image指定镜像疑问，为什么用的是pod-infrastructure而不是pause

### ISSUE THREAD

**Issue by ipchy** [opsnull/follow-me-install-kubernetes-cluster#33]
您好，以前通过kubeadm的时候安装pod-infra-container-image指定的是google的
 pause:3.0镜像，咱们这里是用redhat.com的pod-infrastructure:latest
--pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0
--pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest

**Comment by opsnull** [comment]
因为 google 的镜像仓库被墙了。pause 实际上是空镜像，用哪个都行。
