### ISSUE TITLE
flannel启动报错：Could not find valid interface matching eth0

### ISSUE THREAD

**Issue by guoqingXibei** [opsnull/follow-me-install-kubernetes-cluster#343]
### **flanneld.service**
k8s@kube-node1:/opt/k8s$ **cat /etc/systemd/system/flanneld.service**
```
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
ExecStart=/opt/k8s/bin/flanneld \
  -etcd-cafile=/etc/kubernetes/cert/ca.pem \
  -etcd-certfile=/etc/flanneld/cert/flanneld.pem \
  -etcd-keyfile=/etc/flanneld/cert/flanneld-key.pem \
  -etcd-endpoints=https://172.16.99.221:2379,https://172.16.99.74:2379,https://172.16.99.223:2379 \
  -etcd-prefix=/kubernetes/network \
  -iface=eth0
ExecStartPost=/opt/k8s/bin/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service
```

### **日志**
k8s@kube-node1:/opt/k8s$ **sudo journalctl -xe -u flanneld**
Oct 16 07:12:36 kube-node1 systemd[1]: Failed to start Flanneld overlay address etcd agent.
-- Subject: Unit flanneld.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit flanneld.service has failed.

-- The result is failed.
Oct 16 07:12:36 kube-node1 systemd[1]: flanneld.service: Unit entered failed state.
Oct 16 07:12:36 kube-node1 systemd[1]: flanneld.service: Failed with result 'exit-code'.
Oct 16 07:12:36 kube-node1 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Oct 16 07:12:36 kube-node1 systemd[1]: Stopped Flanneld overlay address etcd agent.
-- Subject: Unit flanneld.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit flanneld.service has finished shutting down.
Oct 16 07:12:36 kube-node1 systemd[1]: Starting Flanneld overlay address etcd agent...
-- Subject: Unit flanneld.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit flanneld.service has begun starting up.
Oct 16 07:12:36 kube-node1 flanneld[21736]: I1016 07:12:36.951893   21736 main.go:201] **Could not find valid interface matching eth0: error looking up interface eth0: route ip+net: no such network interface**
Oct 16 07:12:36 kube-node1 flanneld[21736]: E1016 07:12:36.951931   21736 main.go:225] **Failed to find interface to use that matches the interfaces and/or regexes provided**
Oct 16 07:12:36 kube-node1 systemd[1]: flanneld.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 07:12:36 kube-node1 systemd[1]: Failed to start Flanneld overlay address etcd agent.
-- Subject: Unit flanneld.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit flanneld.service has failed.

-- The result is failed.
Oct 16 07:12:36 kube-node1 systemd[1]: flanneld.service: Unit entered failed state.
Oct 16 07:12:36 kube-node1 systemd[1]: flanneld.service: Failed with result 'exit-code'.
Oct 16 07:12:37 kube-node1 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Oct 16 07:12:37 kube-node1 systemd[1]: Stopped Flanneld overlay address etcd agent.
-- Subject: Unit flanneld.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit flanneld.service has finished shutting down.
Oct 16 07:12:37 kube-node1 systemd[1]: flanneld.service: Start request repeated too quickly.
Oct 16 07:12:37 kube-node1 systemd[1]: Failed to start Flanneld overlay address etcd agent.
-- Subject: Unit flanneld.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit flanneld.service has failed.

-- The result is failed.

**Comment by guoqingXibei** [comment]
已解决。

查看机器网卡信息
k8s@kube-node1:/opt/k8s$ i**fconfig**
```
ens3      Link encap:Ethernet  HWaddr 02:c5:8a:bd:2a:7c
          inet addr:172.16.99.221  Bcast:172.16.99.255  Mask:255.255.255.0
          inet6 addr: fe80::c5:8aff:febd:2a7c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:963580 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1412851 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:349262822 (349.2 MB)  TX bytes:483643524 (483.6 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:8670 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8670 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:37364573 (37.3 MB)  TX bytes:37364573 (37.3 MB)
```
发现，并没有eth0网卡，因此将教程中的eth0替换成我自己机器上的ens3网卡即可。

将
```
source /opt/k8s/bin/environment.sh
export IFACE=eth0
cat > flanneld.service << EOF
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
ExecStart=/opt/k8s/bin/flanneld \\
  -etcd-cafile=/etc/kubernetes/cert/ca.pem \\
  -etcd-certfile=/etc/flanneld/cert/flanneld.pem \\
  -etcd-keyfile=/etc/flanneld/cert/flanneld-key.pem \\
  -etcd-endpoints=${ETCD_ENDPOINTS} \\
  -etcd-prefix=${FLANNEL_ETCD_PREFIX} \\
  -iface=${IFACE}
ExecStartPost=/opt/k8s/bin/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service
EOF
```
改为
```
source /opt/k8s/bin/environment.sh
export IFACE=ens3
cat > flanneld.service << EOF
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
ExecStart=/opt/k8s/bin/flanneld \\
  -etcd-cafile=/etc/kubernetes/cert/ca.pem \\
  -etcd-certfile=/etc/flanneld/cert/flanneld.pem \\
  -etcd-keyfile=/etc/flanneld/cert/flanneld-key.pem \\
  -etcd-endpoints=${ETCD_ENDPOINTS} \\
  -etcd-prefix=${FLANNEL_ETCD_PREFIX} \\
  -iface=${IFACE}
ExecStartPost=/opt/k8s/bin/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service
EOF
```

**Comment by zuihou** [comment]
赞！！！

**Comment by taojunyu** [comment]
老哥厉害了，我找了半天也找不到在哪改网卡，没想到在全局里就设置了，多谢！！！
