### ISSUE TITLE
API Server 配置中etcd 配置是否是错误的？

### ISSUE THREAD

**Issue by xiaojiaqi** [opsnull/follow-me-install-kubernetes-cluster#347]
API Server 配置中
这个部分
  --etcd-cafile=/etc/kubernetes/cert/ca.pem \\
  --etcd-certfile=/etc/kubernetes/cert/kubernetes.pem \\
  --etcd-keyfile=/etc/kubernetes/cert/kubernetes-key.pem \\

我认为应该是etcd.pem  和 etcd-key.pem 才对。 但是我并不确定。请检查

**Comment by opsnull** [comment]
不是的。

这是 kube-apiserver 访问 etcd 时使用的 client 证书。

etcd.pem 和 etcd-key.pem 是 etcd server 使用的证书。
