### ISSUE TITLE
按照步骤部署到 etcd 部分后发现问题

### ISSUE THREAD

**Issue by hy05190134** [opsnull/follow-me-install-kubernetes-cluster#352]
error "remote error: tls: bad certificate", ServerName ""， 是不是证书生成的有问题呀？

**Comment by sunmoondeer** [comment]
我也是这个问题，请问你解决了吗

**Comment by wu-andrew** [comment]
请问解决了吗

**Comment by wu-andrew** [comment]
我的是CA证书问题

**Comment by shawn-yu** [comment]
按手册说的，证书创建的时候节点IP要替换成你自己环境里的IP
•hosts 字段指定授权使用该证书的 etcd 节点 IP 或域名列表，需要将 etcd 集群的三个节点 IP 都列在其中；
