### ISSUE TITLE
kube-controller-manager安装成功运行报错User "system:anonymous" cannot get path /metrics

### ISSUE THREAD

**Issue by RuiBaiXYZ** [opsnull/follow-me-install-kubernetes-cluster#366]
kube-controller-manager安装成功运行后，报错如下：
User "system:anonymous" cannot get path /metrics

请帮忙解决。谢谢

各配置文件详细内容如下：
**"cat /usr/lib/systemd/system/kube-controller-manager.service"**
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/opt/kubernetes/kube-controller-manager \
  --port=0 \
  --secure-port=10252 \
  --bind-address=127.0.0.1 \
  --kubeconfig=/etc/kubernetes/cert/kube-controller-manager.kubeconfig \
  --service-cluster-ip-range=18.80.0.0/16 \
  --cluster-name=kubernetes \
  --cluster-signing-cert-file=/etc/kubernetes/cert/ca.pem \
  --cluster-signing-key-file=/etc/kubernetes/cert/ca-key.pem \
  --root-ca-file=/etc/kubernetes/cert/ca.pem \
  --service-account-private-key-file=/etc/kubernetes/cert/ca-key.pem \
  --leader-elect=true \
  --feature-gates=RotateKubeletServerCertificate=true \
  --controllers=*,bootstrapsigner,tokencleaner \
  --horizontal-pod-autoscaler-use-rest-clients=true \
  --horizontal-pod-autoscaler-sync-period=10s \
  --tls-cert-file=/etc/kubernetes/cert/kube-controller-manager.pem \
  --tls-private-key-file=/etc/kubernetes/cert/kube-controller-manager-key.pem \
  --use-service-account-credentials=true \
  --alsologtostderr=true \
  --logtostderr=false \
  --log-dir=/var/log/kubernetes \
  --v=2
Restart=on
Restart=on-failure
RestartSec=5
User=root

[Install]
WantedBy=multi-user.target

**"cat /usr/lib/systemd/system/kube-apiserver.service"**
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=network.target

[Service]
ExecStart=/opt/kubernetes/kube-apiserver \
  --enable-admission-plugins=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \
  --anonymous-auth=false \
  --experimental-encryption-provider-config=/etc/kubernetes/cert/encryption-config.yaml \
  --advertise-address=192.168.229.171 \
  --bind-address=192.168.229.171 \
  --insecure-port=0 \
  --authorization-mode=Node,RBAC \
  --runtime-config=api/all \
  --enable-bootstrap-token-auth \
  --service-cluster-ip-range=18.80.0.0/16 \
  --service-node-port-range=30000-32766 \
  --tls-cert-file=/etc/kubernetes/cert/kubernetes.pem \
  --tls-private-key-file=/etc/kubernetes/cert/kubernetes-key.pem \
  --client-ca-file=/etc/kubernetes/cert/ca.pem \
  --kubelet-client-certificate=/etc/kubernetes/cert/kubernetes.pem \
  --kubelet-client-key=/etc/kubernetes/cert/kubernetes-key.pem \
  --service-account-key-file=/etc/kubernetes/cert/ca-key.pem \
  --etcd-cafile=/etc/kubernetes/cert/ca.pem \
  --etcd-certfile=/etc/kubernetes/cert/kubernetes.pem \
  --etcd-keyfile=/etc/kubernetes/cert/kubernetes-key.pem \
  --etcd-servers=https://192.168.229.161:2379,https://192.168.229.162:2379,https://192.168.229.163:2379 \
  --enable-swagger-ui=true \
  --allow-privileged=true \
  --apiserver-count=3 \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/log/kube-apiserver-audit.log \
  --event-ttl=1h \
  --alsologtostderr=true \
  --logtostderr=false \
  --log-dir=/var/log/kubernetes \
  --v=2
Restart=on-failure
RestartSec=5
Type=notify
User=root
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target

 ```
for HNAME in ${KMASTER_NAMES[@]}
>   do
>     echo ">>> ${HNAME}"
>     ssh ${HNAME} "systemctl status kube-apiserver | grep 'Active'"
>   done
```
>>> km01
   Active: active (running) since Fri 2018-11-30 08:25:30 CST; 5h 19min ago
>>> km02
   Active: active (running) since Fri 2018-11-30 08:25:18 CST; 5h 19min ago
>>> km03
   Active: active (running) since Fri 2018-11-30 08:25:06 CST; 5h 19min ago

```
for HNAME in ${KMASTER_NAMES[@]}
>   do
>     echo ">>> ${HNAME}"
>     ssh ${HNAME} "systemctl status kube-controller-manager|grep Active"
>   done
```
>>> km01
   Active: active (running) since Fri 2018-11-30 08:25:12 CST; 5h 20min ago
>>> km02
   Active: active (running) since Fri 2018-11-30 08:25:01 CST; 5h 20min ago
>>> km03
   Active: active (running) since Fri 2018-11-30 08:24:47 CST; 5h 20min ago

`ssh km01 "curl -s --cacert /etc/kubernetes/cert/ca.pem https://127.0.0.1:10252/metrics | head"`
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {

**Comment by dianwen119** [comment]
请确保下面几点
1、metrics-server-csr.json 中CN的名字，与apiserver.service 配置中 --requestheader-allowed-names相对应
# cat metrics-server-csr.json 
{
  "CN": "aggregator",
  "hosts": [],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "CN",
      "ST": "GuangZhou",
      "L": "GuangZhou",
      "O": "k8s",
      "OU": "Bit"
    }
  ]
}

2、kube-controller-manager.service加了一行你没有 --horizontal-pod-autoscaler-use-rest-clients=true
[Service]
ExecStart=/opt/k8s/bin/kube-controller-manager \
  --port=10252 \
  --bind-address=127.0.0.1 \
  --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig \
  --service-cluster-ip-range=10.254.0.0/16 \
  --cluster-name=kubernetes \
  --cluster-signing-cert-file=/etc/kubernetes/cert/ca.pem \
  --cluster-signing-key-file=/etc/kubernetes/cert/ca-key.pem \
  --experimental-cluster-signing-duration=8760h \
  --root-ca-file=/etc/kubernetes/cert/ca.pem \
  --service-account-private-key-file=/etc/kubernetes/cert/ca-key.pem \
  --leader-elect=true \
  --feature-gates=RotateKubeletServerCertificate=true \
  --controllers=*,bootstrapsigner,tokencleaner \
  --horizontal-pod-autoscaler-use-rest-clients=true \
  --horizontal-pod-autoscaler-sync-period=10s \
  --tls-cert-file=/etc/kubernetes/cert/kube-controller-manager.pem \
  --tls-private-key-file=/etc/kubernetes/cert/kube-controller-manager-key.pem \
  --use-service-account-credentials=true \
  --alsologtostderr=true \
  --logtostderr=false \
  --log-dir=/var/log/kubernetes \
  --v=2 \
  --horizontal-pod-autoscaler-use-rest-clients=true

3、kube-apiserver.service 如下部分，在最后加了8行。你也没有。
[Service]
ExecStart=/opt/k8s/bin/kube-apiserver \
  --enable-admission-plugins=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \
  --anonymous-auth=false \
  --experimental-encryption-provider-config=/etc/kubernetes/encryption-config.yaml \
  --advertise-address=192.168.11.11 \
  --bind-address=192.168.11.11 \
  --insecure-port=0 \
  --authorization-mode=Node,RBAC \
  --runtime-config=api/all \
  --enable-bootstrap-token-auth=true \
  --service-cluster-ip-range=10.254.0.0/16 \
  --service-node-port-range=8400-9000 \
  --tls-cert-file=/etc/kubernetes/cert/kubernetes.pem \
  --tls-private-key-file=/etc/kubernetes/cert/kubernetes-key.pem \
  --client-ca-file=/etc/kubernetes/cert/ca.pem \
  --kubelet-client-certificate=/etc/kubernetes/cert/kubernetes.pem \
  --kubelet-client-key=/etc/kubernetes/cert/kubernetes-key.pem \
  --service-account-key-file=/etc/kubernetes/cert/ca-key.pem \
  --etcd-cafile=/etc/etcd/ssl/etcd-ca.pem \
  --etcd-certfile=/etc/etcd/ssl/etcd.pem \
  --etcd-keyfile=/etc/etcd/ssl/etcd-key.pem \
  --etcd-servers=https://192.168.11.11:2379,https://192.168.11.12:2379 \
  --storage-backend=etcd3 \
  --enable-swagger-ui=true \
  --allow-privileged=true \
  --apiserver-count=3 \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/log/kube-apiserver-audit.log \
  --event-ttl=1h \
  --alsologtostderr=true \
  --logtostderr=false \
  --log-dir=/var/log/kubernetes \
  --v=2 \
  --requestheader-client-ca-file=/etc/kubernetes/cert/ca.pem \
  --requestheader-allowed-names=aggregator \
  --requestheader-username-headers=X-Remote-User \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-extra-headers-prefix=X-Remote-Extra- \
  --proxy-client-cert-file=/etc/kubernetes/cert/metrics-server.pem \
  --proxy-client-key-file=/etc/kubernetes/cert/metrics-server-key.pem \
  --runtime-config=api/all=true

**Comment by yangmingqi218** [comment]
解决了么

**Comment by goith** [comment]
请问这个怎么解决的？

**Comment by RuiBaiXYZ** [comment]
> 
> 
> 请问这个怎么解决的？


解决了这个问题。按照 dianwen119 的提示，确保一致性就可以解决了。
他这个文档中有些顺序是需要调整的，不能完全按照文档中的顺序来做。

**Comment by Kingchan230** [comment]
正确顺序应该如何？

**Comment by opsnull** [comment]
部署 metrics-server 后可以解决该问题。

**Comment by opsnull** [comment]
文档顺序是没有问题的。

metrics-server 是一个插件，非必选的，所以放到后面插架章节中。
