### ISSUE TITLE
kuber-apiserver 配置问题

### ISSUE THREAD

**Issue by seils1984** [opsnull/follow-me-install-kubernetes-cluster#373]
kube-apiserver的配置文件中已经使用了 --enable-bootstrap-token-auth
为什么还需要配置--kubelet-client-certificate 以及--kubelet-client-key

**Comment by opsnull** [comment]
因为 kubelet 只开启了需要认证授权的 https 端口，kube-apiserver 访问 kubelet API 时需要使用证书认证。
