### ISSUE TITLE
启动kube-controller-manager成功，但是校验metrics失败

### ISSUE THREAD

**Issue by navychi** [opsnull/follow-me-install-kubernetes-cluster#375]
curl -s --cacert /etc/kubernetes/cert/ca.pem https://127.0.0.1:10252/metrics |head
校验失败，是否需要先执行（09-4.metrics-server插件），再启动kube-controller-manager

**Comment by goith** [comment]
> curl -s --cacert /etc/kubernetes/cert/ca.pem https://127.0.0.1:10252/metrics |head
> 校验失败，是否需要先执行（09-4.metrics-server插件），再启动kube-controller-manager

请问解决了吗 ? 是什么原因造成的，怎么解决呢？

**Comment by BigAlanSun** [comment]
https://github.com/opsnull/follow-me-install-kubernetes-cluster/issues/366 这个issue的dianwen119给了解决方法

**Comment by opsnull** [comment]
是的，部署 metrics-server 后解决该问题。
