### ISSUE TITLE
etcd集群 启动失败

### ISSUE THREAD

**Issue by ibit2** [opsnull/follow-me-install-kubernetes-cluster#387]
`
Jan 29 17:21:03 kube-node1 systemd[1]: Failed to start Etcd Server.
Jan 29 17:21:03 kube-node1 systemd[1]: Unit etcd.service entered failed state.
Jan 29 17:21:03 kube-node1 systemd[1]: etcd.service failed.
Jan 29 17:21:08 kube-node1 systemd[1]: etcd.service holdoff time over, scheduling restart.
Jan 29 17:21:08 kube-node1 systemd[1]: Stopped Etcd Server.
Jan 29 17:21:08 kube-node1 systemd[1]: Starting Etcd Server...
Jan 29 17:21:08 kube-node1 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Jan 29 17:21:08 kube-node1 systemd[1]: Failed to start Etcd Server.
Jan 29 17:21:08 kube-node1 systemd[1]: Unit etcd.service entered failed state.
Jan 29 17:21:08 kube-node1 systemd[1]: etcd.service failed.
Jan 29 17:21:14 kube-node1 systemd[1]: etcd.service holdoff time over, scheduling restart.
Jan 29 17:21:14 kube-node1 systemd[1]: Stopped Etcd Server.
Jan 29 17:21:14 kube-node1 systemd[1]: Starting Etcd Server...
Jan 29 17:21:14 kube-node1 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Jan 29 17:21:14 kube-node1 systemd[1]: Failed to start Etcd Server.
Jan 29 17:21:14 kube-node1 systemd[1]: Unit etcd.service entered failed state.
Jan 29 17:21:14 kube-node1 systemd[1]: etcd.service failed.

`

**Comment by opsnull** [comment]
日志信息看不出来失败原因。可以将 etcd.service 中启动命令和参数贴到终端中手动执行，看看出错信息。

**Comment by ibit2** [comment]
@opsnull 我两台主机是公网的，内网不互通，可以搭建吗

**Comment by opsnull** [comment]
可以的。flanneld 可以使用公网。
