### ISSUE TITLE
kubectl describe pod elasticsearch-logging-1 --namespace=kube-system

### ISSUE THREAD

**Issue by q1054261752** [opsnull/follow-me-install-kubernetes-cluster#389]
Events:
  Type     Reason                 Age                From                 Message
  ----     ------                 ----               ----                 -------
  Normal   Scheduled              1h                 default-scheduler    Successfully assigned elasticsearch-logging-1 to kube-node3
  Normal   SuccessfulMountVolume  1h                 kubelet, kube-node3  MountVolume.SetUp succeeded for volume "elasticsearch-logging"
  Normal   SuccessfulMountVolume  1h                 kubelet, kube-node3  MountVolume.SetUp succeeded for volume "elasticsearch-logging-token-skfsd"
  Normal   Pulled                 1h                 kubelet, kube-node3  Container image "alpine:3.6" already present on machine
  Normal   Created                1h                 kubelet, kube-node3  Created container
  Normal   Started                1h                 kubelet, kube-node3  Started container
  Warning  FailedMount            1h                 kubelet, kube-node3  MountVolume.SetUp failed for volume "elasticsearch-logging-token-skfsd" : Get https://172.27.129.253:8443/api/v1/namespaces/kube-system/secrets/elasticsearch-logging-token-skfsd: read tcp 172.27.129.112:48638->172.27.129.253:8443: use of closed network connection
  Warning  FailedMount            1h                 kubelet, kube-node3  MountVolume.SetUp failed for volume "elasticsearch-logging-token-skfsd" : Get https://172.27.129.253:8443/api/v1/namespaces/kube-system/secrets/elasticsearch-logging-token-skfsd: net/http: TLS handshake timeout
  Warning  FailedMount            1h                 kubelet, kube-node3  MountVolume.SetUp failed for volume "elasticsearch-logging-token-skfsd" : Get https://172.27.129.253:8443/api/v1/namespaces/kube-system/secrets/elasticsearch-logging-token-skfsd: read tcp 172.27.129.112:48960->172.27.129.253:8443: use of closed network connection
  Normal   Created                1h (x4 over 1h)    kubelet, kube-node3  Created container
  Normal   Started                1h (x4 over 1h)    kubelet, kube-node3  Started container
  Warning  FailedMount            1h                 kubelet, kube-node3  MountVolume.SetUp failed for volume "elasticsearch-logging-token-skfsd" : Get https://172.27.129.253:8443/api/v1/namespaces/kube-system/secrets/elasticsearch-logging-token-skfsd: read tcp 172.27.129.112:49662->172.27.129.253:8443: use of closed network connection
  Normal   Pulled                 1h (x5 over 1h)    kubelet, kube-node3  Container image "longtds/elasticsearch:v5.6.4" already present on machine
  Warning  BackOff                1h (x34 over 1h)   kubelet, kube-node3  Back-off restarting failed container
  Normal   SuccessfulMountVolume  1h                 kubelet, kube-node3  MountVolume.SetUp succeeded for volume "elasticsearch-logging"
  Normal   SuccessfulMountVolume  1h                 kubelet, kube-node3  MountVolume.SetUp succeeded for volume "elasticsearch-logging-token-skfsd"
  Normal   SandboxChanged         1h                 kubelet, kube-node3  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                 1h                 kubelet, kube-node3  Container image "alpine:3.6" already present on machine
  Normal   Created                1h                 kubelet, kube-node3  Created container
  Normal   Started                1h                 kubelet, kube-node3  Started container
  Warning  FailedMount            1h                 kubelet, kube-node3  MountVolume.SetUp failed for volume "elasticsearch-logging-token-skfsd" : Get https://172.27.129.253:8443/api/v1/namespaces/kube-system/secrets/elasticsearch-logging-token-skfsd: read tcp 172.27.129.112:53538->172.27.129.253:8443: use of closed network connection
  Normal   Started                1h (x3 over 1h)    kubelet, kube-node3  Started container
  Warning  FailedMount            59m                kubelet, kube-node3  MountVolume.SetUp failed for volume "elasticsearch-logging-token-skfsd" : Get https://172.27.129.253:8443/api/v1/namespaces/kube-system/secrets/elasticsearch-logging-token-skfsd: read tcp 172.27.129.112:54364->172.27.129.253:8443: use of closed network connection
  Normal   Created                58m (x4 over 1h)   kubelet, kube-node3  Created container
  Normal   Pulled                 7m (x14 over 1h)   kubelet, kube-node3  Container image "longtds/elasticsearch:v5.6.4" already present on machine
  Warning  BackOff                2m (x233 over 1h)  kubelet, kube-node3  Back-off restarting failed container

elasticsearch-logging-1 不停的重新启动，CrashLoopBackOff

**Comment by opsnull** [comment]
看起来是访问 apiserver vip 失败了。
