### ISSUE TITLE
碰到的几个问题

### ISSUE THREAD

**Issue by mylife6585** [opsnull/follow-me-install-kubernetes-cluster#39]
1、容器网络不通
原因：node 节点 iptables forward链设置不对
解决：iptables -P FORWARD ACCEPT
2、监控、elk 不能在dashboard展现
原因：master没装flannel，没法与pod通信
解决：master安装flannel

**Comment by opsnull** [comment]
多谢分享。
第一个问题再文档里有说明。
第二个是你在一台机器上同时部署master和node组件，所以需要flanneld；
