### ISSUE TITLE
如何新增node节点

### ISSUE THREAD

**Issue by kernelsky** [opsnull/follow-me-install-kubernetes-cluster#394]
按照教程搭建了3个节点互为主备，怎么添加新的node节点进来呢？

**Comment by wangxyd** [comment]
kubelet默认会自动注册节点到kube-apiserver（kubelet的--register-node=true），也就是说在节点上 启动相同配置的kubelet进程 就可以作为node节点加入集群，当然还要配置好flannel、kube-proxy和docker哦
