### ISSUE TITLE
自动 approve CSR 有问题

### ISSUE THREAD

**Issue by dmanbu** [opsnull/follow-me-install-kubernetes-cluster#399]
![image](https://user-images.githubusercontent.com/10231091/53479947-2376f180-3ab5-11e9-91b9-04ede0be838b.png)

图中 csr-44cjc 是我手动过的，其他的csr都不行

刚翻了下github，发现了这个
https://github.com/kubernetes/kubernetes/issues/73356

说的是自动签署证书被删除了，请问有什么办法可以解决？

**Comment by dmanbu** [comment]
@opsnull  能帮忙解决下么？

**Comment by opsnull** [comment]
你这个是哪个 K8S 版本？
1.10 和 1.11 应该是不支持自动 approve kubelet server 的证书的，需要手动approve；
最新的文档 1.12 支持自动 approve。

**Comment by dmanbu** [comment]
> 你这个是哪个 K8S 版本？
> 1.10 和 1.11 应该是不支持自动 approve kubelet server 的证书的，需要手动approve；
> 最新的文档 1.12 支持自动 approve。

我总共试用了 1.10.4、1.10.13、1.12.3、1.12.6 共四个版本的k8s
其中 1.10.4、1.10.13 两个版本可以正常使用自动批准kubelet服务器证书
而 1.12.3、1.12.6 这两个版本并不成功

翻阅了下文档，说的是基于安全原因，在新版本中删除了自动批准，但可以通过
To use RotateKubeletServerCertificate operators need to run a custom approving controller 的方式实现自动批准，但不知道该怎么做？

**Comment by zhengqisong** [comment]
To use RotateKubeletServerCertificate operators need to run a custom approving controller，就是自己写一个controller监听csr，当有csr时，通过自己的controller程序进行approve

**Comment by horis233** [comment]
> > 你这个是哪个 K8S 版本？
> > 1.10 和 1.11 应该是不支持自动 approve kubelet server 的证书的，需要手动approve；
> > 最新的文档 1.12 支持自动 approve。
> 
> 我总共试用了 1.10.4、1.10.13、1.12.3、1.12.6 共四个版本的k8s
> 其中 1.10.4、1.10.13 两个版本可以正常使用自动批准kubelet服务器证书
> 而 1.12.3、1.12.6 这两个版本并不成功
> 
> 翻阅了下文档，说的是基于安全原因，在新版本中删除了自动批准，但可以通过
> To use RotateKubeletServerCertificate operators need to run a custom approving controller 的方式实现自动批准，但不知道该怎么做？
需要自己来写controller 来 approve CSR。

**Comment by invidian** [comment]
https://github.com/kontena/kubelet-rubber-stamp can be used for that. See https://blog.kontena.io/fully-automatic-certificate-bootstrapping-for-kubelets/ for more details.
