### ISSUE TITLE
metrics-server 部署有错

### ISSUE THREAD

**Issue by Kingchan230** [opsnull/follow-me-install-kubernetes-cluster#400]
根据文档编辑metrics-server-deployment.yaml ，在这个yaml中，并没有- -- source= *****的参数，如果强行添加，会报错.
![image](https://user-images.githubusercontent.com/22443359/53538162-80bb8300-3b47-11e9-9352-f701f4f7029f.png)
参考其他文档在次yaml中添加- --kubelet-insecure-tls
      --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
运行也会出现别的错误，提示Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io).该如何正确部署呢？

**Comment by zuihou** [comment]
同问

**Comment by sinerxx** [comment]
同问

**Comment by opsnull** [comment]
metrics-server 版本的问题，请查看最新的文档。
