### ISSUE TITLE
没有nginx的节点 kube-controller-manager.启动不了

### ISSUE THREAD

**Issue by guijunchen** [opsnull/follow-me-install-kubernetes-cluster#402]
你好  没有nginx的节点 kube-controller-manager.启动不了
原因是： Get https://127.0.0.1:8443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 127.0.0.1:8443: connect: connection refused

这个连接不上 一直在重启

**Comment by kernelsky** [comment]
s所有节点都不熟nginx就可以了
