### ISSUE TITLE
 no kind "KubeSchedulerConfiguration" is registered 

### ISSUE THREAD

**Issue by guijunchen** [opsnull/follow-me-install-kubernetes-cluster#404]
我用这个教程部署kubernetesv13.3 在启动kube-scheduler集群是报错，百度实在找不到答案。错误原因如下：
22662 serving.go:318] Generated self-signed cert in-memory
k8s-master kube-scheduler[22662]: no kind "KubeSchedulerConfiguration" is registered for version "componentconfig/v1alpha1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:29"

**Comment by guijunchen** [comment]
root@k8s-node02:~# cat /etc/kubernetes/kube-scheduler.yaml
apiVersion: componentconfig/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true

这个文件的内容

**Comment by opsnull** [comment]
本教程部署的是 kubernetes v1.12.3 版本，对于 v13.3 不一定适用。
具体你反馈的问题，是 v13.0 的 break change，参考：https://kubernetes.io/docs/setup/release/notes/#urgent-upgrade-notes

**Comment by yanzuo0609** [comment]
我遇到了相同的问题，版本和文档里的一致。
May 18 15:53:09 m7-autocv-gpu02 kube-scheduler[35073]: no kind "Config" is registered for version "v1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:29"

**Comment by yanzuo0609** [comment]
May 18 15:59:56 m7-autocv-gpu02 kube-scheduler[36596]: no kind "KubeSchedulerConfiguration" is registered for version "componentconfig/v1alpha1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:29"
