### ISSUE TITLE
08_验证集群功 => curl 请求被拒绝:curl: (7) Failed connect to 10.254.136.26:80; 拒绝连接

### ISSUE THREAD

**Issue by songzhangyu** [opsnull/follow-me-install-kubernetes-cluster#408]
kubectl get svc |grep dnsutils-ds
dnsutils-ds   NodePort    10.254.136.26   <none>        80:30431/TCP   53m

kubectl get pods  -o wide
NAME                READY   STATUS    RESTARTS   AGE   IP              NODE    NOMINATED NODE   READINESS GATES
dnsutils-ds-b7vlq   1/1     Running   1          82m   192.170.32.2    node3   <none>           <none>
dnsutils-ds-cvm9p   1/1     Running   1          82m   192.170.248.2   node2   <none>           <none>
dnsutils-ds-ncjwh   1/1     Running   1          83m   192.170.192.2   node1   <none>           <none>

**Comment by opsnull** [comment]
@songzhangyu 以 fix，参考最新文档验证。
