### ISSUE TITLE
metrics-server-v0.3.1正常启动但是服务不可用kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes" | jq

### ISSUE THREAD

**Issue by q1054261752** [opsnull/follow-me-install-kubernetes-cluster#409]
[root@kube-node1 metrics-server]# kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes" | jq
Error from server (ServiceUnavailable): the server is currently unable to handle the request

**Comment by q1054261752** [comment]
[root@kube-node1 metrics-server]# kubectl get pods -n kube-system |grep metrics-server
metrics-server-v0.3.1-757b58b45f-kq75p   2/2     Running   0          36m

**Comment by q1054261752** [comment]
[root@kube-node1 metrics-server]# kubectl top node
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
[root@kube-node1 metrics-server]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by songzhangyu** [comment]
怎么配置的呢，我一直没搞定；

unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:node1: unable to fetch metrics from Kubelet node1 (192.168.148.133): Get http://192.168.148.133:10255/stats/summary/: dial tcp 192.168.148.133:10255: connect: connection refused, unable to fully scrape metrics from source kubelet_summary:node2: unable to fetch metrics from Kubelet node2 (192.168.148.134): Get http://192.168.148.134:10255/stats/summary/: dial tcp 192.168.148.134:10255: connect: connection refused, unable to fully scrape metrics from source kubelet_summary:node3: unable to fetch metrics from Kubelet node3 (192.168.148.135): Get http://192.168.148.135:10255/stats/summary/: dial tcp 192.168.148.135:10255: connect: connection refused]

**Comment by WrangLer117708** [comment]
我也没搞定，但是我用kubeadm部署的话就ok  二进制不行 不知道问题出在哪了

**Comment by WrangLer117708** [comment]
> 怎么配置的呢，我一直没搞定；
> 
> unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:node1: unable to fetch metrics from Kubelet node1 (192.168.148.133): Get http://192.168.148.133:10255/stats/summary/: dial tcp 192.168.148.133:10255: connect: connection refused, unable to fully scrape metrics from source kubelet_summary:node2: unable to fetch metrics from Kubelet node2 (192.168.148.134): Get http://192.168.148.134:10255/stats/summary/: dial tcp 192.168.148.134:10255: connect: connection refused, unable to fully scrape metrics from source kubelet_summary:node3: unable to fetch metrics from Kubelet node3 (192.168.148.135): Get http://192.168.148.135:10255/stats/summary/: dial tcp 192.168.148.135:10255: connect: connection refused]

请问下 这个问题解决了吗
