### ISSUE TITLE
并没有关于VIP的配置，最后dashboard里面的VIP172.27.128.252:8443不知道从哪里来的

### ISSUE THREAD

**Issue by wangzhitao81** [opsnull/follow-me-install-kubernetes-cluster#411]
我翻过了所有的文件，并没有关于虚ip的配置，也没有关于keepalived的分发和配置
，nginx配置的是127.0.0.1
不知道最后dashboard的虚ip是怎么来の

**Comment by wangzhitao81** [comment]
在 [06-2.apiserver集群.md#创建加密配置文件-检查集群信息](https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/06-2.apiserver%E9%9B%86%E7%BE%A4.md#%E5%88%9B%E5%BB%BA%E5%8A%A0%E5%AF%86%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)
执行 kubectl cluster-info的时候
返回的还是 

> Kubernetes master is running at https://127.0.0.1:8443

**Comment by opsnull** [comment]
@wangzhitao81 最新文档已经 fix 了这个笔误，给了查看方式。
