### ISSUE TITLE
sed 语法错误

### ISSUE THREAD

**Issue by liurui2014** [opsnull/follow-me-install-kubernetes-cluster#413]
在https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/07-1.docker.md 中分发 systemd unit 文件到所有 worker 机器内容中
`sed -i -e "s/##DOCKER_DIR##/${DOCKER_DIR}/" docker.service` 语法错误。
```
# sed -i -e "s/##DOCKER_DIR##/${DOCKER_DIR}/" docker.service
sed: -e expression #1, char 19: unknown option to `s'
```
应该是
```
# sed -i -e 's/##DOCKER_DIR##/${DOCKER_DIR}/' docker.service
```

**Comment by songzhangyu** [comment]
因为DOCKER_DIR 含有'/' 报错，把分隔符换成 | 就好了；单引号不解析变量，结果不对。
