### ISSUE TITLE
kube-scheduler启不来

### ISSUE THREAD

**Issue by sanger89** [opsnull/follow-me-install-kubernetes-cluster#414]
![image](https://user-images.githubusercontent.com/35362585/54503064-88ad5c80-4968-11e9-891c-e4a0480f96d8.png)

**Comment by songzhangyu** [comment]
![image](https://user-images.githubusercontent.com/16074583/54503208-20ab4600-4969-11e9-8584-fcc347bf350c.png)
这里写得很清楚啊

**Comment by sanger89** [comment]
> ![image](https://user-images.githubusercontent.com/16074583/54503208-20ab4600-4969-11e9-8584-fcc347bf350c.png)
> 这里写得很清楚啊

![image](https://user-images.githubusercontent.com/35362585/54503727-83054600-496b-11e9-9a05-edf7ef403702.png)
然后报这个错了。。

**Comment by sanger89** [comment]
已解决，证书问题  重新制证  
查证 kubectl config view --kubeconfig=/usr/local/kubernetes/etc/kube-scheduler.kubeconfig 确认后解决
