### ISSUE TITLE
sudo netstat -lnpt|grep kube-sche中ip为:::

### ISSUE THREAD

**Issue by F36** [opsnull/follow-me-install-kubernetes-cluster#418]
在步骤6-4部署高可用 kube-scheduler 集群的最后，查看输出的 metric：
[root@model-graph-dev01 work]# sudo netstat -lnpt|grep kube-sche
tcp6       0      **0 :::10251                :::***                    LISTEN      24740/kube-schedule

其它项都是正常的，请问这是为什么？

**Comment by opsnull** [comment]
正常的。监听 0.0.0.0 时就是这种情况。
