### ISSUE TITLE
/etc/systemd/system/kubelet.service 中漏加 "\\"

### ISSUE THREAD

**Issue by zhaoshouzhong** [opsnull/follow-me-install-kubernetes-cluster#422]
![image](https://user-images.githubusercontent.com/22735215/54890258-7f317080-4ee3-11e9-8da1-5b91e64a59ad.png)
/etc/systemd/system/kubelet.service的
--pod-infra-container-image=registry.cn-beijing.aliyuncs.com/k8s_images/pause-amd64:3.1
后面需要加 “\\”

**Comment by neighbour-oldhuang** [comment]
嗯 就是这里漏掉了会导致 kubectl get csr 提示 no resource found
