### ISSUE TITLE
06-3.controller-manager集群 这一节部署不成功

### ISSUE THREAD

**Issue by kongkaiping** [opsnull/follow-me-install-kubernetes-cluster#426]
kube-controller-manager[29501]: invalid configuration: no configuration has been provided
--------------
都按照步骤来的, 是不是文档上有小问题?

**Comment by kongkaiping** [comment]
进一步跟踪错误日志是:
E0402 17:33:46.271499   29159 leaderelection.go:252] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:8443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: dial tcp 127.0.0.1:8443: connect: connection refused

**Comment by neighbour-oldhuang** [comment]
> 进一步跟踪错误日志是:
> E0402 17:33:46.271499 29159 leaderelection.go:252] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:8443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: dial tcp 127.0.0.1:8443: connect: connection refused

见issue 402
