### ISSUE TITLE
创建 kubeconfig 文件中 server地址不生效

### ISSUE THREAD

**Issue by neighbour-oldhuang** [opsnull/follow-me-install-kubernetes-cluster#427]
# 设置集群参数
kubectl config set-cluster kubernetes \
  --certificate-authority=/opt/k8s/work/ca.pem \
  --embed-certs=true \
  --server=${KUBE_APISERVER} \
  --kubeconfig=kubectl.kubeconfig
![image](https://user-images.githubusercontent.com/23180415/55537398-af042380-56ee-11e9-850c-7f0fc7ff25b6.png)
![image](https://user-images.githubusercontent.com/23180415/55537454-d22ed300-56ee-11e9-831c-5a3cd99e7c36.png)
红圈中是我手动编辑的
之前是 ""

**Comment by opsnull** [comment]
这个环境变量是在 environment.sh 脚本中定义的。
