### ISSUE TITLE
升级内核至4.4的原因？

### ISSUE THREAD

**Issue by AlanCarl** [opsnull/follow-me-install-kubernetes-cluster#430]
因为升级系统内核可能导致许多其他的问题，所以在此我想问下，K8S部署时升级内核至4.4是有哪些必须的原因？

我查了一些资料，比较相关的是#61937(https://github.com/kubernetes/kubernetes/issues/61937).

是否只是因为这个原因才要升级内核？如果有别的办法解决上述问题，是否就不需要升级内核了？

**Comment by neighbour-oldhuang** [comment]
教程不可能100%符合 你的期望, 高版本的内核对不管是对docker还是 其他应用特性支持理论上都会优化一些, 升级内核也是统一环境, 尽可能多的避免因环境问题导致的各种问题. 个人理解

**Comment by neighbour-oldhuang** [comment]
> 因为升级系统内核可能导致许多其他的问题，所以在此我想问下，K8S部署时升级内核至4.4是有哪些必须的原因？
> 
> 我查了一些资料，比较相关的是#61937([kubernetes/kubernetes#61937](https://github.com/kubernetes/kubernetes/issues/61937)).
> 
> 是否只是因为这个原因才要升级内核？如果有别的办法解决上述问题，是否就不需要升级内核了？

教程不可能100%符合 你的期望, 高版本的内核对不管是对docker还是 其他应用特性支持理论上都会优化一些, 升级内核也是统一环境, 尽可能多的避免因环境问题导致的各种问题. 个人理解

**Comment by AlanCarl** [comment]
每一个步骤都有其深意。这个作者分享的部署步骤我反复试了很多次，包括v1.10和v1.12版本。

升级内核必然有其背后的原因。经过我的检索，K8Sv1.9+与centos系列7.x之间存在一个较为严重的问题，当Linux内核版本低于4.4时，会出现内核锁死，而这对生产环境来说是致命的。作者在发布这份指南的时候，当时的处理方法就是将内核版本升级至4.4，但这依然无法完全避免这一风险。

最近，Docker方面更新了版本，专门针对内核锁死问题进行了处理。这一解决方法相比较于升级内核能更好的处理该问题。所以，如果升级内核只是单纯为了处理这一个问题的话，那升级内核的操作就可以避免了。毕竟，对于很多系统了来说，升级内核可能也是存在一定风险的。

**Comment by opsnull** [comment]
@AlanCarl 回答的非常赞。

1. 3.10 内核 kmem account 泄漏 bugs 导致节点 NotReady
2. 3.10 内核 Bugs，系统日志出现大量 kernel: unregister_netdevice: waiting for eth0 to become free 报错，节点 NotReady
3. kernel: NMI watchdog: BUG soft lockup -CPU#9 stuck for 22s! [migration/9:54]”

可以参考：
https://mp.weixin.qq.com/s?__biz=MzI3NDIxNTQyOQ==&mid=2247488656&idx=1&sn=e92c1ae5bd603e1f020fe51916d4daa5&chksm=eb1633fadc61baec932be490bc43c698945785ae4b8a799e72620092b021cda26e99e06ca288&mpshare=1&scene=1&srcid=&rd2werd=1#wechat_redirect

**Comment by xgfone** [comment]
@AlanCarl 那是不是说，我只要使用最新版的 Docker 即可，不用更新 CentOS 7 的内核了？？

**Comment by AlanCarl** [comment]
@xgfone 目前我是这么操作的，没有升级内核版本，升级了Docker版本，暂时没有出什么问题。

**Comment by torlix** [comment]
作者威武，多谢分享
