### ISSUE TITLE
所有教程都会叫关闭防火墙，为啥？

### ISSUE THREAD

**Issue by zuihou** [opsnull/follow-me-install-kubernetes-cluster#431]
1， 关闭防火墙后，服务器安装如何保证
2，若开启防火墙， 并且把主节点和工作节点所有部署的服务端口都打开，能行吗？
3，开启防火墙后， 新部署一个nginx服务，nodePort类型端口30000， 会指定加入防火墙规则吗？

**Comment by opsnull** [comment]
关闭防火墙是为了方便大家部署过程中不受干扰。
如果懂得配置防火墙策略，开启是完全没问题的。

**Comment by zuihou** [comment]
> 关闭防火墙是为了方便大家部署过程中不受干扰。
> 如果懂得配置防火墙策略，开启是完全没问题的。

 是不是把 主节点和工作节点所有部署的服务端口都打开，
然后在把部署的项目端口打开即可？
