### ISSUE TITLE
metric-server部署报错  2个pod都起不来

### ISSUE THREAD

**Issue by sanger89** [opsnull/follow-me-install-kubernetes-cluster#432]
**docker ps -a**
2c22628c98b6        b57c00a12f6c                                                  "/pod_nanny --config…"   22 seconds ago      Exited (2) 20 seconds ago                       k8s_metrics-server-nanny_metrics-server-v0.3.1-6f96d6d78-ps2j6_kube-system_d09ea719-5a78-11e9-8984-fab5c188590c_2
f89d45ae81cf        61a0c90da56e                                                  "/metrics-server --m…"   39 seconds ago      Up 38 seconds                                   k8s_metrics-server_metrics-server-v0.3.1-6f96d6d78-ps2j6_kube-system_d09ea719-5a78-11e9-8984-fab5c188590c_0

**docker logs 2c22628c98b6**        

**ERROR**: logging before flag.Parse: I0409 03:37:55.244873       1 pod_nanny.go:65] Invoked by [/pod_nanny --config-dir=/etc/config --cpu={{ base_metrics_server_cpu }} --extra-cpu=0.5m --memory={{ base_metrics_server_memory }} --extra-memory={{ metrics_server_memory_per_node }}Mi --threshold=5 --deployment=metrics-server-v0.3.1 --container=metrics-server --poll-period=300000 --estimator=exponential --minClusterSize=2]
**ERROR**: logging before flag.Parse: I0409 03:37:55.245354       1 pod_nanny.go:81] Watching namespace: kube-system, pod: metrics-server-v0.3.1-6f96d6d78-ps2j6, container: metrics-server.
**ERROR**: logging before flag.Parse: I0409 03:37:55.245391       1 pod_nanny.go:82] storage: MISSING, extra_storage: 0Gi
**ERROR**: logging before flag.Parse: I0409 03:37:55.341185       1 pod_nanny.go:109] cpu: {{ base_metrics_server_cpu }}, extra_cpu: 0.5m, memory: {{ base_metrics_server_memory }}, extra_memory: {{ metrics_server_memory_per_node }}Mi
panic: cannot parse '{{ base_metrics_server_cpu }}': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

goroutine 1 [running]:
k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource.MustParse(0x7ffc3f8fa54c, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/danielmk/go/src/k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:136 +0x228
main.main()
	/usr/local/google/home/danielmk/go/src/k8s.io/autoscaler/addon-resizer/nanny/main/pod_nanny.go:116 +0x6c3

**docker logs f89d45ae81cf**     

Flag --deprecated-kubelet-completely-insecure has been deprecated, This is rarely the right option, since it leaves kubelet communication completely insecure.  If you encounter auth errors, make sure you've enabled token webhook auth on the Kubelet, and if you're in a test cluster with self-signed Kubelet certificates, consider using kubelet-insecure-tls instead.
I0409 03:37:38.035316       1 serving.go:273] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
[restful] 2019/04/09 03:37:38 log.go:33: [restful/swagger] listing is available at https://:443/swaggerapi
[restful] 2019/04/09 03:37:38 log.go:33: [restful/swagger] https://:443/swaggerui/ is mapped to folder /swagger-ui/
I0409 03:37:38.642855       1 serve.go:96] Serving securely on [::]:443
W0409 03:37:57.164737       1 x509.go:172] x509: subject with cn=aggregator is not in the allowed list: []
E0409 03:38:08.661458       1 manager.go:102] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:kube-node-150: unable to fetch metrics from Kubelet kube-node-150 (kube-node-150): Get http://kube-node-150:10250/stats/summary/: dial tcp: lookup kube-node-150 on 10.254.0.2:53: no such host, unable to fully scrape metrics from source kubelet_summary:kube-node-151: unable to fetch metrics from Kubelet kube-node-151 (kube-node-151): Get http://kube-node-151:10250/stats/summary/: dial tcp: lookup kube-node-151 on 10.254.0.2:53: no such host, unable to fully scrape metrics from source kubelet_summary:kube-node-152: unable to fetch metrics from Kubelet kube-node-152 (kube-node-152): Get http://kube-node-152:10250/stats/summary/: dial tcp: lookup kube-node-152 on 10.254.0.2:53: no such host]
E0409 03:38:38.632709       1 manager.go:102] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:kube-node-151: unable to fetch metrics from Kubelet kube-node-151 (kube-node-151): Get http://kube-node-151:10250/stats/summary/: dial tcp: lookup kube-node-151 on 10.254.0.2:53: no such host, unable to fully scrape metrics from source kubelet_summary:kube-node-152: unable to fetch metrics from Kubelet kube-node-152 (kube-node-152): Get http://kube-node-152:10250/stats/summary/: dial tcp: lookup kube-node-152 on 10.254.0.2:53: no such host, unable to fully scrape metrics from source kubelet_summary:kube-node-150: unable to fetch metrics from Kubelet kube-node-150 (kube-node-150): Get http://kube-node-150:10250/stats/summary/: dial tcp: lookup kube-node-150 on 10.254.0.2:53: no such host]
E0409 03:39:08.808747       1 manager.go:102] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:kube-node-150: unable to fetch metrics from Kubelet kube-node-150 (kube-node-150): Get http://kube-node-150:10250/stats/summary/: dial tcp: lookup kube-node-150 on 10.254.0.2:53: no such host, unable to fully scrape metrics from source kubelet_summary:kube-node-152: unable to fetch metrics from Kubelet kube-node-152 (kube-node-152): Get http://kube-node-152:10250/stats/summary/: dial tcp: lookup kube-node-152 on 10.254.0.2:53: no such host, unable to fully scrape metrics from source kubelet_summary:kube-node-151: unable to fetch metrics from Kubelet kube-node-151 (kube-node-151): Get http://kube-node-151:10250/stats/summary/: dial tcp: lookup kube-node-151 on 10.254.0.2:53: no such host]

**Comment by deep-cds** [comment]
你好 ， 我也是遇到跟你一样的问题 ， 请问解决了吗 ， 是怎么解决的？

**Comment by opsnull** [comment]
> Get http://kube-node-151:10250/stats/summary/: dial tcp: lookup kube-node-151 on 10.254.0.2:53: no such host
容器内部不能解析主机名 kube-node-151  的缘故，可以配置 metrics-server 的参数 --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP，这样优先使用 InternalIP；
