### ISSUE TITLE
部署metrics-server  失败     please  help  ，thanks 

### ISSUE THREAD

**Issue by deep-cds** [opsnull/follow-me-install-kubernetes-cluster#445]
![image](https://user-images.githubusercontent.com/44251514/57190222-a6e80f80-6f4a-11e9-8cc8-eba1fad95f4e.png)

mestrics-server-deployment.yaml  如下 

[metrics-server-deployment.txt](https://github.com/opsnull/follow-me-install-kubernetes-cluster/files/3145243/metrics-server-deployment.txt)

**Comment by linkingtd** [comment]
去k8s仓库中把版本v.1.11.2版本左右 中metrics-server yaml文件 下载下来 覆盖现在这个，就可以了

**Comment by deep-cds** [comment]
@linkingtd  thanks
