### ISSUE TITLE
通过kube-apiserver 访问dashboard报错401

### ISSUE THREAD

**Issue by Croyson** [opsnull/follow-me-install-kubernetes-cluster#450]
https://10.211.55.7:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
{
kind: "Status",
apiVersion: "v1",
metadata: { },
status: "Failure",
message: "Unauthorized",
reason: "Unauthorized",
code: 401
}

**Comment by opsnull** [comment]
文档里已经解释过这个问题。

**Comment by hardyxia2018** [comment]
![image](https://user-images.githubusercontent.com/44759712/73345566-40b4d100-42bf-11ea-8cbf-fac0730c51fc.png)

Firefox 显示安全连接，admin.pfx 也导入，但是一直401

**Comment by hardyxia2018** [comment]
![image](https://user-images.githubusercontent.com/44759712/73513950-aec9d700-442a-11ea-941f-ab5db2f7d0b3.png)
作者确定这个生成的证书没问题吗

**Comment by 957446525** [comment]
从9-2开始，很多图都显示不了了，博主处理一下吧
