### ISSUE TITLE
启动 kube-scheduler 服务失败

### ISSUE THREAD

**Issue by yanzuo0609** [opsnull/follow-me-install-kubernetes-cluster#453]
按照文档安装配置，启动kube-scheduler 失败，日志可以看到如下错误：
May 18 15:59:56 m7-autocv-gpu02 kube-scheduler[36596]: no kind "KubeSchedulerConfiguration" is registered for version "componentconfig/v1alpha1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:29"
May 18 15:59:56 m7-autocv-gpu02 systemd[1]: kube-scheduler.service: main process exited, code=exited, status=1/FAILURE
May 18 15:59:56 m7-autocv-gpu02 systemd[1]: Unit kube-scheduler.service entered failed state.
May 18 15:59:56 m7-autocv-gpu02 systemd[1]: kube-scheduler.service failed.

**Comment by opsnull** [comment]
看起来像 K8S 版本兼容性问题，本文档只适合 1.12，这个参数在 1.13 版本是不支持的。
