### ISSUE TITLE
kubeadm没有

### ISSUE THREAD

**Issue by zhangq123456** [opsnull/follow-me-install-kubernetes-cluster#454]
老师你好：
   我在部署kubelet的时候，发现需要生成token “export BOOTSTRAP_TOKEN=￥（kubeadm token Create” 我在前面的步骤中都没有发现有安装部署kubeadm的。
   另：在kubelet.config.yaml文件生成的时候，有个变量“POD_CID”,我在env.sh文件中也没有找到这个变量定义。

**Comment by opsnull** [comment]
kubeadm 包含在 06-1.部署 master 节点 一文下载的 kubernetes-server-linux-amd64.tar.gz 包中。
