### ISSUE TITLE
06-4.部署高可用 kube-scheduler 集群

### ISSUE THREAD

**Issue by Vv123456789** [opsnull/follow-me-install-kubernetes-cluster#457]
06-4.部署高可用 kube-scheduler 集群
创建 kube-scheduler 证书和私钥少了个 “ , ”
      "172.27.128.148"
      "172.27.128.149",
      "172.27.128.150"

      "172.27.128.148"，
      "172.27.128.149",
      "172.27.128.150"
才对

**Comment by opsnull** [comment]
谢谢反馈，已有 PR 修复。
