### ISSUE TITLE
Kubelet config file /etc/kubernetes/kubelet-config.yaml 

### ISSUE THREAD

**Issue by zdwork** [opsnull/follow-me-install-kubernetes-cluster#458]
帮忙看下这个问题 
 failed to load Kubelet config file /etc/kubernetes/kubelet-config.yaml, error failed to decode, error: v1beta1.KubeletConfiguration.EvictionSoft: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|ionSoft":"nil","fail|..., bigger context ...|":"10%","nodefs.inodesFree":"5%"},"evictionSoft":"nil","failSwapOn":true,"fileCheckFrequency":"20s",|...

**Comment by duerlatter** [comment]
kubelet-config.yaml.template 文件排版问题 我也是遇见了这个问题

**Comment by zdwork** [comment]
您好
可以发个 正确的模板吗

**Comment by duerlatter** [comment]
刚安装到这一步,  还没来得及

**Comment by duerlatter** [comment]
刚走到这一步 还没来得及细看.  可等作者订正

**Comment by zdwork** [comment]
k8s Y有格式化这个语法的命令吗

**Comment by opsnull** [comment]
感谢反馈，已修复。
