### ISSUE TITLE
#458 Kubelet config file /etc/kubernetes/kubelet-config.yaml

### ISSUE THREAD

**Issue by duerlatter** [opsnull/follow-me-install-kubernetes-cluster#459]
** 文档版本 **
master
**现象描述**
描述问题的现象。
#458  问题依然存在,

failed to load Kubelet config file /etc/kubernetes/kubelet-config.yaml, error failed to decode, error: v1beta1.KubeletConfiguration.EvictionSoft: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|ionSoft":"nil","fail|..., bigger context ...|":"10%","nodefs.inodesFree":"5%"},"evictionSoft":"nil","failSwapOn":true,"fileCheckFrequency":"20s",|...

还需设置 evictionSoft systemReserved kubeReserved 默认为nil的三个值

**Comment by opsnull** [comment]
需要把 nil 替换为 {}。
