### ISSUE TITLE
cat /etc/kubernetes/kubelet.kubeconfig 

### ISSUE THREAD

**Issue by zdwork** [opsnull/follow-me-install-kubernetes-cluster#460]
请教大家个问题 kubelet.kubeconfig配置文件里  client-certificate和 client-key 为啥都是.pem呢
cat /etc/kubernetes/kubelet.kubeconfig 

 client-certificate: /etc/kubernetes/cert/kubelet-client-current.pem
 client-key: /etc/kubernetes/cert/kubelet-client-current.pem

**Comment by opsnull** [comment]
因为 kubelet 的 client & server 会被周期轮转的，不能讲证书嵌入到 kubeconfig 文件中。
