### ISSUE TITLE
您好 我这个为啥没有任何输出呢

### ISSUE THREAD

**Issue by zdwork** [opsnull/follow-me-install-kubernetes-cluster#461]
curl -s --cacert /etc/kubernetes/cert/ca.pem https://192.168.20.183:10250/metrics

**Comment by zlfzy** [comment]
确实没有

**Comment by opsnull** [comment]
kubelet 的 server 证书有么？具体参考：07-2.kubelet.md 的 手动 approve server cert csr

**Comment by zdwork** [comment]
多谢 手动approve server cert csr 之后就可以了 不知道自动为啥不行

**Comment by opsnull** [comment]
kubelet server  证书的 csr 需要手动  approve。
