### ISSUE TITLE
controller-manager 启动后一直打印这些信息 

### ISSUE THREAD

**Issue by zdwork** [opsnull/follow-me-install-kubernetes-cluster#466]
5月 30 09:42:05 k8s-01 kube-apiserver[30701]: Impacted events:
5月 30 09:42:05 k8s-01 kube-apiserver[30701]: 2019-05-30T09:42:05.804985922+08:00 AUDIT: id="dc7e02ea-4afb-4a26-bdd2-a312d3d9b84a" stage="ResponseComplete" ip="192.168.20.130" method="list" user="system:serviceaccount:kube-system:cronjob-controller" groups="\"system:serviceaccounts\",\"system:serviceaccounts:kube-system\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/apis/batch/v1beta1/cronjobs?limit=500" response="200"
5月 30 09:42:07 k8s-01 kube-apiserver[30701]: E0530 09:42:07.165637   30701 metrics.go:96] 

Error in audit plugin 'buffered' affecting 1 audit events: audit buffer queue blocked

5月 30 09:42:07 k8s-01 kube-apiserver[30701]: Impacted events:
5月 30 09:42:07 k8s-01 kube-apiserver[30701]: 2019-05-30T09:42:07.156858329+08:00 AUDIT: id="8b1ea04a-4fdb-4928-9c70-9e45e3ba23cb" stage="ResponseComplete" ip="192.168.20.130" method="list" user="system:serviceaccount:kube-system:pod-garbage-collector" groups="\"system:serviceaccounts\",\"system:serviceaccounts:kube-system\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/api/v1/nodes" response="200"

**Comment by zdwork** [comment]
5月 30 10:24:16 k8s-02 kube-controller-manager[104313]: W0530 10:24:16.302299  104313 reflector.go:289] k8s.io/client-go/informers/factory.go:133: watch of *v1beta1.Event ended with: The resourceVersion for the provided watch is too old.

**Comment by zdwork** [comment]
大哥们 帮忙看看

**Comment by opsnull** [comment]
没有影响的。

**Comment by zdwork** [comment]
多谢
