### ISSUE TITLE
kubelet启动后一直报这个错误 大哥求助

### ISSUE THREAD

**Issue by zdwork** [opsnull/follow-me-install-kubernetes-cluster#467]
#apiserver
kube-apiserver[109181]: E0530 15:47:26.595341  109181 authentication.go:65] Unable to authenticate the request due to an error: invalid bearer token

#kubelet
5月 30 15:47:35 k8s-node kubelet[34217]: E0530 15:47:35.643333   34217 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list...uthorized
5月 30 15:47:35 k8s-node kubelet[34217]: E0530 15:47:35.644552   34217 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed...uthorized
5月 30 15:47:35 k8s-node kubelet[34217]: E0530 15:47:35.671988   34217 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v...uthorized
5月 30 15:47:35 k8s-node kubelet[34217]: E0530 15:47:35.674858   34217 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v...uthorized
5月 30 15:47:35 k8s-node kubelet[34217]: E0530 15:47:35.733238   34217 kubelet.go:2244] node "k8s-node" not found
5月 30 15:47:35 k8s-node kubelet[34217]: E0530 15:47:35.833783   34217 kubelet.go:2244] node "k8s-node" not found
5月 30 15:47:35 k8s-node kubelet[34217]: E0530 15:47:35.934105   34217 kubelet.go:2244] node "k8s-node" not found

**Comment by opsnull** [comment]
你的各节点名称分别是什么？

**Comment by zdwork** [comment]
您好 已解决
toeken的问题
我用你的项目写了一个一键安装的脚本
https://github.com/zdwork/k8s-install
