### ISSUE TITLE
07-2.部署 kubelet 组件，访问 metrics 和 metrics/cadvisor  返回Unauthorized

### ISSUE THREAD

**Issue by guishensxy** [opsnull/follow-me-install-kubernetes-cluster#469]
**使用的版本和问题章节**
https://github.com/opsnull/follow-me-install-kubernetes-cluster，使用的这个文档，
07-2.kubelet.md
版本V1.14.3

**现象描述**
07-2.kubelet.md 之前的部署都已经通过，但是在本文中最后，使用浏览器访问 https://172.27.137.240:10250/metrics 和 https://172.27.137.240:10250/metrics/cadvisor 分别返回 kubelet 和 cadvisor 的 metrics的时候，页面提示 Unauthorized。
已经完成了“证书认证和授权”和“bear token 认证和授权”，也可以“获取 kubelet 的配置”。
但是页面一直提示 Unauthorized。
之后的文章也没有进行

补充：sudo journalctl -u kubelet -a |grep -A 2 'certificatesigningrequests' 这个也没有报错提示，如果使用sudo journalctl -u kubelet -a 提示
![image](https://user-images.githubusercontent.com/30856194/58698685-58edec80-83ce-11e9-9826-0e0bd2122137.png)

**Comment by opsnull** [comment]
![image](https://user-images.githubusercontent.com/433567/58742889-7c5e7900-845a-11e9-9fab-6b9a8689adae.png)
