### ISSUE TITLE
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)

### ISSUE THREAD

**Issue by zdwork** [opsnull/follow-me-install-kubernetes-cluster#470]
大哥求助
[root@k8s-01 1.8+]#  kubectl top node
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)

**Comment by achuDk** [comment]
请问后来怎么成功的呢？
