### ISSUE TITLE
kubelet启动成功，kubelet有报错

### ISSUE THREAD

**Issue by yzhangying** [opsnull/follow-me-install-kubernetes-cluster#473]
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.418615   14661 kubelet.go:2244] node "master1" not found
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.518789   14661 kubelet.go:2244] node "master1" not found
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.525714   14661 controller.go:115] failed to ensure node lease exists, will retry in 7s, error: Unauthorized
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.619007   14661 kubelet.go:2244] node "master1" not found
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.649143   14661 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Unauthorized
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.653942   14661 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Unauthorized
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.661361   14661 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Unauthorized
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.673295   14661 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.679516   14661 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Unauthorized
Jun 03 17:33:59 master1 kubelet[14661]: E0603 17:33:59.719293   14661 kubelet.go:2244] node "master1" not found

**Comment by mds1455975151** [comment]
+1

**Comment by opsnull** [comment]
这一步做了么：
![image](https://user-images.githubusercontent.com/433567/58968929-6e598100-87e9-11e9-98e3-9459253ce802.png)

**Comment by mds1455975151** [comment]
我按照master版本文档操作的 当时使用的最新的v1.14.2 这步骤也执行过

**Comment by Just-Doing** [comment]
我之前也遇到这个问题， 走完博主的 approve CSR 请求 它就好了

**Comment by yzhangying** [comment]
角色绑定已经绑定过了，但还是有这种问题

**Comment by yzhangying** [comment]
角色绑定已经绑定过了，但还是有这种问题

**Comment by xiahuhu1** [comment]
我跟楼主一样，这个到底是什么问题啊，查了一天没有查到解决办法

**Comment by jaychang9** [comment]
同样的问题，不知道是什么原因
`root@k8s-1:~# journalctl -u kubelet |tail
Jun 24 06:38:57 k8s-1 kubelet[19866]: I0624 06:38:57.156514   19866 kubelet_node_status.go:72] Attempting to register node k8s-1
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.165074   19866 kubelet_node_status.go:94] Unable to register node "k8s-1" with API server: Unauthorized
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.204559   19866 kubelet.go:2244] node "k8s-1" not found
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.222903   19866 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Unauthorized
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.305147   19866 kubelet.go:2244] node "k8s-1" not found
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.405714   19866 kubelet.go:2244] node "k8s-1" not found
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.506180   19866 kubelet.go:2244] node "k8s-1" not found
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.607315   19866 kubelet.go:2244] node "k8s-1" not found
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.707822   19866 kubelet.go:2244] node "k8s-1" not found
Jun 24 06:38:57 k8s-1 kubelet[19866]: E0624 06:38:57.808499   19866 kubelet.go:2244] node "k8s-1" not found
`

而且这一步也执行了
kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --group=system:bootstrappers

**Comment by opsnull** [comment]
是的，需要 自动或手动 Approve CSR。
