### ISSUE TITLE
检测状态时kube-scheduler / kube-controller-manager 不正常

### ISSUE THREAD

**Issue by Just-Doing** [opsnull/follow-me-install-kubernetes-cluster#474]
**文档版本**
 K8S v1.14.2。
    都是按照文档来部署的
**现象描述**
我将 kubelet / kube-apiserver / kube-scheduler / kube-controller-manager 部署在同一台机器上
检测状态时kube-scheduler / kube-controller-manager 不正常
![image](https://user-images.githubusercontent.com/6999056/58890447-32f18080-871d-11e9-8ec5-fdcedbb22fd6.png)

kubelet 服务状态
![image](https://user-images.githubusercontent.com/6999056/58891037-5e289f80-871e-11e9-991d-0fbfb51676fc.png)

kube-apiserver 服务状态
![image](https://user-images.githubusercontent.com/6999056/58891098-7f898b80-871e-11e9-96a9-e0950b6cbeb1.png)

大哥们帮帮忙，不知道那个环节出了问题，

**Comment by opsnull** [comment]
![Uploading image.png…]()

**Comment by opsnull** [comment]
![image](https://user-images.githubusercontent.com/433567/58968538-cba10280-87e8-11e9-901d-ded49444c617.png)
