### ISSUE TITLE
metrics-server部署后，验证时出错

### ISSUE THREAD

**Issue by Kingchan230** [opsnull/follow-me-install-kubernetes-cluster#476]
**文档版本**
说明你查看的是哪个 branch 的文档，即 K8S 版本，如 v1.8、v1.12。

**现象描述**
描述问题的现象。

**Comment by Kingchan230** [comment]
修改metrics-server-deployment.yaml后，部署metrics-server，验证功能时，可以获取vibate1的信息
但是无法获取node的相关信息，报错：User "aggregator" cannot list nodes.metrics.k8s.io at the cluster scope
![image](https://user-images.githubusercontent.com/22443359/59261103-7002c900-8c6f-11e9-9797-9faefe127fda.png)
一直提示这个错误，请问如何处理？

**Comment by redfoxfox** [comment]
同样的报错, 执行kubectl  top node也会报错
