### ISSUE TITLE
这个文档能跑通吗？

### ISSUE THREAD

**Issue by guishensxy** [opsnull/follow-me-install-kubernetes-cluster#477]
**文档版本**
K8S V1.14.3

**现象描述**
我按照文档，每步都一样，除了目录不一样之外。根本跑不起来。。。而且我的之前问的问题为什么被删掉了

**Comment by hackerzyh** [comment]
可以跑的起来
你要把错误日志贴出来，别人才能帮你

**Comment by opsnull** [comment]
@guishensxy 提问的智慧：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
