### ISSUE TITLE
elasticsearch 部署完成之后，使用同样的请求，返回不同样的结果。

### ISSUE THREAD

**Issue by Kingchan230** [opsnull/follow-me-install-kubernetes-cluster#480]
**文档版本**
根据当前最新的部署文档一步步部署。

**现象描述**
按照部署文档，部署EFK之后，直接通过命令
curl -X 调用elasticsearh 的api,返回的结果不一致，出现轮询的情况。
![image](https://user-images.githubusercontent.com/22443359/59583712-b2645400-910e-11e9-9ad0-05c41724d495.png)

**Comment by opsnull** [comment]
这个是 ES 的问题，超出了本文档的支持范围。
