### ISSUE TITLE
建议Docker使用systemd作为cgroupfs

### ISSUE THREAD

**Issue by N0mansky** [opsnull/follow-me-install-kubernetes-cluster#486]
**文档版本**
k8s v1.15

**现象描述**
1. 在官方文档里，安装Docker作为container runtime的时候，在`/etc/docker/daemon.sjon`建议加上一条`"exec-opts": ["native.cgroupdriver=systemd"],`
2. 原文如下:

> When systemd is chosen as the init system for a Linux distribution, the init process generates and consumes a root control group (cgroup) and acts as a cgroup manager. Systemd has a tight integration with cgroups and will allocate cgroups per process. It’s possible to configure your container runtime and the kubelet to use cgroupfs. Using cgroupfs alongside systemd means that there will then be two different cgroup managers.
> 
> Control groups are used to constrain resources that are allocated to processes. A single cgroup manager will simplify the view of what resources are being allocated and will by default have a more consistent view of the available and in-use resources. When we have two managers we end up with two views of those resources. We have seen cases in the field where nodes that are configured to use cgroupfs for the kubelet and Docker, and systemd for the rest of the processes running on the node becomes unstable under resource pressure.
> 
> Changing the settings such that your container runtime and kubelet use systemd as the cgroup driver stabilized the system. Please note the native.cgroupdriver=systemd option in the Docker setup below.

引用自：[k8s container runtime](https://kubernetes.io/docs/setup/production-environment/container-runtimes/)

**Comment by N0mansky** [comment]
btw,kubelet config file中，cgroupDriver也要改为systemd

**Comment by opsnull** [comment]
docker 和 kubelet 默认的 cgroupdriver 都为 cgroupfs，所以本文档没有明确配置这个参数，使用默认值 cgroupfs。
