### ISSUE TITLE
求助：kubectl 证书不对

### ISSUE THREAD

**Issue by lwheha** [opsnull/follow-me-install-kubernetes-cluster#49]
执行：kubectl get node 报如下错误
error: You must be logged in to the server (the server has asked for the client to provide credentials)

kube-apiserver 的日志报  “Unable to authenticate the request due to an error: x509: certificate specifies an incompatible key usage”

如下是admin-csr.json 内容，请帮看看有可能是哪里问题
{
  "CN": "admin",
  "hosts": [],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "CN",
      "ST": "BeiJing",
      "L": "BeiJing",
      "O": "system:masters",
      "OU": "System"
    }
  ]
}

**Comment by opsnull** [comment]
> kube-apiserver 的日志报 “Unable to authenticate the request due to an error: x509: certificate specifies an incompatible key usage”

看起来你的 CA 证书配置有问题，请参考 ca-config.json 重新生成CA和其它证书；

**Comment by lwheha** [comment]
嗯，都是不细心，copy都能丢东西，谢谢啦
