### ISSUE TITLE
kube-scheduler 部署完毕后，无法通过https访问10259端口服务

### ISSUE THREAD

**Issue by tiandong19860806** [opsnull/follow-me-install-kubernetes-cluster#490]
**文档版本**
https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/06-4.scheduler%E9%9B%86%E7%BE%A4.md

     
**kubenetes版本**
1. k8s版本 = v1.14.1
2. 已经在三台master机器部署完kube-apiserver和kube-scheduler
kubectl get cs 查询返回结果OK，可以看见已经安装的组件OK,如下：（kube-controller-manager还没有安装，下一步安装）
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
scheduler            Healthy     ok 
etcd-1               Healthy     {"health":"true"}                                                                           
etcd-2               Healthy     {"health":"true"}                                                                           
etcd-0               Healthy     {"health":"true"} 

2. 可以通过curl + kubenetes.pem证书，访问kube-apiserver的rest服务，如下
方式1：机器IP方式
curl --cacert /k8s/kubernetes/ssl/k8s-ca.pem --cert /k8s/kubernetes/ssl/kubernetes.pem --key /k8s/kubernetes/ssl/kubernetes-key.pem \
https://192.168.3.96:6443/api/v1
方式2：域名方式
curl --cacert /k8s/kubernetes/ssl/k8s-ca.pem --cert /k8s/kubernetes/ssl/kubernetes.pem --key /k8s/kubernetes/ssl/kubernetes-key.pem \
https://k8s-master-cluster-01.its.cn:8443/api/v1
正常返回结果，如下json报文，文字省略。
{
  "kind": "APIResourceList",
  "groupVersion": "v1",
  "resources": [
    {
      "name": "bindings",
      "singularName": "",
      "namespaced": true,
      "kind": "Binding",
      "verbs": [
        "create"
      ]
    },
    {
剩下文字省略。

3. kube-scheduler的安全端口10251可以访问，并且正常返回结果，如下
curl -s http://127.0.0.1:10251/metrics | head
`# HELP apiserver_audit_event_total Counter of audit events generated and sent to the audit backend.
`# TYPE apiserver_audit_event_total counter
apiserver_audit_event_total 0
`# HELP apiserver_audit_requests_rejected_total Counter of apiserver requests rejected due to an error in audit logging backend.
`# TYPE apiserver_audit_requests_rejected_total counter
apiserver_audit_requests_rejected_total 0
`# HELP apiserver_client_certificate_expiration_seconds Distribution of the remaining lifetime on the certificate used to authenticate a request.
`# TYPE apiserver_client_certificate_expiration_seconds histogram
apiserver_client_certificate_expiration_seconds_bucket{le="0"} 0
apiserver_client_certificate_expiration_seconds_bucket{le="1800"} 0`

4. https 访问10259的heathz，正常返回OK
curl -s --cacert /k8s/kubernetes/ssl/k8s-ca.pem --cert /k8s/kubernetes/ssl/admin.pem --key /k8s/kubernetes/ssl/admin-key.pem https://192.168.3.96:10259/healthz
root >> OK

        
**现象描述**
5. kube-scheduler的安全端口10259不能访问，感觉权限受限，但是证书和kubeconfig制作完全按照作者教材制作，不清楚为何不行。
root >> curl -s --cacert /k8s/kubernetes/ssl/k8s-ca.pem --cert /k8s/kubernetes/ssl/admin.pem --key /k8s/kubernetes/ssl/admin-key.pem https://192.168.3.96:10259/metrics | head
或
root >> curl -s --cacert /k8s/kubernetes/ssl/k8s-ca.pem --cert /k8s/kubernetes/ssl/k8s-scheduler.pem --key /k8s/kubernetes/ssl/k8s-scheduler-key.pem https://192.168.3.96:10259/metrics |head
root >>
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:kube-scheduler\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {

**Comment by tiandong19860806** [comment]
我感觉是否是pem证书和kubeconfig文件，教材中使用的一些user或group或O或CN可能设置不对？
比如kube-apiserver章节是kubenetes。但是在kube-scheduler又是system:kube-scheduler和kubenetes。

      剩下的章节我都完整照着做过，总有不能完全正常执行，最后所有5个主要组件都部署完毕。
master发起的pod部署，却执行完deployment、pod等环节，最后pod处于pending状态，却没有event日志，感觉master根本就权限通知到node节点的kubelet执行pod的所有操作。

**Comment by tiandong19860806** [comment]
这次bug，我是第三次完全零环境，复盘部署k8s所有集群组件。三 master + 三node。
感觉证书csr.json文件和kubeconfig文件，个人感觉教材中各个k8s组件之间是否有user或group或CN或O/OU有不对的问题。

**Comment by tiandong19860806** [comment]
楼主，
如果可以的话，把你部署完毕的所有K8S组件的配置文件yaml/propeties/csr.json/.service文件，分享出来我们看看是否哪里我们理解教材和你的实际意思不一致。

谢谢

**Comment by opsnull** [comment]
> 5. kube-scheduler的安全端口10259不能访问，感觉权限受限，但是证书和kubeconfig制作完全按照作者教材制作，不清楚为何不行。
curl 使用的证书权限不足导致的。

看文档，我示例用的是 admin 证书。

**Comment by tiandong19860806** [comment]
Hi @opsnull ,
   上面确实是证书使用有误，把kubelet使用了kube-apiserver-server.pem的证书导致。
我当时理解为kube-apiserver/kubelet/kube-proxy可以用不同名字的证书pem。只要调用kube-apiserver生成的证书即可。看来是我理解错了。
