### ISSUE TITLE
kube-controller-manager.service 参数有冲突

### ISSUE THREAD

**Issue by tiandong19860806** [opsnull/follow-me-install-kubernetes-cluster#492]
**文档版本**
文章 = 06-3.部署高可用 kube-controller-manager 集群

**现象描述**
错误 = kube-controller-manager.service文件，参数--bind-address不能写master_ip，只能写127.0.0.1；参数--secure-port=10252不能写，必须删除，否则启动服务后报错“listen tcp 127.0.0.1:10252: bind: address already in use”。

经过多次反复试验，我发现kube-controller-manager的http/https端口参数如下：
  --bind-address=127.0.0.1 \  # https 安全通讯的地址
  --secure-port=10257 \  # https 安全通讯的端口
  --address=127.0.0.1 \  # http 非安全通讯的地址
  --port=10252 \    # http 非安全通讯的端口
而且，由于kubectl get cs使用的默认地址是http非安全通讯方式和地址127.0.0.1，且设置--master=https://127.0.0.1:10257无效。见下面提示
[root@CNT7XDCK11D03 ~]# kubectl get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused   
scheduler            Healthy     ok                                                                                          
etcd-0               Healthy     {"health":"true"}                                                                           
etcd-1               Healthy     {"health":"true"}                                                                           
etcd-2               Healthy     {"health":"true"}                                                                           
[root@CNT7XDCK11D03 ~]# 

正确的配置如下：
1 kube-controller-manager.service内容如下：
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
EnvironmentFile=/k8s/kubernetes/cfg/kube-controller-manager.env
ExecStart=/k8s/kubernetes/bin/kube-controller-manager \
  --profiling \
  --cluster-name=kubernetes \
  --controllers=*,bootstrapsigner,tokencleaner \
  --kube-api-qps=1000 \
  --kube-api-burst=2000 \
  --leader-elect=true \
  --use-service-account-credentials=true \
  --concurrent-service-syncs=2 \
  --bind-address=127.0.0.1 \  # https 安全通讯的地址
  --secure-port=10257 \  # https 安全通讯的端口
  --address=127.0.0.1 \  # http 非安全通讯的地址
  --port=10252 \    # http 非安全通讯的端口
  --tls-cert-file=/k8s/kubernetes/ssl/k8s-controller-manager-server.pem \
  --tls-private-key-file=/k8s/kubernetes/ssl/k8s-controller-manager-server-key.pem \
  --authentication-kubeconfig=${KUBECONFIG} \
  --client-ca-file=/k8s/kubernetes/ssl/k8s-ca.pem \
  --requestheader-allowed-names="" \
  --requestheader-client-ca-file=/k8s/kubernetes/ssl/k8s-ca.pem \
  --requestheader-extra-headers-prefix="X-Remote-Extra-" \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --authorization-kubeconfig=${KUBECONFIG} \
  --cluster-signing-cert-file=/k8s/kubernetes/ssl/k8s-ca.pem \
  --cluster-signing-key-file=/k8s/kubernetes/ssl/k8s-ca-key.pem \
  --experimental-cluster-signing-duration=876000h \
  --horizontal-pod-autoscaler-sync-period=10s \
  --concurrent-deployment-syncs=10 \
  --concurrent-gc-syncs=30 \
  --node-cidr-mask-size=24 \
  --service-cluster-ip-range=${SERVICE_CLUSTER_IP_RANGE} \
  --pod-eviction-timeout=6m \
  --terminated-pod-gc-threshold=10000 \
  --root-ca-file=/k8s/kubernetes/ssl/k8s-ca.pem \
  --service-account-private-key-file=/k8s/kubernetes/ssl/k8s-ca-key.pem \
  --kubeconfig=${KUBECONFIG} \
  --alsologtostderr=true \
  --logtostderr=true \
  --log-dir=${LOG_DIR} \
  --v=4
LimitNOFILE=1000000
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

2 环境变量文件kube-controller-manager.env，如下
KUBECONFIG="/k8s/kubernetes/cfg/kube-controller-manager.kubeconfig"
SERVICE_CLUSTER_IP_RANGE="10.0.0.0/16"
LOG_DIR="/var/log/k8s/kube-controller-manager"

**Comment by tiandong19860806** [comment]
最后，如上配置后，成功得到结果如下

1. root >> kubectl get cs
输出正确结果如下
[root@CNT7XDCK11D01 ~]# kubectl get cs
NAME                 STATUS    MESSAGE             ERROR
scheduler            Healthy   ok                  
controller-manager   Healthy   ok                  
etcd-1               Healthy   {"health":"true"}   
etcd-0               Healthy   {"health":"true"}   
etcd-2               Healthy   {"health":"true"} 

2. root >> curl -s --cacert /k8s/kubernetes/ssl/k8s-ca.pem --cert /k8s/kubernetes/ssl/admin.pem --key /k8s/kubernetes/ssl/admin-key.pem https://127.0.0.1:10257/metrics | head
输出正确结果如下
[root@CNT7XDCK11D01 ~]# curl -s --cacert /k8s/kubernetes/ssl/k8s-ca.pem --cert /k8s/kubernetes/ssl/admin.pem --key /k8s/kubernetes/ssl/admin-key.pem https://127.0.0.1:10257/metrics | head
# HELP ClusterRoleAggregator_adds (Deprecated) Total number of adds handled by workqueue: ClusterRoleAggregator
# TYPE ClusterRoleAggregator_adds counter
ClusterRoleAggregator_adds 3
# HELP ClusterRoleAggregator_depth (Deprecated) Current depth of workqueue: ClusterRoleAggregator
# TYPE ClusterRoleAggregator_depth gauge
ClusterRoleAggregator_depth 0
# HELP ClusterRoleAggregator_longest_running_processor_microseconds (Deprecated) How many microseconds has the longest running processor for ClusterRoleAggregator been running.
# TYPE ClusterRoleAggregator_longest_running_processor_microseconds gauge
ClusterRoleAggregator_longest_running_processor_microseconds 0
# HELP ClusterRoleAggregator_queue_latency (Deprecated) How long an item stays in workqueueClusterRoleAggregator before being requested.

**Comment by opsnull** [comment]
![image](https://user-images.githubusercontent.com/433567/61184830-a83d6300-a684-11e9-9297-5c4d5f0ece7f.png)

本文档关闭了非安全端口，所以没这个问题。

**Comment by tiandong19860806** [comment]
Hi @opsnull ,
    是的，问题原因是不管是否开启了http端口，kubectl get cs查询都显示kube-controller-manager组件都是使用的非安全端口的kube-apiserver，而不是使用安全端口的kube-apiserver。
另外参数--master = https://{master_ip}:{secure_port}完全没有生效。
