### ISSUE TITLE
kubectl get componentstatuses 的controller-manager组件报错：400

### ISSUE THREAD

**Issue by shanqiuge** [opsnull/follow-me-install-kubernetes-cluster#493]
**文档版本**
说明你查看的是哪个 branch 的文档，即 K8S 版本，如 v1.8、v1.12。
https://github.com/opsnull/follow-me-install-kubernetes-cluster 
是master分支，K8S版本是v.1.14.2
**现象描述**
描述问题的现象。
如题，执行kubectl get cs时，controller-manager 组件报错：400.
经过：
$ kubectl get componentstatuses
NAME                 STATUS      MESSAGE                                                                                     ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
etcd-0               Healthy     {"health":"true"}
etcd-2               Healthy     {"health":"true"}
etcd-1               Healthy     {"health":"true"}

原因：由上可知controller-manager 和scheduler 这两个组件是需要访问127.0.0.1:10252 和127.0.0.1:10251 这两个本机端口的。然而按照教程上是不会起这两个端口的。所以我在nginx上加了一个反向代理。但controller-manager 还是会报错。不知道问题在哪里，还望楼主指点下：
[root@k8s01 work]# kubectl get cs
NAME                 STATUS      MESSAGE                                  ERROR
controller-manager   Unhealthy   HTTP probe failed with statuscode: 400   
scheduler            Healthy     ok                                       
etcd-0               Healthy     {"health":"true"}                        
etcd-2               Healthy     {"health":"true"}                        
etcd-1               Healthy     {"health":"true"}

**Comment by opsnull** [comment]
文档中有说明：
![image](https://user-images.githubusercontent.com/433567/61185000-73321000-a686-11e9-8a51-d6a0395198ff.png)
