### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by GeekBoyDqz** [opsnull/follow-me-install-kubernetes-cluster#510]
**文档版本**
使用的最新的v14版本的文档

**现象描述**
使用kubectl命令出现以下报错
The connection to the server localhost:8080 was refused - did you specify the right host or port?

但是我不知道这个8080是哪个组件需要启动的端口，看所有端口确实没有8080端口

**Comment by GeekBoyDqz** [comment]
我重新配置config文件，可以了

**Comment by JohnnyHL** [comment]
一般出现这种情况，多是在访问集群的kube-apiserver服务端口出现，解决方案：【1】查看kube-apiserver参数配置文件中，8080端口是否绑定在非安全端口配置参数上；【2】或是netstat -nltp看一下kube-apiserver是否开启8080服务端口，【3】还有就是kubectl客户端管理工具的权限问题，那就涉及到生成kubectl.kubeconfig文件时的权限配置，该文件一般默认存放在~/.kube/config下 。

**Comment by GeekBoyDqz** [comment]
好的，我检查下





------------------ 原始邮件 ------------------
发件人: "JohnnyHL"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 晚上10:44
收件人: "opsnull/follow-me-install-kubernetes-cluster"<follow-me-install-kubernetes-cluster@noreply.github.com>;
抄送: "゛浅时光"<76587135@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [opsnull/follow-me-install-kubernetes-cluster] The connection tothe server localhost:8080 was refused - did you specify the right host orport? (#510)



一般出现这种情况，多是在访问集群的kube-apiserver服务端口出现，解决方案：【1】查看kube-apiserver参数配置文件中，8080端口是否绑定在非安全端口配置参数上；【2】或是netstat -nltp看一下kube-apiserver是否开启8080服务端口，【3】还有就是kubectl客户端管理工具的权限问题，那就涉及到生成kubectl.kubeconfig文件时的权限配置，该文件一般默认存放在~/.kube/config下 。
