### ISSUE TITLE
Prometheus服务器分析证书失败：x509:无法分析dnsname \“kubernetes.default.svc.cluster.local.\“

### ISSUE THREAD

**Issue by fanslinux** [opsnull/follow-me-install-kubernetes-cluster#513]
**文档版本**
参考v1.14.x 部署 1.14.2 版本k8s集群
**现象描述**
大神您推荐的Prometheus监控方案，在部署后Prometheus容器日志报错
```
level=error ts=2019-08-21T03:55:55.423167788Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:316: Failed to list *v1.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName \"kubernetes.default.svc.cluster.local.\""
level=error ts=2019-08-21T03:55:55.50406166Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:296: Failed to list *v1.Pod: Get https://10.254.0.1:443/api/v1/pods?resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName \"kubernetes.default.svc.cluster.local.\""
```
说x509:无法分析dnsname的kubernetes.default.svc.cluster.local。
遂进入Prometheus容器查看了/var/run/secrets/kubernetes.io/serviceaccount/ca.crt文件，文件内容与ca.pem一致未发现问题，且在容器内使用nslookuplookup解析集群内外域名都没问题。
集群dashboard插件、metrics-server插件、dns插件都正常部署成功。
Prometheus的yaml文件为kubernetes-server-linux-amd64.tar.gz包下cluster/addons/prometheus目录里的prometheus-configmap.yaml  prometheus-rbac.yaml  prometheus-service.yaml  prometheus-statefulset.yaml文件只改了一下动态供给卷和NodePort端口其他未动

求大神帮忙check一下

**Comment by JohnnyHL** [comment]
关于X509证书问题，多数情况下去看下你的集群安装组件是否用到自己配置的TLS认证证书和秘钥；注意查看一下你的kubernetes-csr.json文件中配置是否正确，集群节点ip、虚IP那些什么的；还有就是检查一下你的dnsName配置是否正确，日志显示无法解析你配置的dnsName


------------------ 原始邮件 ------------------
发件人: "leiyz"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 下午3:18
收件人: "opsnull/follow-me-install-kubernetes-cluster"<follow-me-install-kubernetes-cluster@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [opsnull/follow-me-install-kubernetes-cluster] Prometheus服务器分析证书失败：x509:无法分析dnsname \“kubernetes.default.svc.cluster.local.\“ (#513)




文档版本
 参考v1.14.x 部署 1.14.2 版本k8s集群
 现象描述
 大神您推荐的Prometheus监控方案，在部署后Prometheus容器日志报错
 level=error ts=2019-08-21T03:55:55.423167788Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:316: Failed to list *v1.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName \"kubernetes.default.svc.cluster.local.\"" level=error ts=2019-08-21T03:55:55.50406166Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:296: Failed to list *v1.Pod: Get https://10.254.0.1:443/api/v1/pods?resourceVersion=0: tls: failed to parse certificate from server: x509: cannot parse dnsName \"kubernetes.default.svc.cluster.local.\""  
说x509:无法分析dnsname的kubernetes.default.svc.cluster.local。
 遂进入Prometheus容器查看了/var/run/secrets/kubernetes.io/serviceaccount/ca.crt文件，文件内容与ca.pem一致未发现问题，且在容器内使用nslookuplookup解析集群内外域名都没问题。
 集群dashboard插件、metrics-server插件、dns插件都正常部署成功。
 Prometheus的yaml文件为kubernetes-server-linux-amd64.tar.gz包下cluster/addons/prometheus目录里的prometheus-configmap.yaml  prometheus-rbac.yaml  prometheus-service.yaml  prometheus-statefulset.yaml文件只改了一下动态供给卷和NodePort端口其他未动
 
求大神帮忙check一下

**Comment by opsnull** [comment]
理论上 K8S  1.14.2 包含的 prometheus 镜像已经是 go 1.10.3 以后的版本编译的，不应该有这个问题。
可以参考：https://github.com/opsnull/follow-me-install-kubernetes-cluster/issues/151#issuecomment-401797628

**Comment by fanslinux** [comment]
已解决，默认的普罗米修斯镜像版本为v2.2.1，可能会出现go1.10.*的X509证书问题，将镜像版本更新到v2.3.1此问题解决，谢谢大神帮忙！

**Comment by tanmx** [comment]
@fanslinux 请问是参考哪篇文章安装的 Prometheus ？
