### ISSUE TITLE
09-4.EFK插件.md中elasticsearch-logging-0没成功产生（把yaml文件中的gcr.io替换为gcr.azk8s.cn即可，已解决）

### ISSUE THREAD

**Issue by qulz1988** [opsnull/follow-me-install-kubernetes-cluster#515]
**文档版本**

`[root@master fluentd-elasticsearch]# kubectl get pods -n kube-system -o wide|grep -E 'elasticsearch|fluentd|kibana'
elasticsearch-logging-0                 0/1     ErrImagePull   0          9s      172.30.16.5    master   <none>           <none>
fluentd-es-v2.4.0-5cz7b                 1/1     Running        0          92m     172.30.16.6    master   <none>           <none>
fluentd-es-v2.4.0-5wddh                 1/1     Running        0          92m     172.30.176.6   node1    <none>           <none>
fluentd-es-v2.4.0-msc6h                 1/1     Running        0          92m     172.30.192.5   node2    <none>           <none>
kibana-logging-f4d99b69f-796dz          1/1     Running        0          92m     172.30.16.7    master   <none>           <none>
[root@master fluentd-elasticsearch]# kubectl -n kube-system describe pod elasticsearch-logging-0
Name:               elasticsearch-logging-0
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               master/192.168.63.120
Start Time:         Sat, 24 Aug 2019 02:17:11 +0800
Labels:             controller-revision-hash=elasticsearch-logging-67676f5975
                    k8s-app=elasticsearch-logging
                    kubernetes.io/cluster-service=true
                    statefulset.kubernetes.io/pod-name=elasticsearch-logging-0
                    version=v6.6.1
Annotations:        <none>
Status:             Pending
IP:                 172.30.16.5
Controlled By:      StatefulSet/elasticsearch-logging
Init Containers:
  elasticsearch-logging-init:
    Container ID:  docker://c10f5ed2992b76cd064b93062e47aaf7543d224a5cf2c9e30bce0e7c6275d15a
    Image:         alpine:3.6
    Image ID:      docker-pullable://alpine@sha256:66790a2b79e1ea3e1dabac43990c54aca5d1ddf268d9a5a0285e4167c8b24475
    Port:          <none>
    Host Port:     <none>
    Command:
      /sbin/sysctl
      -w
      vm.max_map_count=262144
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 24 Aug 2019 02:17:13 +0800
      Finished:     Sat, 24 Aug 2019 02:17:13 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from elasticsearch-logging-token-r8dq2 (ro)
Containers:
  elasticsearch-logging:
    Container ID:   
    Image:          gcr.io/fluentd-elasticsearch/elasticsearch:v6.6.1
    Image ID:       
    Ports:          9200/TCP, 9300/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:  1
    Requests:
      cpu:  100m
    Environment:
      NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /data from elasticsearch-logging (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from elasticsearch-logging-token-r8dq2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  elasticsearch-logging:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  elasticsearch-logging-token-r8dq2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  elasticsearch-logging-token-r8dq2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 360s
                 node.kubernetes.io/unreachable:NoExecute for 360s
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  17s               default-scheduler  Successfully assigned kube-system/elasticsearch-logging-0 to master
  Normal   Pulled     15s               kubelet, master    Container image "alpine:3.6" already present on machine
  Normal   Created    15s               kubelet, master    Created container elasticsearch-logging-init
  Normal   Started    15s               kubelet, master    Started container elasticsearch-logging-init
  Warning  Failed     13s               kubelet, master    Failed to pull image "gcr.io/fluentd-elasticsearch/elasticsearch:v6.6.1": rpc error: code = Unknown desc = Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
  Warning  Failed     13s               kubelet, master    Error: ErrImagePull
  Normal   BackOff    13s               kubelet, master    Back-off pulling image "gcr.io/fluentd-elasticsearch/elasticsearch:v6.6.1"
  Warning  Failed     13s               kubelet, master    Error: ImagePullBackOff
  Normal   Pulling    1s (x2 over 14s)  kubelet, master    Pulling image "gcr.io/fluentd-elasticsearch/elasticsearch:v6.6.1"
[root@master fluentd-elasticsearch]# docker pull gcr.io/fluentd-elasticsearch/elasticsearch:v6.6.1
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
[root@master fluentd-elasticsearch]# docker pull elasticsearch:v6.6.1
Error response from daemon: manifest for elasticsearch:v6.6.1 not found
[root@master fluentd-elasticsearch]# `
**现象描述**
描述问题的现象。

**Comment by opsnull** [comment]
看起来是你没有权限从gcr.io 拉取镜像，可以试试 docker.elastic.co/elasticsearch/elasticsearch:6.6.1
