### ISSUE TITLE
官方二进制安装docker的一个问题

### ISSUE THREAD

**Issue by q1054261752** [opsnull/follow-me-install-kubernetes-cluster#521]
**文档版本**

https://docs.docker.com/install/linux/docker-ce/binaries/#install-daemon-and-client-binaries-on-linux

A properly mounted cgroupfs hierarchy; a single, all-encompassing cgroup mount point is not sufficient. See Github issues #2683, #3485, #4568).
官方文档里的这个先觉条件是干什么的，有什么用啊，  properly mounted 链接里的脚步，需要运行吗？

**现象描述**
描述问题的现象。

**Comment by opsnull** [comment]
默认的 Centos 7 和 Ubuntu 环境没有这个问题，不需要调整。
