### ISSUE TITLE
关于1.14文档中http和https检测集群健康状态的2个小问题

### ISSUE THREAD

**Issue by l3950809** [opsnull/follow-me-install-kubernetes-cluster#524]
**文档版本**
参考文档版本v1.14，应该是最新的吧，文档链接如下：https://github.com/opsnull/follow-me-install-kubernetes-cluster

**现象描述**
我想提的问题有2个
问题一：确认是否无法通过kubectl get componentstatuses检测集群组件的健康状态，因为默认是使用http去curl127.0.0.1的端口，而在文档在编译nginx的时候，就without了http的模块，只接收https的协议，报错图如下
![image](https://user-images.githubusercontent.com/38310692/65144480-4ecb1a80-d9cc-11e9-93e2-3a8177c9759f.png)

问题二：在06-4的文档中，检测scheduler状态，明明监听的ip是172.27.137.240，却可以通过127.0.0.1去拿到数据，这是如何实现的呢？ 截图如下
![image](https://user-images.githubusercontent.com/38310692/65144785-e03a8c80-d9cc-11e9-8e82-94e37ac98779.png)

**Comment by opsnull** [comment]
问题1 ：那个 check 是 apiserver 自己做的，所以不需要通过 nginx 代理。
问题2：多谢反馈，文档已修正。
