### ISSUE TITLE
kube-nginx 连接数和 kube-apiserver max-request-inflight 数量的关系

### ISSUE THREAD

**Issue by blackpiglet** [opsnull/follow-me-install-kubernetes-cluster#525]
**文档版本**
v1.14

**现象描述**
kube-nginx 的配置文件中指定了连接数是 1024:
worker_connections  1024;

kube-apiserver 中则配置最大并发请求数为 4000；
--max-requests-inflight=4000
NGINX 的后端对应是三个 kube-apiserver，也就是说最大支持 12000 并发，这样配置 kube-nginx 会不会成为瓶颈？是否需要调大连接数？

**Comment by opsnull** [comment]
max-requests-inflight 并不是最大连接，而是 apiserver 当前正在处理的请求数量。
由于有长连接，这些请求可能是很少几个 client （实际就本节点的 kubelet 进程）发起的。所以不需要调整 nginx 的连接数。
