### ISSUE TITLE
第六章文档描述有问题

### ISSUE THREAD

**Issue by nameless1987** [opsnull/follow-me-install-kubernetes-cluster#527]
**文档版本**
第六章

**现象描述**
本章指导安装apiservice
但还没有部署的时候 文中提示需要kubectl get svc 
这个命令当时是执行不了的

**Comment by opsnull** [comment]
请留意：
![image](https://user-images.githubusercontent.com/433567/66700084-55c12080-ed1f-11e9-887c-f7574af6216c.png)
