### ISSUE TITLE
kube-controller-manager 总是自动重启

### ISSUE THREAD

**Issue by emg2012-emg** [opsnull/follow-me-install-kubernetes-cluster#528]
**文档版本**
k8s 二进制方式部署，版本v1.14.6

**现象描述**
kube-controller-manager 部署成功后，可以正常启动，但是过一段时间报错如下：
Oct 09 10:11:10 k8s-master1 kube-controller-manager[29203]: I1009 10:11:10.274374   29203 flags.go:33] FLAG: --unhealthy-zone-threshold="0.55"
Oct 09 10:11:10 k8s-master1 kube-controller-manager[29203]: I1009 10:11:10.274378   29203 flags.go:33] FLAG: --use-service-account-credentials="true"
Oct 09 10:11:10 k8s-master1 kube-controller-manager[29203]: I1009 10:11:10.274381   29203 flags.go:33] FLAG: --v="2"
Oct 09 10:11:10 k8s-master1 kube-controller-manager[29203]: I1009 10:11:10.274384   29203 flags.go:33] FLAG: --version="false"
Oct 09 10:11:10 k8s-master1 kube-controller-manager[29203]: I1009 10:11:10.274390   29203 flags.go:33] FLAG: --vmodule=""
Oct 09 10:11:10 k8s-master1 kube-controller-manager[29203]: I1009 10:11:10.675155   29203 controllermanager.go:155] Version: v1.14.6
Oct 09 10:11:10 k8s-master1 kube-controller-manager[29203]: I1009 10:11:10.675771   29203 secure_serving.go:116] Serving securely on 192.168.2.120:10252
Oct 09 10:11:10 k8s-master1 kube-controller-manager[29203]: I1009 10:11:10.675870   29203 leaderelection.go:217] attempting to acquire leader lease  kube-system/kube-controller-manager...
Oct 09 10:31:07 k8s-master1 kube-controller-manager[29203]: E1009 10:31:05.404438   29203 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: Get https://192.168.2.240:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Oct 09 10:31:17 k8s-master1 kube-controller-manager[29203]: E1009 10:31:17.930755   29203 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: Get https://192.168.2.240:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers

kube-controller-manager 会自动重启，请问这个应该怎么解决？

**Comment by opsnull** [comment]
> Oct 09 10:31:07 k8s-master1 kube-controller-manager[29203]: E1009 10:31:05.404438 29203 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: Get https://192.168.2.240:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

看起来是连接 apiserver 失败导致的，看看 apiserver 是否正常运行，是否有防火墙策略阻挡等。

**Comment by emg2012-emg** [comment]
运行正常，防护墙没有阻挡策略， “context deadline exceeded”  请问k8s 上下文内容有过期时间吗？

**Comment by emg2012-emg** [comment]
虚拟机资源不够，造成进程异常重启
