### ISSUE TITLE
kubectl第六章部署api 命令报错

### ISSUE THREAD

**Issue by qishuowen** [opsnull/follow-me-install-kubernetes-cluster#529]
**文档版本*
 K8S 版本，v1.14.3

**现象描述**
在 kube-controller-manager 启动文件有  --port=0  和--secure-port=10252 时  连接拒绝
kubectl get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused   
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused   
etcd-1               Healthy     {"health":"true"}                                                                           
etcd-0               Healthy     {"health":"true"}                                                                           
etcd-2               Healthy     {"health":"true"}

去掉这两个参数 重启 controller，正常
 vim /etc/systemd/system/kube-controller-manager.service 
[root@qsw-k8s01 work]# systemctl  daemon-reload 
[root@qsw-k8s01 work]# systemctl  restart kube-controller-manager.service 
[root@qsw-k8s01 work]# kubectl get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused   
controller-manager   Healthy     ok                                                                                          
etcd-0               Healthy     {"health":"true"}                                                                           
etcd-2               Healthy     {"health":"true"}                                                                           
etcd-1               Healthy     {"health":"true"}

是什么问题造成的，都这样还是我的操作问题

**Comment by opsnull** [comment]
应该是正常情况，参考第六章文档对这个现象的说明。
