### ISSUE TITLE
curl 10252/metrics  输出问题

### ISSUE THREAD

**Issue by qishuowen** [opsnull/follow-me-install-kubernetes-cluster#530]
**文档版本**
v1.14。

**现象描述**
curl输出和文档不一致，那个error  是什么 这个有影响吗
curl -s --cacert /opt/k8s/work/ca.pem --cert /opt/k8s/work/admin.pem --key /opt/k8s/work/admin-key.pem https://10.100.2.163:10252/metrics  |head
# HELP apiserver_audit_event_total Counter of audit events generated and sent to the audit backend.
# TYPE apiserver_audit_event_total counter
apiserver_audit_event_total 0
# HELP apiserver_audit_requests_rejected_total Counter of apiserver requests rejected due to an error in audit logging backend.
# TYPE apiserver_audit_requests_rejected_total counter
apiserver_audit_requests_rejected_total 0
# HELP apiserver_client_certificate_expiration_seconds Distribution of the remaining lifetime on the certificate used to authenticate a request.
# TYPE apiserver_client_certificate_expiration_seconds histogram
apiserver_client_certificate_expiration_seconds_bucket{le="0"} 0
apiserver_client_certificate_expiration_seconds_bucket{le="1800"} 0

**Comment by opsnull** [comment]
没影响，那个 error 是统计指标的描述。
