### ISSUE TITLE
请问题一个问题，为什么没有看到配置cni？kubelet是怎么创建pod网络的？

### ISSUE THREAD

**Issue by malixian** [opsnull/follow-me-install-kubernetes-cluster#532]
根据文档已经成功搭建好集群，由于设计容器运行时的切换，将一节点的运行时切换成了singularity，出现了不能创建网络的错误。
`could not get networks: no net configurations found in /etc/cni/net.d`
后来想了一下，安装过程好像没有cni的设置，那么kubelet在创建pod网络的时候所需要的二进制文文件与/etc/cni/net.d文件也没有，但是通过测试在运行时不切换并且全部是docker的情况下kubelet可以成功创建pod，并且pod之间可以通信。想问一下大佬们这里面原理是啥？

**Comment by khs1994** [comment]
容器运行时是 Docker ,网络是由 Docker 管理的。其他运行时是由 CNI 负责的，本项目运行时是 Docker ，所以也就没有 CNI 这方面的内容。

**Comment by malixian** [comment]
> 容器运行时是 Docker ,网络是由 Docker 管理的。其他运行时是由 CNI 负责的，本项目运行时是 Docker ，所以也就没有 CNI 这方面的内容。

了解了，感谢答复～
