### ISSUE TITLE
kubectl top node   报错：Error from server (ServiceUnavailable):

### ISSUE THREAD

**Issue by emg2012-emg** [opsnull/follow-me-install-kubernetes-cluster#534]
**文档版本**
k8s  v1.14.6  metric-server 1.8+

**现象描述**
metric-server pod 运行正常，但是执行kubectl top node 提示错误如下：
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)

**Comment by emg2012-emg** [comment]
kube-apiserver 启动参数没有添加--enable-aggregator-routing=true  ，添加完重启kube-apiserver问题解决

**Comment by Lincoln-audi** [comment]
E1026 22:43:54.177784   87378 available_controller.go:407] v1beta1.metrics.k8s.io failed with: failing or missing response from https://172.25.25.32:443: bad status from https://172.25.25.32:443: 403
Oct 26 22:43:55 k8s-node01 kube-controller-manager: E1026 22:43:55.751882  119388 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
服务403  kubectl top node 不行
