### ISSUE TITLE
some bug tips

### ISSUE THREAD

**Issue by lannyMa** [opsnull/follow-me-install-kubernetes-cluster#54]
# 01,   07-部署Node节点.md
 ls -l /etc/kubernetes/kubelet.kubeconfig  kubenet请求证书, 应该是master审批.  client生成证书的目录是
ls -l /etc/kubernetes/ssl/  是不是写错了?

# 02,  04-部署Kubectl命令行工具.md
admin.pem 证书 OU 字段值为 system:masters ...  这里OU应该是是O吧.

**Comment by opsnull** [comment]
> ls -l /etc/kubernetes/kubelet.kubeconfig kubenet请求证书, 应该是master审批. client生成证书的目录是
> ls -l /etc/kubernetes/ssl/ 是不是写错了?

文档没有问题，kubelet 的systemd unit 文件中 --cert-dir=/etc/kubernetes/ssl 参数指定了自动生成的证书目录。

> admin.pem 证书 OU 字段值为 system:masters ... 这里OU应该是是O吧.

已经fix了。
