### ISSUE TITLE
coredns部署后无法进入pod

### ISSUE THREAD

**Issue by onesafe** [opsnull/follow-me-install-kubernetes-cluster#540]
**文档版本**
master

**现象描述**

![图片](https://user-images.githubusercontent.com/4188127/67862439-15ee9b80-fb5d-11e9-956c-77722887e3c4.png)

![图片](https://user-images.githubusercontent.com/4188127/67862515-3159a680-fb5d-11e9-9f67-605b87429d09.png)

**Comment by opsnull** [comment]
这是由于主机名不能解析导致的。
参考 本文档在系统初始化一节，在各机器 /etc/hosts  文件添加解析的步骤即可解决。
