### ISSUE TITLE
在dashboard中进行具体容器点击运行命令会出现内嵌dashboard的情况

### ISSUE THREAD

**Issue by nameissoso** [opsnull/follow-me-install-kubernetes-cluster#542]
**文档版本**
master

**现象描述**
在dashboard中进行具体容器点击运行命令会出现内嵌dashboard的情况
![image](https://user-images.githubusercontent.com/30620921/67921573-2d706780-fbe3-11e9-8ef3-08db35ec7f83.png)

**Comment by nameissoso** [comment]
安装dashboard2.0.0 beta5可以解决此问题

**Comment by cheungfei** [comment]
我是在chrome没问题，在Firefox上面一直存在这个问题，2.0版本就OK了吗？
