### ISSUE TITLE
apiserver 问题

### ISSUE THREAD

**Issue by BlackSunday001** [opsnull/follow-me-install-kubernetes-cluster#545]
查看的是 k8s 1.42 版本的部署

这是我三台master的hosts文件

192.168.1.90 vip01 vip01.k8s.com
192.168.1.91 node01 node01.k8s.com
192.168.1.92 node02 node02.k8s.com
192.168.1.93 node03 node03.k8s.com

----------------------------------------------------------------------------------------------

在我部署完 kube-apiserver后，开始出现问题，如下：

[root@node01 work]# kubectl cluster-info dump
Error from server (BadRequest): the server rejected our request for an unknown reason (get nodes)

这里请求被拒绝了

查到
Make sure the resource group and name matches to what you created. Now if you type ‘kubectl get services’ or ‘kubectl get nodes’ it should display the services instead of ‘Error from server (BadRequest): the server rejected our request for an unknown reason’ which means that we haven’t yet download the credentials...

通过我个人判断以及查阅后的结果，判断应该是证书出现了问题，应该是kubernetes的证书

----------------------------------------------------------------------------------------------

下面是我在创建admin的时候用到的命令

kubectl config set-cluster kubernetes \
  --certificate-authority=/opt/k8s/work/ca.pem \
  --embed-certs=true \
  --server=vip01.k8s.com:8443 \    # 这里配置的是vip
  --kubeconfig=kubectl.kubeconfig

----------------------------------------------------------------------------------------------

这是我的 创建证书签名请求

[root@node01 work]# cat kubernetes-csr.json 
{
  "CN": "kubernetes",
  "hosts": [
    "127.0.0.1",
    "10.254.0.1",
    "192.168.1.90",
    "192.168.1.91",
    "192.168.1.92",
    "192.168.1.93",
    "vip01",
    "node01",
    "node02",
    "node03",
    "vip01.k8s.com",   # 这里配置了vip的域名
    "node01.k8s.com",
    "node02.k8s.com",
    "node03.k8s.com",
    "kubernetes",
    "kubernetes.default",
    "kubernetes.default.svc",
    "kubernetes.default.svc.cluster",
    "kubernetes.default.svc.cluster.local."
  ],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "CN",
      "ST": "BeiJing",
      "L": "BeiJing",
      "O": "k8s",
      "OU": "4Paradigm"
    }
  ]
}

----------------------------------------------------------------------------------------------

反复初始化环境后重新部署好几遍，也查询过google，目前还是没有解决，也重新生成证书好几遍了，

希望您看到后帮忙看下，非常感谢

**Comment by opsnull** [comment]
kubectl 的版本与 apiserver 一致么？

**Comment by BlackSunday001** [comment]
版本如下:

```
[root@node02 ~]# kube-apiserver --version
Kubernetes v1.14.2
[root@node02 ~]# kubelet --version
Kubernetes v1.14.2
```

经过测试，进群内所有的链接地址使用 IP，在部署完`kube-apiserver` 后，测试是正常的，跟您的教程一致

当我是用 不管是 `写hosts文件解析` 或者是 `部署BIND用DNS解析`，集群内的所有链接地址都是用域名的方式后，就会出现上述的问题。

**Comment by daniel-hutao** [comment]
同遇到此问题
