### ISSUE TITLE
执行kubectl命令报错

### ISSUE THREAD

**Issue by yongnights** [opsnull/follow-me-install-kubernetes-cluster#546]
**文档版本**
查看的是master主分支，使用的是软件版本分别如下：
Kubernetes v1.14.2
nginx-1.15.3
etcd-v3.3.13
flannel-v0.11.0

**现象描述**
按照文档进行操作的，在走到文档：06-2.apiserver集群时，在最后一步“检查集群信息”时执行如下命令报错：
[root@kube-node1 work]# kubectl cluster-info
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server localhost:8080 was refused - did you specify the right host or port?

文档中给的有解决方案，但是说的不是很明白，从头开始就只新建了一个docker用户，文档中执行的命令也都是使用root命令操作的，按照文档说的，都是在其中一个主机上进行操作，然后把相关文档分发到另外两台主机上的。

什么才是正确的账户？如何操作才能解决这个问题？

如下的这几个服务：etcd，flanneld，kube-apiserver，kube-nginx在三台主机上都是启动状态，除了主机IP和主机名跟文档中的不一样之外，其余的都是按照文档步骤来的，实在想不通哪儿出了问题？

百度查找解决办法，大部分都是执行如下的命令：
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

但是二进制安装的就没有admin.conf文件，并且config文件路径是/root/.kube目录下的，就算把这个文件安装命令操作，使用文档开头创建的docker账户，还是不行？？？？

**Comment by yongnights** [comment]
不用回复了，已经解决了。
解决思路如下：
kubectl 默认从 ~/.kube/config 配置文件获取访问 kube-apiserver 地址、证书、用户名等信息，如果没有配置该文件，执行命令时出错：The connection to the server localhost:8080 was refused - did you specify the right host or port?

经检查，在生成~/.kube/config文件过程中，因在途中修改过environment.sh文件，github提供的文件里面的参数跟网站上的https://www.orchome.com/652有不一样的，造成生成该文件时，KUBE_APISERVER是空的，造成该文件没有这个地址，后来手动添加上就可以执行kubectl命令了。

**Comment by 852438143** [comment]
您好，关于您的回答中
“ https://www.orchome.com/652有不一样的，造成生成该文件时，KUBE_APISERVER是空的，造成该文件没有这个地址，后来手动添加上就可以执行kubectl命令了。”
这句话是否表示 /root/.kube/config 文件中这个参数 clusters->cluster-> server 没有值呀。

**Comment by 852438143** [comment]
不用回答了，因为kube-apiserver.service文件中 insecure-port=0禁用了8080端口，设置为insecure-port=8080，就可以正常访问了
