### ISSUE TITLE
文档中有一处需要完善的地方

### ISSUE THREAD

**Issue by yongnights** [opsnull/follow-me-install-kubernetes-cluster#551]
**文档版本**
master分支 v1.14.2

**现象描述**
文章目录标题跟具体文档中的标题不匹配

https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/09-3.metrics-server%E6%8F%92%E4%BB%B6.md

文章目录标题是：09-3.metrics-server插件.md，但是内容标题是：09-4.部署 metrics-server 插件

https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/09-4.EFK%E6%8F%92%E4%BB%B6.md

文章目录标题是：09-4.EFK插件.md，但是内容标题是09-5.部署 EFK 插件

**Comment by opsnull** [comment]
谢谢反馈！
