### ISSUE TITLE
文档中需要完善的地方

### ISSUE THREAD

**Issue by yongnights** [opsnull/follow-me-install-kubernetes-cluster#552]
**文档版本**
master分支 v1.14.2

**现象描述**
文档：部署 EFK 插件，修改配置文件中
除了fluentd-es-ds.yaml 文件修改path地址外：
把path: /var/lib/docker/containers修改成 path: /data/k8s/docker/data/containers/

还需要修改es-statefulset.yaml文件：
尤其是这个文件，个别内容是错误的，具体如下：

    spec:
      serviceAccountName: elasticsearch-logging
      containers:
      - image: gcr.io/fluentd-elasticsearch/elasticsearch:v6.6.1
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:

把其中的name和image需要修改一下才行
    spec:
      serviceAccountName: elasticsearch-logging
      containers:
        name: elasticsearch-logging
          - image: gcr.io/fluentd-elasticsearch/elasticsearch:v6.6.1
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:

另外，使用的这个镜像gcr.io/fluentd-elasticsearch/elasticsearch:v6.6.1 在微软中国提供的 gcr.io 免费代理镜像中找不到这个镜像，这个镜像使用的是哪一个，还请告知一下。

**Comment by opsnull** [comment]
源文件没有问题。
elasticsearch 的镜像问题可以自行 Google。
