### ISSUE TITLE
kubelet 启动参数--allow-privileged报错

### ISSUE THREAD

**Issue by IamEricqi** [opsnull/follow-me-install-kubernetes-cluster#555]
**文档版本**
master 分支：https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/07-2.kubelet.md

**现象描述**
在执行到 启动 kubelet 服务，启动kubelet报错：`k8s01 kubelet[14745]: F1116 11:03:04.058148   14745 server.go:156] unknown flag: --allow-privileged` 网上资料说不支持这个参数--allow-privileged 了？但是去掉后，再启动依然报错：`E1116 11:00:03.187036   13951 certificate_manager.go:400] Failed while requesting a signed certificate from the master: cannot create certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User "system:bootstrap:s6j13w" cannot create resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope
` 请大神赐教！！

**Comment by IamEricqi** [comment]
难道是apiserver证书过期了？是前天部署的。

**Comment by khs1994** [comment]
可能是以下两个问题

* https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/07-2.kubelet.md#%E5%88%9B%E5%BB%BA-kubelet-bootstrap-kubeconfig-%E6%96%87%E4%BB%B6

> token 有效期为 1 天，超期后将不能再被用来 boostrap kubelet，且会被 kube-controller-manager 的 tokencleaner 清理 这个根据提示重新生成

* https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/07-2.kubelet.md#bootstrap-token-auth-%E5%92%8C%E6%8E%88%E4%BA%88%E6%9D%83%E9%99%90

> 根据提示绑定

**Comment by IamEricqi** [comment]
原来是版本15有这个bug，用14就好了。还要顺便提一下，在“09-4.EFK插件.md”中，es和kibana的image地址也需要修改的。
