### ISSUE TITLE
08.验证集群功能--创建测试文件，pod一直处于 ContainerCreating状态

### ISSUE THREAD

**Issue by xiahuhu1** [opsnull/follow-me-install-kubernetes-cluster#559]
**文档版本**
K8S 版本，1.14.3
当前使用的版本是1.13.6
**现象描述**
在验证集群功能--创建测试文件，pod一直处于 ContainerCreating状态
[root@xiahuhu-k8s01 work]# kubectl get nodes
NAME            STATUS   ROLES    AGE   VERSION
xiahuhu-k8s01   Ready    <none>   31m   v1.13.6
xiahuhu-k8s02   Ready    <none>   31m   v1.13.6
xiahuhu-k8s03   Ready    <none>   31m   v1.13.6

[root@xiahuhu-k8s01 work]# kubectl get pods  -o wide|grep nginx-ds
nginx-ds-4tkn4   0/1     ContainerCreating   0          12m   <none>   xiahuhu-k8s03   <none>           <none>
nginx-ds-h44xz   0/1     ContainerCreating   0          12m   <none>   xiahuhu-k8s01   <none>           <none>
nginx-ds-vf4rp   0/1     ContainerCreating   0          12m   <none>   xiahuhu-k8s02   <none>           <none>

错误日志：
11月 23 12:13:43 xiahuhu-k8s01 kubelet[45480]: E1123 12:13:43.393891   45480 kuberuntime_manager.go:662] createPodSandbox for pod "nginx-ds-h44xz_default(aca72c00-0da6-11ea-8f60-000c29b3b3d5)" failed: rpc error: code = Unknown desc = failed pulling image "registry.cn-beijing.aliyuncs.com/k8s_images/pause-amd64:3.1": Error response from daemon: pull access denied for registry.cn-beijing.aliyuncs.com/k8s_images/pause-amd64, repository does not exist or may require 'docker login'
11月 23 12:13:43 xiahuhu-k8s01 kubelet[45480]: E1123 12:13:43.393945   45480 pod_workers.go:190] Error syncing pod aca72c00-0da6-11ea-8f60-000c29b3b3d5 ("nginx-ds-h44xz_default(aca72c00-0da6-11ea-8f60-000c29b3b3d5)"), skipping: failed to "CreatePodSandbox" for "nginx-ds-h44xz_default(aca72c00-0da6-11ea-8f60-000c29b3b3d5)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-ds-h44xz_default(aca72c00-0da6-11ea-8f60-000c29b3b3d5)\" failed: rpc error: code = Unknown desc = failed pulling image \"registry.cn-beijing.aliyuncs.com/k8s_images/pause-amd64:3.1\": Error response from daemon: pull access denied for registry.cn-beijing.aliyuncs.com/k8s_images/pause-amd64, repository does not exist or may require 'docker login'"
//pause-amd64容器无法下载？麻烦大佬看下是什么问题。

**Comment by mdh67899** [comment]
@xiahuhu1 你使用的pause镜像地址写错了。
<pre>
正确的镜像地址：registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1
你用的镜像地址：registry.cn-beijing.aliyuncs.com/k8s_images/pause-amd64:3.1
</pre>

**Comment by xiahuhu1** [comment]
> @xiahuhu1 你使用的pause镜像地址写错了。
> 
> 正确的镜像地址：registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1
> 你用的镜像地址：registry.cn-beijing.aliyuncs.com/k8s_images/pause-amd64:3.1
