### ISSUE TITLE
创建完kube-api集群发现总是提示我Unable to connect to the server:EOF

### ISSUE THREAD

**Issue by SirBlues** [opsnull/follow-me-install-kubernetes-cluster#568]
kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF
kubectl cluster-info dump
Unable to connect to the server: EOF
 ubectl get componentstatuses
-bash: ubectl: command not found
kubectl get componentstatuses
Unable to connect to the server: EOF
 netstat -lnpt|grep kube
tcp        0      0 172.16.10.24:6443       0.0.0.0:*               LISTEN      5442/kube-apiserver 

kubectl create clusterrolebinding kube-apiserver:kubelet-apis --clusterrole=system:kubelet-api-admin --user kubernetes
Unable to connect to the server: EOF
我所有api的节点运行状态都是正常的，也没有任何错误日志。求解

**Comment by opsnull** [comment]
和 #569  重复。
