### ISSUE TITLE
kubelet 无法正常启动，  谢谢

### ISSUE THREAD

**Issue by DavenAaron** [opsnull/follow-me-install-kubernetes-cluster#57]
May 12 16:40:37 node82 kubelet: error: failed to run Kubelet: cannot create certificate signing request: the server has asked for the client to provide credentials (post certificatesigningrequests.certificates.k8s.io)
May 12 16:40:37 node82 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
May 12 16:40:37 node82 systemd: Unit kubelet.service entered failed state.
May 12 16:40:37 node82 systemd: kubelet.service failed.
May 12 16:40:42 node82 systemd: kubelet.service holdoff time over, scheduling restart.
May 12 16:40:42 node82 systemd: Started Kubernetes Kubelet.
May 12 16:40:42 node82 systemd: Starting Kubernetes Kubelet...
May 12 16:40:42 node82 kubelet: I0512 16:40:42.530619   39763 feature_gate.go:144] feature gates: map[]
May 12 16:40:42 node82 kubelet: I0512 16:40:42.530701   39763 bootstrap.go:58] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file
May 12 16:40:42 node82 kubelet: error: failed to run Kubelet: cannot create certificate signing request: the server has asked for the client to provide credentials (post certificatesigningrequests.certificates.k8s.io)
May 12 16:40:42 node82 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
May 12 16:40:42 node82 systemd: Unit kubelet.service entered failed state.
May 12 16:40:42 node82 systemd: kubelet.service failed.

**Comment by opsnull** [comment]
> May 12 16:40:37 node82 kubelet: error: failed to run Kubelet: cannot create certificate signing request: the server has asked for the client to provide credentials (post certificatesigningrequests.certificates.k8s.io)

kublet 的 bootstrap kubeconfig 中 token 和 kube-apiserver 的 token.csv 不一致或者没有添加文档中说明的 rolebinding；

**Comment by it2911** [comment]
我也遇到同样问题，是不是kubelet的文档出现了问题？

**Comment by DavenAaron** [comment]
证书的问题，  重新生成下吧


------------------ 原始邮件 ------------------
发件人: "it2911";<notifications@github.com>;
发送时间: 2017年5月15日(星期一) 上午7:52
收件人: "opsnull/follow-me-install-kubernetes-cluster"<follow-me-install-kubernetes-cluster@noreply.github.com>; 
抄送: "简单、平凡、 执着"<86962983@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [opsnull/follow-me-install-kubernetes-cluster] kubelet 无法正常启动， 谢谢 (#57)




我也遇到同样问题，是不是kubelet的文档出现了问题？
