### ISSUE TITLE
flannel网络配置未全部改动到位，请更新下

### ISSUE THREAD

**Issue by cheungfei** [opsnull/follow-me-install-kubernetes-cluster#576]
**文档版本**
文档分支master。

**现象描述**
#561 建议修改子网长度，但是配置文件里面没有同步修改：
mk ${FLANNEL_ETCD_PREFIX}/config '{"Network":"'${CLUSTER_CIDR}'", "SubnetLen": 21, "Backend": {"Type": "vxlan"}}'

这里也需要修改的

**Comment by opsnull** [comment]
Done
