### ISSUE TITLE
安装 calico 后 etcd 出现故障

### ISSUE THREAD

**Issue by lluxury** [opsnull/follow-me-install-kubernetes-cluster#579]
**文档版本**
说明你查看的是哪个 branch 的文档，即 K8S 版本，如 v1.8、v1.12。
按照 16.6 的版本搭建的，前面一直很顺利，各种测试都和文中描述一致。
其中安装etcd 后也做了各种测试，均输出正常。

然后 安装 calico 后，集群出现卡顿，命令提交失败，排查之后发现 etcd 出现故障。

**现象描述**
描述问题的现象。

已解决，服务器系统性能太差，抱歉^^ 

另外请问一下，以上部署全是针对master的，想部署其它 Node 节点的话，要如何操作，貌似直接用 Worker 部分的内容不是很方便，我自己改掉了

另外，小小支持一下，请继续加油

**Comment by wulixu** [comment]
我也遇到类似的情况
![image](https://user-images.githubusercontent.com/3402267/109809573-67cc9780-7c63-11eb-9c8b-ea871242b5e9.png)
![Uploading image.png…]()
