### ISSUE TITLE
kube-apiserver 启动失败 

### ISSUE THREAD

**Issue by sun51036** [opsnull/follow-me-install-kubernetes-cluster#587]
**文档版本**
v1.16.6

**现象描述**
启动kube-apiserver报错

报错信息：
Error: error while parsing encryption provider configuration file "/etc/kubernetes/encryption-config.yaml": could not obtain secret for named key key1: illegal base64 data at input byte 0

encryption-config.yaml
kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ${ENCRYPTION_KEY} 
      - identity: {}

**Comment by opsnull** [comment]
看起来是创建的 /etc/kubernetes/encryption-config.yaml 文件格式不对，请校验下。
