### ISSUE TITLE
kubelet加入集群时的文档小建议

### ISSUE THREAD

**Issue by guleng** [opsnull/follow-me-install-kubernetes-cluster#588]
**文档版本**
目前的master分支
k8s:v1.16.6

我遇到的坑是：生成kubelet bootstrap kubeconfig的时用的token是博主的变量文件里的BOOTSTRAP_TOKEN 来生成了bootstrap kubeconfig，还按照步骤用kubeadm生成了节点的 token，这样启动会报一下的报错。建议把变量文件的BOOTSTRAP_TOKEN 删除处理

![image](https://user-images.githubusercontent.com/40238640/80362465-4a95a280-88b5-11ea-98a9-eb768d8f01a0.png)
##

**现象描述**
kubelet启动后向 kubeconfig 写入的是 token ，但是向kube-controller-manager并未kubelet 创建 client 和 server 证书

kubeadm 为各节点创建的 token在的，未过期删除
![image](https://user-images.githubusercontent.com/40238640/80359180-0b188780-88b0-11ea-8898-d45109ba534f.png)

 kube-apiserver 访问 kubelet API 的权限clusterrolebinding和Bootstrap Token Auth权限已授权

启动kubelet未发现CSR
![image](https://user-images.githubusercontent.com/40238640/80361192-1d47f500-88b3-11ea-8231-d3e0da00eae3.png)

![image](https://user-images.githubusercontent.com/40238640/80361275-3c468700-88b3-11ea-8cde-3ebad859d492.png)

##
kube-proxy的ipvs模式模块儿永久化
# 永久生效
cat > /etc/sysconfig/modules/ipvs.modules <<EOF
modprobe -- ip_vs
modprobe -- ip_vs_rr
modprobe -- ip_vs_wrr
modprobe -- ip_vs_sh
modprobe -- nf_conntrack_ipv4
EOF

**Comment by opsnull** [comment]
你这个是 kubeadm 与本部署方式冲突的 case，需要手动删除下 token。
