### ISSUE TITLE
感谢！ 集群我搭建完了，参考issue问题都已解决，分享一个我见过的一个一键安装！

### ISSUE THREAD

**Issue by Mountains-and-rivers** [opsnull/follow-me-install-kubernetes-cluster#589]
相比之下。你这个更加详细，资助了你30块，后续加油！期待。。。。。。。。。。。。。。。

一键安装: https://github.com/fanux/sealos

**Comment by pinggit** [comment]
奇怪 我为什么总是退订不了 还在接受邮件？

**Comment by opsnull** [comment]
@Mountains-and-rivers 谢谢！
