### ISSUE TITLE
生成etcd 证书报错

### ISSUE THREAD

**Issue by OSMeteor** [opsnull/follow-me-install-kubernetes-cluster#59]
Failed to load config file: {"code":5200,"message":"failed to unmarshal configuration: unexpected end of JSON input"}Failed to parse input: unexpected end of JSON input

**Comment by opsnull** [comment]
> Failed to load config file:

配置文件 `/etc/kubernetes/ssl/ca-config.json` 内容或格式有误，参考 02-创建CA证书和秘钥.md
