### ISSUE TITLE
文档内没有关于各个模块内存占用的介绍

### ISSUE THREAD

**Issue by qq958905365** [opsnull/follow-me-install-kubernetes-cluster#592]
**文档版本**
master

**现象描述**
我给三台虚拟机分配的内存为1.5G,在搭建一半的时候关机了，重启过后发现有好几个模块出现out of memory的错误，我觉得文档补充一下各个模块的内存配置，还是有必要的

**Comment by opsnull** [comment]
多谢建议，后续会补充上。建议从 8C16G 100G 的机器资源开始尝试。
