### ISSUE TITLE
【更改集群中的SERVICE_CIDR网段】

### ISSUE THREAD

**Issue by xiahuhu1** [opsnull/follow-me-install-kubernetes-cluster#595]
**文档版本**
k8s版本：v1.14.2
**现象描述**
开始部署k8s集群设置环境变量的时候定义SERVICE_CIDR="10.254.0.0/16"，部署完成之后后面由于一些原因需要跟换这个网段为“10.10.0.0/16”，请问下这个网段可以修改吗，如果可以的话具体的步骤有哪些？

**Comment by opsnull** [comment]
需要修改：
1. 05-2.apiserver集群.md 的 CLUSTER_KUBERNETES_SVC_IP，重新生成 kubernetes 证书；
2. 05-3.controller-manager集群.md 和 05-2.apiserver集群.md 中的 SERVICE_CIDR，重启服务；
3. 08-2.coredns插件.md 中的 CLUSTER_DNS_SVC_IP，重建 coredns；
4. 删除所有已经存在的 Service 对象，重新创建。（可以先导出，删除 ClusterIP 后再创建）

**Comment by OneCodeMonkey** [comment]
> 需要修改：
> 
> 1. 05-2.apiserver集群.md 的 CLUSTER_KUBERNETES_SVC_IP，重新生成 kubernetes 证书；
> 2. 05-3.controller-manager集群.md 和 05-2.apiserver集群.md 中的 SERVICE_CIDR，重启服务；
> 3. 08-2.coredns插件.md 中的 CLUSTER_DNS_SVC_IP，重建 coredns；
> 4. 删除所有已经存在的 Service 对象，重新创建。（可以先导出，删除 ClusterIP 后再创建）

`CLUSTER_KUBERNETES_SVC_IP` 和 `CLUSTER_DNS_DOMAIN` 分别代表什么，文档中没看到样例配置，很困惑。。
