### ISSUE TITLE
kubernetes v1.16.6 文档存疑，求解答！

### ISSUE THREAD

**Issue by garrettdo** [opsnull/follow-me-install-kubernetes-cluster#596]
**文档版本**
kubernetes v1.16.6

**现象描述**
首先感谢大佬的无私奉献！！！敬礼！！！
跟着文档做到 08-2. 部署 coredns 插件，测试验证都无问题，因为很晚了，虚拟机就挂起了，电脑休眠，第二天开启的虚拟机再次验证集群功能时，无法成功验证；
当我尝试一台一台重启后，执行 **kubectl get nodes**
报错 **The connection to the server 192.168.128.231:6443 was refused - did you specify the right host or port?**

**建议**
可否添加故障排除以及版本升级方面的文档。

**Comment by opsnull** [comment]
kubectl 命令被 refused 的原因应该是对应节点（128.231）的 kube-apiserver 没有启动或在启动过程中。

这个文档偏向于 install 的，故障排除可以参考另外专门的文档：https://github.com/opsnull/kubernetes-troubleshooting-book
