### ISSUE TITLE
kubectl cluster-info无法查看到集群状态

### ISSUE THREAD

**Issue by GeekBoyDqz** [opsnull/follow-me-install-kubernetes-cluster#597]
**文档版本**
文档v1.16

**现象描述**
部署到05-2.apiserver集群，最后查看集群状态，提示如下提示，确实没有8443端口，这个该如何解决？之前
[root@k8s-master1 work]# kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?

[root@k8s-master1 work]# kubectl get all --all-namespaces
The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?

[root@k8s-master1 work]# kubectl get componentstatuses
The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?

**Comment by GeekBoyDqz** [comment]
问题已解决

**Comment by GZ315200** [comment]
这个是什么原因导致的呢？
