### ISSUE TITLE
遇到一个问题，我是这样解决的

### ISSUE THREAD

**Issue by amoyzhu** [opsnull/follow-me-install-kubernetes-cluster#60]
nginx的pod和svc创建好后，通过nodePort的方式访问即宿舍主机的ＩＰ加端口访问，不能访问，我是先把firewalld防火墙开启再关闭，然后重启kubelet服务，之后就可以通过ＩＰ加端口访问了。

**Comment by opsnull** [comment]
文档中有提示，部署node节点时关闭 firewalld，清空iptables规则；
