### ISSUE TITLE
calico

### ISSUE THREAD

**Issue by happyhelloworld** [opsnull/follow-me-install-kubernetes-cluster#601]
**文档版本**
master 
**现象描述**
calico在执行apply的时候起不来
The DaemonSet "calico-node" is invalid: spec.template.spec.containers[0].env[10].valueFrom: Invalid value: "": may not be sp
ecified when `value` is not empty

[root@nanhua-k8s-01 work]# diff calico.yaml.orig calico.yaml
3580c3580,3582
<             #   value: "192.168.0.0/16"
---
>               value: "172.30.0.0/16"
>             - name: IP_AUTODETECTION_METHOD
>               value: "interface=ens160"
3655c3657
<             path: /opt/cni/bin
---
>             path: /opt/k8s/bin
[root@nanhua-k8s-01 work]# 

[root@nanhua-k8s-01 work]# kubectl get pods -n kube-system -o wide
NAME                                       READY   STATUS    RESTARTS   AGE     IP       NODE     NOMINATED NODE   READINESS
 GATEScalico-kube-controllers-69cb4d4df7-drlqs   0/1     Pending   0          7m59s   <none>   <none>   <none>           <none>
[root@nanhua-k8s-01 work]#

[root@nanhua-k8s-01 work]# kubectl describe pod calico-kube-controllers-69cb4d4df7-drlqs -n kube-system
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't
 tolerate.  
 Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't  
 tolerate.

**Comment by noveluser** [comment]
我也遇到同样的问题，应该是calico.yaml和之前他们当初的文件不一致导致，但还没解决

**Comment by yevision94** [comment]
试下把 `- name: CALICO_IPV4POOL_CIDR` 前的注释去掉，我的去掉后，就可以起了

```bash
[root@k8s-master1 work]# diff calico.yaml.orig calico.yaml
3579,3580c3579,3580
<             # - name: CALICO_IPV4POOL_CIDR
<             #   value: "192.168.0.0/16"
---
>             - name: CALICO_IPV4POOL_CIDR
>               value: "172.30.0.0/16"
3581a3582,3583
>             - name: IP_AUTODETECTION_METHOD
>               value: "interface=ens33"
3649c3651
<             path: /opt/cni/bin
---
>             path: /opt/k8s/bin
```

**Comment by noveluser** [comment]
谢谢，问题解决了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Peyton Yip<mailto:notifications@github.com>
发送时间: 2020年7月14日 20:03
收件人: opsnull/follow-me-install-kubernetes-cluster<mailto:follow-me-install-kubernetes-cluster@noreply.github.com>
抄送: noveluser<mailto:flywangle@hotmail.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [opsnull/follow-me-install-kubernetes-cluster] calico (#601)


试下把 - name: CALICO_IPV4POOL_CIDR 前的注释去掉，我的去掉后，就可以起了

[root@k8s-master1 work]# diff calico.yaml.orig calico.yaml



3579,3580c3579,3580



<             # - name: CALICO_IPV4POOL_CIDR



<             #   value: "192.168.0.0/16"



---



>             - name: CALICO_IPV4POOL_CIDR



>               value: "172.30.0.0/16"



3581a3582,3583



>             - name: IP_AUTODETECTION_METHOD



>               value: "interface=ens33"



3649c3651



<             path: /opt/cni/bin



---



>             path: /opt/k8s/bin

―

**Comment by hurner** [comment]
在/etc/containerd/config.toml中使用registry.cn-beijing.aliyuncs.com/zhoujun/pause-amd64:3.1，或者干脆自己新建一个就ok了。

**Comment by fengjian1585** [comment]
没使用containerd,  还是使用的docker

**Comment by haiya512** [comment]
> **文档版本**
> master
> **现象描述**
> calico在执行apply的时候起不来
> The DaemonSet "calico-node" is invalid: spec.template.spec.containers[0].env[10].valueFrom: Invalid value: "": may not be sp
> ecified when `value` is not empty
> 
> ## [root@nanhua-k8s-01 work]# diff calico.yaml.orig calico.yaml
> 3580c3580,3582
> < # value: "192.168.0.0/16"
> > ```
> >           value: "172.30.0.0/16"
> >         - name: IP_AUTODETECTION_METHOD
> >           value: "interface=ens160"
> > ```
> 
> ## 3655c3657
> < path: /opt/cni/bin
> > ```
> >         path: /opt/k8s/bin
> > ```
> 
> [root@nanhua-k8s-01 work]#
> 
> [root@nanhua-k8s-01 work]# kubectl get pods -n kube-system -o wide
> NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS
> GATEScalico-kube-controllers-69cb4d4df7-drlqs 0/1 Pending 0 7m59s
> [root@nanhua-k8s-01 work]#
> 
> [root@nanhua-k8s-01 work]# kubectl describe pod calico-kube-controllers-69cb4d4df7-drlqs -n kube-system
> Events:
> Type Reason Age From Message
> 
> Warning FailedScheduling default-scheduler 0/3 nodes are available: 3 node(s) had taints that the pod didn't
> tolerate.
> Warning FailedScheduling default-scheduler 0/3 nodes are available: 3 node(s) had taints that the pod didn't
> tolerate.

我的这个解决了，根据楼上的提示@peytonyip 的方案

**Comment by haiya512** [comment]
> 在/etc/containerd/config.toml中使用registry.cn-beijing.aliyuncs.com/zhoujun/pause-amd64:3.1，或者干脆自己新建一个就ok了。

这个是怎么建的？没搞懂
