### ISSUE TITLE
calico在node节点上一直是Init:0/3

### ISSUE THREAD

**Issue by ShaPoHun** [opsnull/follow-me-install-kubernetes-cluster#612]
### pod的状态
[root@master1 ~]# kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS     RESTARTS   AGE
kube-system   calico-kube-controllers-c9784d67d-b6xkk   1/1     Running    6          4d22h
kube-system   calico-node-5wrk5                         0/1     Running    0          4d1h
kube-system   calico-node-6fm9g                         0/1     Init:0/3   0          3d22h
kube-system   calico-node-mdlfl                         1/1     Running    1          4d1h
kube-system   calico-node-wn5q7                         1/1     Running    2          4d1h

### calico日志信息
[root@master1 ~]# kubectl -n kube-system logs calico-node-6fm9g
Error from server (BadRequest): container "calico-node" in pod "calico-node-6fm9g" is waiting to start: PodInitializing

### calico pod event
................
..................
..................
Events:
  Type    Reason     Age    From            Message
  ----    ------     ----   ----            -------
  Normal  Scheduled  3d22h                  Successfully assigned kube-system/calico-node-6fm9g to node1
  Normal  Pulled     3d22h  kubelet, node1  Container image "calico/cni:v3.16.1" already present on machine
  Normal  Created    3d22h  kubelet, node1  Created container upgrade-ipam
  Normal  Started    3d22h  kubelet, node1  Started container upgrade-ipam

安装的calico，在master正常，在node一直在初始化

**Comment by xjjj064** [comment]
一起问下2020年9月27日搭建caclio时一直起不来：
[root@sjyt-k8s01 work]# kubectl get pods -n kube-system -o wide
NAME                                       READY   STATUS     RESTARTS   AGE   IP             NODE         NOMINATED NODE   READINESS GATES
calico-kube-controllers-54d4b4b69f-x9qwm   0/1     Pending    0          0s    <none>         <none>       <none>           <none>
calico-node-57hb6                          0/1     Init:0/3   0          1s    10.20.11.252   sjyt-k8s02   <none>           <none>
calico-node-hjcbk                          0/1     Init:0/3   0          1s    10.20.11.251   sjyt-k8s01   <none>           <none>
calico-node-x5z6f                          0/1     Init:0/3   0          1s    10.20.11.253   sjyt-k8s03   <none>           <none>

查看calico-kube-controllers-54d4b4b69f-x9qwm pod 显示下面的错误：
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  13s   default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.

看过另外一篇文章：
https://github.com/opsnull/follow-me-install-kubernetes-cluster/issues/601
但是并没有解决。。。。。
所有nodes 一直是NotReady 状态
[root@sjyt-k8s01 work]# kubectl get nodes
NAME         STATUS     ROLES    AGE     VERSION
sjyt-k8s01   NotReady   <none>   3h27m   v1.16.6
sjyt-k8s02   NotReady   master   3h27m   v1.16.6
sjyt-k8s03   NotReady   master   3h27m   v1.16.6

MD 测试环境这样搞没得问题，看来是换了一些东西了啊

**Comment by hurner** [comment]
在/etc/containerd/config.toml中使用registry.cn-beijing.aliyuncs.com/zhoujun/pause-amd64:3.1，或者干脆自己新建一个就ok了。

**Comment by fengjian1585** [comment]
> 确实发现了这个问题，calio-node 一直是init状态，在node节点docker logs查看container报错如下

2021-03-12 10:00:15.695 [INFO][1] migrate.go 65: checking host-local IPAM data dir dir existence...
2021-03-12 10:00:15.695 [INFO][1] migrate.go 72: retrieving node for IPIP tunnel address
2021-03-12 10:00:15.699 [INFO][1] migrate.go 80: IPIP tunnel address not found, assigning...
2021-03-12 10:00:15.703 [ERROR][1] ipam_plugin.go 95: failed to migrate ipam, retrying... error=PodCIDR  did not parse successfully: invalid CIDR address:  node="master2"
2021-03-12 10:00:16.704 [INFO][1] migrate.go 65: checking host-local IPAM data dir dir existence...
2021-03-12 10:00:16.704 [INFO][1] migrate.go 72: retrieving node for IPIP tunnel address
2021-03-12 10:00:16.708 [INFO][1] migrate.go 80: IPIP tunnel address not found, assigning...
2021-03-12 10:00:16.711 [ERROR][1] ipam_plugin.go 95: failed to migrate ipam, retrying... error=PodCIDR  did not parse successfully: invalid CIDR address:  node="master2"
2021-03-12 10:00:17.711 [INFO][1] migrate.go 65: checking host-local IPAM data dir dir existence...
2021-03-12 10:00:17.711 [INFO][1] migrate.go 72: retrieving node for IPIP tunnel address
2021-03-12 10:00:17.716 [INFO][1] migrate.go 80: IPIP tunnel address not found, assigning...
2021-03-12 10:00:17.720 [ERROR][1] ipam_plugin.go 95: failed to migrate ipam, retrying... error=PodCIDR  did not parse successfully: invalid CIDR address:  node="master2"
2021-03-12 10:00:18.721 [INFO][1] migrate.go 65: checking host-local IPAM data dir dir existence...
2021-03-12 10:00:18.721 [INFO][1] migrate.go 72: retrieving node for IPIP tunnel address
2021-03-12 10:00:18.725 [INFO][1] migrate.go 80: IPIP tunnel address not found, assigning...
2021-03-12 10:00:18.729 [ERROR][1] ipam_plugin.go 95: failed to migrate ipam, retrying... error=PodCIDR  did not parse successfully: invalid CIDR address:  node="master2"
2021-03-12 10:00:19.729 [INFO][1] migrate.go 65: checking host-local IPAM data dir dir existence...
2021-03-12 10:00:19.729 [INFO][1] migrate.go 72: retrieving node for IPIP tunnel address
2021-03-12 10:00:19.734 [INFO][1] migrate.go 80

**Comment by fengjian1585** [comment]
/etc/cni目录无法创建

**Comment by Crisescode** [comment]
大家最后都是怎么解决这个问题的呢？

**Comment by yanzuo0609** [comment]
[root@k8s01 work]# kubectl get pods -n kube-system -o wide
NAME                                       READY   STATUS     RESTARTS   AGE    IP               NODE         NOMINATED NODE   READINESS GATES
calico-kube-controllers-7986dc57c4-g5ztd   0/1     Pending    0          41s    <none>           <none>       <none>           <none>
calico-node-f6jsx                          0/1     Init:0/3   0          42s    
calico-node-jtspm                          0/1     Init:0/3   0          2s     
calico-node-sd56f                          0/1     Init:0/3   0          42s    
configure-calico-d2zh5                     0/1     Pending    0   
我也出现类似的问题，有解决方法了吗？？？

**Comment by yanzuo0609** [comment]
我的问题查到了，通过日志发现，是镜像地址有问题，无法下载导致的。

**Comment by haiya512** [comment]
> 我的问题查到了，通过日志发现，是镜像地址有问题，无法下载导致的。

那你怎么解决的呢？我也是看到了kubelet的日志

> May 26 14:40:49 zhangjun-k8s-03 kubelet[21054]: E0526 14:40:49.681093   21054 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
May 26 14:40:54 zhangjun-k8s-03 kubelet[21054]: E0526 14:40:54.682907   21054 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
May 26 14:40:59 zhangjun-k8s-03 kubelet[21054]: E0526 14:40:59.691938   21054 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
May 26 14:41:01 zhangjun-k8s-03 kubelet[21054]: I0526 14:41:01.590650   21054 kuberuntime_manager.go:409] No sandbox for pod "calico-node-2m84k_kube-system(0a1906ec-82a4-49a6-b8e9-0057637fbe1f)" can be found. Need to start a new one
May 26 14:41:02 zhangjun-k8s-03 kubelet[21054]: E0526 14:41:02.039482   21054 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to pull image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to pull and unpack image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to resolve reference "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
May 26 14:41:02 zhangjun-k8s-03 kubelet[21054]: E0526 14:41:02.039642   21054 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "calico-node-2m84k_kube-system(0a1906ec-82a4-49a6-b8e9-0057637fbe1f)" failed: rpc error: code = Unknown desc = failed to get sandbox image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to pull image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to pull and unpack image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to resolve reference "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
May 26 14:41:02 zhangjun-k8s-03 kubelet[21054]: E0526 14:41:02.039694   21054 kuberuntime_manager.go:710] createPodSandbox for pod "calico-node-2m84k_kube-system(0a1906ec-82a4-49a6-b8e9-0057637fbe1f)" failed: rpc error: code = Unknown desc = failed to get sandbox image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to pull image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to pull and unpack image "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": failed to resolve reference "registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
May 26 14:41:02 zhangjun-k8s-03 kubelet[21054]: E0526 14:41:02.039880   21054 pod_workers.go:191] Error syncing pod 0a1906ec-82a4-49a6-b8e9-0057637fbe1f ("calico-node-2m84k_kube-system(0a1906ec-82a4-49a6-b8e9-0057637fbe1f)"), skipping: failed to "CreatePodSandbox" for "calico-node-2m84k_kube-system(0a1906ec-82a4-49a6-b8e9-0057637fbe1f)" with CreatePodSandboxError: "CreatePodSandbox for pod \"calico-node-2m84k_kube-system(0a1906ec-82a4-49a6-b8e9-0057637fbe1f)\" failed: rpc error: code = Unknown desc = failed to get sandbox image \"registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1\": failed to pull image \"registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1\": failed to pull and unpack image \"registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1\": failed to resolve reference \"registry.cn-beijing.aliyuncs.com/images_k8s/pause-amd64:3.1\": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed"
May 26 14:41:04 zhangjun-k8s-03 kubelet[21054]: E0526 14:41:04.693544   21054 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
May 26 14:41:09 zhangjun-k8s-03 kubelet[21054]: E0526 14:41:09.697774   21054 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

**Comment by haiya512** [comment]
我的解决了，根据这个issue #601  的方案
