### ISSUE TITLE
06-6. 部署 calico 网络

### ISSUE THREAD

**Issue by lujf0910** [opsnull/follow-me-install-kubernetes-cluster#624]
**文档版本**
master版本

**现象描述**
06-6. 部署 calico 网络 章节 calico.yaml文件修改时候，要将# - name: CALICO_IPV4POOL_CIDR，该行注释去掉。

**Comment by shalousun** [comment]
3.13+版本开始的calico默认测试根本不需要做修改cidr都是自发现的。维度就是根据自己的网络需求看是否要关闭ipip模式

**Comment by fengjian1585** [comment]
注释掉后 分配 192.168 网段IP ， control-manster 定义的pod 地址不起作用。

**Comment by haiya512** [comment]
你可以看issue #612
