### ISSUE TITLE
关于Harbor创建问题

### ISSUE THREAD

**Issue by it2911** [opsnull/follow-me-install-kubernetes-cluster#64]
Harbor的运行好像是需要在docker上，请问这里的docker的安装，只是普通的安装么？如果方便的话，是否可以给出步骤。THX

**Comment by opsnull** [comment]
没明白你的意思。

直接参考文档中的步骤即可。

**Comment by it2911** [comment]
我按照官方文档，在集群里面部署好了docker之后，可以运行了。您这里是直接在master上运行的，本身是有docker的。我是在另外的机器上面部署的

**Comment by opsnull** [comment]
我尝试过二进制部署 harbor，但都以失败告终。。。
还是按照官方建议的、使用 docker-compose 来运行 harbor 吧。
