### ISSUE TITLE
 制作证书的过程是不是遗忘了K8S证书？制作步骤中并没有看到

### ISSUE THREAD

**Issue by Yangsheng93** [opsnull/follow-me-install-kubernetes-cluster#65]
如题，在制作证书中，并没用看到k8s相关证书的制作过程，你们的手册直接到了测试、验证。

**Comment by opsnull** [comment]
> 校验证书
> 
> 以校验 kubernetes 证书(后续部署 master 节点时生成的)为例：

注释中说明了证书是后续生成的。
