### ISSUE TITLE
watch chan error: etcdserver: mvcc: required revision has been compacted

### ISSUE THREAD

**Issue by wangycc** [opsnull/follow-me-install-kubernetes-cluster#66]
apiserver error日志:
            
    E0523 11:06:37.151092   22648 watcher.go:188] watch chan error: etcdserver: mvcc: required revision has been compacted

version：
- Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by wangycc** [comment]
Apiserver断断续续的刷着ERROR:

- E0523 11:06:37.151092   22648 watcher.go:188] watch chan error: etcdserver: mvcc: required revision has been compacted
- E0523 11:18:53.165478   22648 watcher.go:188] watch chan error: etcdserver: mvcc: required revision has been compacted
- E0523 11:37:25.642989   22648 watcher.go:188] watch chan error: etcdserver: mvcc: required revision has been compacted
- E0523 11:45:51.716376   22648 watcher.go:188] watch chan error: etcdserver: mvcc: required revision has been compacted

> etcdctl --ca-file=/etc/kubernetes/ssl/ca.pem --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ssl/kubernetes-key.pem cluster-health

    2017-05-23 12:02:28.608658 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
    2017-05-23 12:02:28.609368 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
    member 1261ad1b46e27ed5 is healthy: got healthy result from https://192.168.2.7:2379
    member 6795fffdfc180a59 is healthy: got healthy result from https://192.168.4.174:2379
    member f0b07cfcbaf17ad0 is healthy: got healthy result from https://192.168.4.232:2379
cluster is healthy

**Comment by opsnull** [comment]
应该是低版本 etcd 的bug，使用文档中的版本或官网最新版本。

**Comment by wangycc** [comment]
- E0525 22:56:13.915244   19879 kuberuntime_gc.go:123] Failed to remove container "af8224caa0d4323305a105dd57d99f4af0bc161a60aa132e6791f816aa997573": rpc error: code = 2 desc = failed to remove container "af8224caa0d4323305a105dd57d99f4af0bc161a60aa132e6791f816aa997573": Error response from daemon: {"message":"Driver overlay failed to remove root filesystem af8224caa0d4323305a105dd57d99f4af0bc161a60aa132e6791f816aa997573: remove /data/data/docker/overlay/c8ccd1ca2fd7db977596831eef663fa4e73bee48456c8458afac90281bb70d09/merged: device or resource busy"}

kubeletERROR日志，pod回收不了，手动删除容器也提示device or resource busy，经过排查是被Daemonset 容器进程占用了，有遇到吗

             [root@ip-10-255-1-141 merged]# grep -l c8ccd1ca2fd7db /proc/*/mountinfo
		grep: /proc/21778/mountinfo: Invalid argument
		/proc/31673/mountinfo
		[root@ip-10-255-1-141 merged]# ps -f 31673
		UID        PID  PPID  C STIME TTY      STAT   TIME CMD
		root     31673 31656  0 May18 ?        Ssl    3:38 /bin/node_exporter
		[root@ip-10-255-1-141 merged]# docker top 223c2cb3761c
		UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
		root                31673               31656               0                   May18               ?                   00:03:38            /bin/node_exporter

**Comment by opsnull** [comment]
有这种问题，等待官方修复。
