### ISSUE TITLE
harbor使用openssl自签发的证书一直导致浏览器无法打开ui

### ISSUE THREAD

**Issue by seecsea** [opsnull/follow-me-install-kubernetes-cluster#67]
使用openssl按照官网生成的证书启动harbor后，浏览器打开ui自动跳转到https页面，但是chrome和edge显示证书有问题，可能会被他们冒充来偷取信息等，页面无法打开。我看你这也是自签发的证书，没遇到这个问题么？

**Comment by opsnull** [comment]
使用自己 CA 签名的证书都有这个问题。

你可以将 CA 导入到浏览器中，这样浏览器就会信任它签名的证书，不会有那个提示。
