### ISSUE TITLE
monitoring-influxdb pod一直报错无法mount文件

### ISSUE THREAD

**Issue by seecsea** [opsnull/follow-me-install-kubernetes-cluster#69]
kubectl describe pod monitoring-influxdb-2075516717-w36cd -n kube-system
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  31d           32s             22316   kubelet, 10.20.107.45                   Warning         FailedMount     MountVolume.SetUp failed for volume "kubernetes.io/configmap/89d01b9d-24dd-11e7-8373-5254000d6f84-influxdb-config" (spec.Name: "influxdb-config") pod "89d01b9d-24dd-11e7-8373-5254000d6f84" (UID: "89d01b9d-24dd-11e7-8373-5254000d6f84") with: remove /var/lib/kubelet/pods/89d01b9d-24dd-11e7-8373-5254000d6f84/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy

**Comment by seecsea** [comment]
所在节点message里的日志：
May 26 00:11:18 k8s_n2 kubelet: E0526 00:11:18.272641   2478 atomic_writer.go:456] pod kube-system/monitoring-influxdb-2075516717-w36cd volume influxdb-con
fig: error pruning old user-visible path resolv.conf: remove /var/lib/kubelet/pods/89d01b9d-24dd-11e7-8373-5254000d6f84/volumes/kubernetes.io~configmap/infl
uxdb-config/resolv.conf: device or resource busy
May 26 00:11:18 k8s_n2 kubelet: E0526 00:11:18.272693   2478 atomic_writer.go:203] pod kube-system/monitoring-influxdb-2075516717-w36cd volume influxdb-con
fig: error removing old visible symlinks: remove /var/lib/kubelet/pods/89d01b9d-24dd-11e7-8373-5254000d6f84/volumes/kubernetes.io~configmap/influxdb-config/
resolv.conf: device or resource busy
May 26 00:11:18 k8s_n2 kubelet: E0526 00:11:18.272708   2478 configmap.go:218] Error writing payload to dir: remove /var/lib/kubelet/pods/89d01b9d-24dd-11e
7-8373-5254000d6f84/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy
May 26 00:11:18 k8s_n2 kubelet: E0526 00:11:18.272829   2478 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/configmap/89d01b9d-24dd-11e7-83
73-5254000d6f84-influxdb-config\" (\"89d01b9d-24dd-11e7-8373-5254000d6f84\")" failed. No retries permitted until 2017-05-26 00:13:18.272791726 ＋0800 CST (du
rationBeforeRetry 2m0s). Error: MountVolume.SetUp failed for volume "kubernetes.io/configmap/89d01b9d-24dd-11e7-8373-5254000d6f84-influxdb-config" (spec.Nam
e: "influxdb-config") pod "89d01b9d-24dd-11e7-8373-5254000d6f84" (UID: "89d01b9d-24dd-11e7-8373-5254000d6f84") with: remove /var/lib/kubelet/pods/89d01b9d-2
4dd-11e7-8373-5254000d6f84/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy

**Comment by wangycc** [comment]
这些ERROR我也有，通过/proc/*/mountinfo查询，老是被daemoset(prometheus的node_exporter和EFK的fluentd)资源进程占用了。

**Comment by opsnull** [comment]
是的，daemonset 容易引起这种问题，目前还没有解决办法。

**Comment by wangycc** [comment]
目前有解决办法了吗
