### ISSUE TITLE
monitoring-influxdb-16771525

### ISSUE THREAD

**Issue by flameyucong** [opsnull/follow-me-install-kubernetes-cluster#72]
MountVolume.SetUp failed for volume "kubernetes.io/configmap/af0a362d-421a-11e7-b5af-00505681671d-influxdb-config" (spec.Name: "influxdb-config") pod "af0a362d-421a-11e7-b5af-00505681671d" (UID: "af0a362d-421a-11e7-b5af-00505681671d") with: remove /var/lib/kubelet/pods/af0a362d-421a-11e7-b5af-00505681671d/volumes/kubernetes.io~configmap/influxdb-config/resolv.conf: device or resource busy

**Comment by opsnull** [comment]
这是由于其它Pod 如 daemonset 在占用 pod 文件，目前没有好的解决方案。等待官方修复。

**Comment by flameyucong** [comment]
多谢
