### ISSUE TITLE
集群整体架构图的问题。

### ISSUE THREAD

**Issue by cnicy** [opsnull/follow-me-install-kubernetes-cluster#73]
能不能出一个集群的整体架构图，比如有几个master几个node。master分别安装哪些组建，node安装哪些组件，下面的结构不知道对不对。
master：apiserver、controller manager、scheduler、proxy、etcd、flannel、kubelet
node：proxy、kubelet、flannel
目前master有三台服务器，node若干。

**Comment by opsnull** [comment]
看起来你已经发现了部署 master 和 node 节点的文档开头分别提到了 master 和 node 节点的组件，:)

**Comment by cnicy** [comment]
@opsnull  是的。😄
