### ISSUE TITLE
cfssl: command not found

### ISSUE THREAD

**Issue by jiangmin168168** [opsnull/follow-me-install-kubernetes-cluster#80]
安装cfssl确定步骤正确吗，我是ubuntu 16.04, 但提示cfssl: command not found,是我操作不对还是说少了什么步骤？

https://github.com/opsnull/follow-me-install-kubernetes-cluster/blob/master/02-%E5%88%9B%E5%BB%BACA%E8%AF%81%E4%B9%A6%E5%92%8C%E7%A7%98%E9%92%A5.md

**Comment by opsnull** [comment]
你没看清楚文档中设置 PATH 和 mv 的命令行参数。
