### ISSUE TITLE
flannel 网络网关互通，但是pod内的ip 相互不通

### ISSUE THREAD

**Issue by mohaijiang** [opsnull/follow-me-install-kubernetes-cluster#81]
在 flannel 项目的issue 找到了解决方法

    sudo iptables -P FORWARD ACCEPT

[Container can not be accessed by another Docker host](https://github.com/coreos/flannel/issues/609)

**Comment by opsnull** [comment]
新版 docker 可能会将 FORWARD 的缺省 policy 设置为 DROP，进而 引起 pod 互联互通失败。

在部署 kubernetes 节点的文档中有提醒。

**Comment by laokan** [comment]
如果是在centos7 系统上是因为系统默认得iptables 规则禁用了这个 开放即可
