### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by langtu329** [opsnull/follow-me-install-kubernetes-cluster#82]
health check for peer ec2a7add58746895 could not connect: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
etcd 加入ssl后报证书问题，这种自签名证书报错，正常吗？

**Comment by opsnull** [comment]
应该是没有指定 CA 证书，或者指定的 CA 证书有误。

**Comment by opsnull** [comment]
@langtu329 问题解决了么？

**Comment by langtu329** [comment]
谢谢，问题解决了，是证书的问题
