### ISSUE TITLE
无法获取节点信息

### ISSUE THREAD

**Issue by big-loser** [opsnull/follow-me-install-kubernetes-cluster#84]
centos 7.2.1511 内核bug

会导致问题。

https://github.com/kubernetes/kubernetes/issues/43856

**Comment by opsnull** [comment]
老版本的docker使用的是systemd，和 kublet 默认的 cgroupfs 不一致。
文档中使用的是最新版 docker，默认值是 cgroupfs，和 Kublet 的默认值一致，所以没有这个问题。
