### ISSUE TITLE
heapster   安装cpu和mem没有显示 grafana也没有数据

### ISSUE THREAD

**Issue by fujianan** [opsnull/follow-me-install-kubernetes-cluster#85]
Kubernetes master is running at https://192.168.233.161:6443
Heapster is running at https://192.168.233.161:6443/api/v1/proxy/namespaces/kube-system/services/heapster
kubernetes-dashboard is running at https://192.168.233.161:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
monitoring-grafana is running at https://192.168.233.161:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
monitoring-influxdb is running at https://192.168.233.161:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

**Comment by opsnull** [comment]
就这些信息，解决不了问题。
