### ISSUE TITLE
08DNS部署验证时 容器内不能ping通10.254.0.2DNS地址

### ISSUE THREAD

**Issue by zhengJunhui** [opsnull/follow-me-install-kubernetes-cluster#86]
root@nginx:/# cat /etc/resolv.conf 
nameserver 10.254.0.2
search default.svc.cluster.local. svc.cluster.local. cluster.local. localdomain
options ndots:5

root@nginx:/# ping my-nginx
ping: unknown host
root@nginx:/# ping kubernetes
ping: unknown host
root@nginx:/# ping 10.254.0.2
PING 10.254.0.2 (10.254.0.2): 48 data bytes
^C--- 10.254.0.2 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss

成功部署pod nginx后在进入容器 不能Ping通相关server

以及09部署dashboard 
外部通过nodeIP :nodePort无法访问，但是在对应的node节点却可以访问
请大神赐教

**Comment by opsnull** [comment]
ping 不通 正常，K8S Service IP 都是 ping 不通的(因为它不是网络接口地址，只是存在于iptables中的徐地址)。

目前看问题是你的 pod 和 service ip 不通，需要检查下 flannel、iptables 是否正常。

**Comment by 13567436138** [comment]
怎么解决的，我也遇到这个问题
