### ISSUE TITLE
[WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for websites

### ISSUE THREAD

**Issue by langtu329** [opsnull/follow-me-install-kubernetes-cluster#88]
echo '{"CN":"kubernetes","hosts":[""],"key":{"algo":"rsa","size":2048},"names":[{"C":"CN","ST":"BeiJing","L":"BeiJing","O":"system:masters","OU":"System"}]}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes  - | cfssljson -bare admin
创建证书经常报这个错误，
[WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);

**Comment by nboooo0** [comment]
这是警告信息 可以忽略

**Comment by opsnull** [comment]
是的，cfssl 的 bug，可以忽略。
