### ISSUE TITLE
向 etcd 写入集群 Pod 网段信息报错

### ISSUE THREAD

**Issue by MarxGo** [opsnull/follow-me-install-kubernetes-cluster#90]
在向 etcd 写入集群 Pod 网段信息 时 返回
2017-07-03 00:19:03.846213 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
Error:  client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
; error #1: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
; error #2: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
error #1: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
error #2: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

在etcd集群检查的时候输出是通过了的
2017-07-03 00:26:44.728524 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
https://192.168.137.171:2379 is healthy: successfully committed proposal: took = 3.140706ms
2017-07-03 00:26:44.773391 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
https://192.168.137.172:2379 is healthy: successfully committed proposal: took = 2.187144ms
2017-07-03 00:26:44.808330 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
https://192.168.137.173:2379 is healthy: successfully committed proposal: took = 3.097542ms

这是为什么?请大神赐教

**Comment by MarxGo** [comment]
补充, 加入 --debug参数后显示
/root/local/bin/etcdctl   --endpoints=${ETCD_ENDPOINTS}   --ca-file=/etc/kubernetes/ssl/ca.pem   --cert-file=/etc/flanneld/ssl/flanneld.pem   --key-file=/etc/flanneld/ssl/flanneld-key.pem --debug ls
2017-07-03 00:39:46.669008 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
start to sync cluster using endpoints(http://192.168.137.173:2379,http://192.168.137.171:2379,http://192.168.137.172:2379)
cURL Command: curl -X GET http://192.168.137.173:2379/v2/members
cURL Command: curl -X GET http://192.168.137.171:2379/v2/members
cURL Command: curl -X GET http://192.168.137.172:2379/v2/members
got endpoints(http://192.168.137.173:2379,http://192.168.137.171:2379,http://192.168.137.172:2379) after sync
Cluster-Endpoints: http://192.168.137.173:2379, http://192.168.137.171:2379, http://192.168.137.172:2379
cURL Command: curl -X GET http://192.168.137.173:2379/v2/keys/?quorum=false&recursive=false&sorted=false
cURL Command: curl -X GET http://192.168.137.171:2379/v2/keys/?quorum=false&recursive=false&sorted=false
cURL Command: curl -X GET http://192.168.137.172:2379/v2/keys/?quorum=false&recursive=false&sorted=false
Error:  client: etcd cluster is unavailable or misconfigured; error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
; error #1: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
; error #2: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

error #0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
error #1: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
error #2: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

**Comment by MarxGo** [comment]
问题解决了,好像是Xshell的问题,换了台机器就好了

**Comment by 3792274** [comment]
![image](https://user-images.githubusercontent.com/19231863/30043270-0af84bf8-9229-11e7-8670-e970f51c805e.png)
