### ISSUE TITLE
etcd 启动不了

### ISSUE THREAD

**Issue by baikingrio** [opsnull/follow-me-install-kubernetes-cluster#91]
[root@k8s-master etcd]# systemctl status etcd
etcd.service - Etcd Server
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mo 2017-07-03 13:05:37 CEST; 1s ago
     Docs: https://github.com/coreos
  Process: 11023 ExecStart=/root/local/bin/etcd --name=${NONDE_NAME} --cert-file=/etc/etcd/ssl/etcd.pem --key-file=/etc/etcd/ssl/etcd-key.pem --peer-cert-file=/etc/etcd/ssl/etcd.pem --peer-key-file=/etc/etcd/ssl/etcd-key.pem --trusted-ca-file=/etc/kubernetes/ssl/ca.pem --peer-trusted-ca-file=/etc/kubernetes/ssl/ca.pem --initial-advertise-peer-urls=https://${NODE_IP}:2380 --listen-peer-urls=https://${NODE_IP}:2380 --listen-client-urls=https://${NODE_IP}:2379,http://127.0.0.1:2379 --advertise-client-urls=https://${NODE_IP}:2379 --initial-cluster-token=etcd-cluster-0 --initial-cluster=${ETCD_NODES} --initial-cluster-state=new --data-dir=/var/lib/etcd (code=exited, status=1/FAILURE)
 Main PID: 11023 (code=exited, status=1/FAILURE)

Jul 03 13:05:37 k8s-master systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Jul 03 13:05:37 k8s-master systemd[1]: Failed to start Etcd Server.
Jul 03 13:05:37 k8s-master systemd[1]: Unit etcd.service entered failed state.
[root@k8s-master etcd]#

**Comment by opsnull** [comment]
> Process: 11023 ExecStart=/root/local/bin/etcd --name=${NONDE_NAME} --cert-file=/etc/etcd/ssl/etcd.pem --key-file=/etc/etcd/ssl/etcd-key.pem --peer-cert-

这些 ${xxx} 变量是需要被定义或 source 的 shell 环境变量替换的。 参考文档中的 here 文档语法。

**Comment by baikingrio** [comment]
是的，这些变量我都有执行environment.sh和执行export NODE_NAME=xxx的方式添加到系统环境变量中了的。

2017-07-03 20:31 GMT+08:00 ZhangJun <notifications@github.com>:

**Comment by ww110052181** [comment]
这个问题怎么解决，没有解决干嘛关闭
