### ISSUE TITLE
容器内无法访问主机所在的网络的机器

### ISSUE THREAD

**Issue by JackFong** [opsnull/follow-me-install-kubernetes-cluster#94]
所有组件都正常，容器内也能相互访问，但是就是容器内无法访问主机所在网络里的其它机器。

后来我发现iptables里的docker0相关的配置都消失了。于是只能重新启动恢复docker0。

现在可以正常的访问任何内网的机器了。

但是，这个是什么原因导致的docker0的路由配置全部消失的？

**Comment by opsnull** [comment]
在部署 Node 节点一章有先清理 iptables 规则，再起 docker、kubelet、kube-proxy的步骤，如果顺序不对的话，可能会丢失 iptables 规则。
