### ISSUE TITLE
kubelet.server命令错误，之前一直不成功，修改后成功了

### ISSUE THREAD

**Issue by neilqin** [opsnull/follow-me-install-kubernetes-cluster#95]
--cert-dir=/etc/kubernetes/ssl \\
  --cluster_dns=${CLUSTER_DNS_SVC_IP} \\
  --cluster_domain=${CLUSTER_DNS_DOMAIN} \\
  --hairpin-mode promiscuous-bridge \\

这里--cluster_dns应该是--cluster-dns，--cluster_domain应该是--cluster-domain

修改后就可以了

**Comment by opsnull** [comment]
多谢反馈，已修复！
