### ISSUE TITLE
DNS部署失败,pod创建成功,但是无法解析

### ISSUE THREAD

**Issue by MarxGo** [opsnull/follow-me-install-kubernetes-cluster#96]
在配置集群时我做了几个改动
1. 改变了 `environment.sh`中的`CLUSTER_DNS_DOMAIN="cluster.local."`,变为`CLUSTER_DNS_DOMAIN="cluster.local"`
2. 在我直接创建dns的时候rs会报一个
`service account kube-system/kube-dns was not found, retry after the service account is created`
的错误,此时`kubectl get sa --all-namespaces=true`的结果是
NAMESPACE     NAME       SECRETS   AGE
default       default    1         1d
default       kube-dns   1         1h
kube-public   default    1         1d
kube-system   default    1         1d

所以我用类似于给dashbord创建用户的方式在`kube-system`这个namespace 下创建了一个kube-dns账户

3. 在我直接修改完dns-controller.yaml后创建,容器启动会报错如下
`k8s_sidecar_kube-dns`:

> invalid argument "kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local.5,A" for --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local.5,A: strconv.ParseInt: parsing "A": invalid syntax
> Usage of /sidecar:
>       --alsologtostderr                  log to standard error as well as files
>       --dnsmasq-addr string              address that the dnsmasq server is listening on (default "127.0.0.1")
>       --dnsmasq-poll-interval-ms int     interval with which to poll dnsmasq for stats (default 5000)
>       --dnsmasq-port int                 port that the dnsmasq server is listening on (default 53)
>       --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
>       --log-dir string                   If non-empty, write log files in this directory
>       --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
>       --logtostderr                      log to standard error instead of files (default true)
>       --probe string                     probe the given DNS server with the DNS name and export probe metrics and healthcheck URI. Specified as <label>,<server>,<dns name>[,<interval_seconds>][,<type>]. Healthcheck url will be exported under /healthcheck/<label>. inter
> val_seconds is optional. This option may be specified multiple times to check multiple servers. <type> is one of ANY, A, AAAA. Example: 'mydns,127.0.0.1:53,example.com,10,A'. (default "[]")      --prometheus-addr string           http addr to bind metrics server to (default "0.0.0.0")
>       --prometheus-namespace string      prometheus metric namespace (default "kubedns")
>       --prometheus-path string           http path used to export metrics (default "/metrics")
>       --prometheus-port int              http port to use to export prometheus metrics (default 10054)
>       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
>   -v, --v Level                          log level for V logs (default 0)
>       --version version[=true]           Print version information and quit
>       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
> 
因此我修改了dns-controller中的
>         - --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
>         - --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
把最后的那个`,A`去掉了

现在dns的pod启动正常,进入pod-nginx后
root@nginx:/# cat /etc/resolv.conf
nameserver 10.254.0.2
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

root@nginx:/# ping my-nginx
ping: unknown host
root@nginx:/# ping kubernetes
ping: unknown host
root@nginx:/# ping kube-dns.kube-system.svc.cluster.local
ping: unknown host

请问这时应该往什么方向排查错误呢?

**Comment by opsnull** [comment]
你的 yaml 有问题：

> invalid argument "kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local.5,A" for --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local.5,A: strconv.ParseInt: parsing "A": invalid syntax

local. 和 5 之间少了 逗号。
