### ISSUE TITLE
watch chan error: etcdserver: mvcc: required revision has been compacted

### ISSUE THREAD

**Issue by langtu329** [opsnull/follow-me-install-kubernetes-cluster#97]
systemctl status kube-apiserver -l  这个报错有问题吗？
Jul 06 09:25:44 iZ23psueoqtZ kube-apiserver[27196]: E0706 09:25:44.826693   27196 watcher.go:188] watch chan error: etcdserver: mvcc: required revision has been compacted

**Comment by opsnull** [comment]
感觉问题不大，只是历史版本数据被清理了，不影响当前数据。

BTW，etcd 的 compact 周期是可配置的，你可以调大些。

**Comment by zhaolinew** [comment]
我也有这样的错误，请问那里可以调etcd compact周期？

**Comment by zhaolinew** [comment]
Oct 16 20:09:13 master1 kube-apiserver[912]: E1016 20:09:13.694262     912 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
