### ISSUE TITLE
部署EFK插件问题

### ISSUE THREAD

**Issue by neilqin** [opsnull/follow-me-install-kubernetes-cluster#99]
在create -f .后，启动了，在你说的“在 Settings -> Indices 页面创建一个 index（相当于 mysql 中的一个 database），选中 Index contains time-based events，使用默认的 logstash-* pattern，点击 Create ;”，我访问页面，setting的时候没有出现create按钮，看日志有404，如下，不知道是哪里出了问题：
`{"type":"response","@timestamp":"2017-07-07T07:38:37Z","tags":[],"pid":7,"method":"get","statusCode":404,"req":{"url":"/elasticsearch/logstash-*/_mapping/field/*?_=1499413135465&allow_no_indices=false&ignore_unavailable=false&include_defaults=true","method":"get","headers":{"host":"10.134.94.7:5601","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0","accept":"application/json, text/plain, */*","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3","kbn-version":"4.6.1","referer":"http://10.10.16.128:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging/app/kibana","x-forwarded-uri":"/api/v1/proxy/namespaces/kube-system/services/kibana-logging/elasticsearch/logstash-*/_mapping/field/*"},"remoteAddress":"10.133.76.0","userAgent":"10.133.76.0","referer":"http://10.10.16.128:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging/app/kibana"},"res":{"statusCode":404,"responseTime":5,"contentLength":9},"message":"GET /elasticsearch/logstash-*/_mapping/field/*?_=1499413135465&allow_no_indices=false&ignore_unavailable=false&include_defaults=true 404 5ms - 9.0B"}`

**Comment by opsnull** [comment]
> kibana Pod 第一次启动时会用**较长时间(10-20分钟)**来优化和 Cache 状态页面，可以 tailf 该 Pod 的日志观察进度：

kibana 优化状态页面结束了么？那个页面应该在优化结束后才能看到。

**Comment by liyubao1984** [comment]
我的EFK 一直提示elasticsearch 插件timeout，不知道是什么原因

**Comment by post707** [comment]
@neilqin @opsnull 我也出现了这个问题
网页上显示的是Unable to fetch mapping. Do you have indices matching the pattern?

**Comment by neilqin** [comment]
@post707 @opsnull 对我就是这个问题，一直没法创建，这里在文件fluentd-es-ds.yaml里面有挂载本地目录，我docker目录配置到别的地方了，我修改成如下：

volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /data/docker/run/containers


还是不行,一直是post707这个问题

**Comment by post707** [comment]
@neilqin @opsnull 我的问题找到了，是因为docker没有使用默认的输出方式，使用了journald。

**Comment by neilqin** [comment]
@post707 我没有配置--log-driver这个，默认是journald？你怎么配置好的？是修改docker.service里面吗

**Comment by post707** [comment]
使用默认的就可以

**Comment by neilqin** [comment]
@post707 我都没有配置它的输出方式了，你怎么改动的，说来看看？你不是用systemctl start docker方式启动的吗？

**Comment by post707** [comment]
没有配置就是默认

**Comment by neilqin** [comment]
@opsnull 从请求url来看，是请求"ip:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging/elasticsearch/logstash-*/_mapping/field/*?_=1501656086826&ignore_unavailable=false&allow_no_indices=false&include_defaults=true"返回了404，
原始输出：{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"logstash-*","index":"logstash-*"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"logstash-*","index":"logstash-*"},"status":404}

好像是说no search index，这不是正要创建吗？不知道还要怎么处理

**Comment by rainard** [comment]
# 执行后， kubectl create -f fluentd-es-ds.yaml 发现pods奔溃了，查看容器日志，发现这个
Could not open library 'libsystemd.so.0': libgcrypt.so.11: cannot open shared object file: No such file or directory

**Comment by opsnull** [comment]
#119 提到了这个问题，升级版本后解决。

**Comment by chinakevinguo** [comment]
@post707 你的意思是把默认的journald 删掉吧

**Comment by xkai08** [comment]
@neilqin 跟你一样的问题，浏览器控制台404
`No matching indices found: No indices match pattern "logstash-*"``
不显示create按钮

**Comment by xkai08** [comment]
@post707 nice,删掉这个重启docker服务解决问题
